<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ui-id-29</name>
   <tag></tag>
   <elementGuidId>aa859000-e763-4744-8ffd-9a38348c0a0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.NevOfficeadminEncounter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' NevOfficeadminEncounter ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Encounters&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>08058142-95df-4318-9eff-6a58e2e7a525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Encounter</value>
      <webElementGuid>f85d5868-6de0-4fdd-96ae-516ff840c5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NevOfficeadminEncounter ui-tabs-anchor</value>
      <webElementGuid>2bebb413-945a-402e-a2da-59bd18e162d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thirdnavigation</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>12152148-44b1-4577-bf2a-c429a0f65885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>../Home/Encounter_Admin_menu</value>
      <webElementGuid>e22a70c9-76dc-4249-8927-6994c8d7f1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ShowOfficeAdminEncounterElement(this);</value>
      <webElementGuid>847755b3-ec71-4a09-97dd-7239b7467553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>87d677b1-95df-414a-bda2-5c0657800a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4feb83d1-8ade-470f-a33a-88723e237fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-29</value>
      <webElementGuid>a61f8c2a-ba40-47df-bff4-c2139624447c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Encounters</value>
      <webElementGuid>d4d527ca-c2bd-464d-a1d2-18cac9dae61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-74b43ebe56b181ed6a1379de490c8137</value>
      <webElementGuid>f3941faf-831e-4d1b-9938-82e02d8b4905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' NevOfficeadminEncounter ')]</value>
      <webElementGuid>5f5baf80-19ae-4874-a47c-865f96f29974</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' NevOfficeadminEncounter ')]</value>
      <webElementGuid>92a45c2d-4a4a-490c-92f1-17f5444e033b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#Encounter' and @id = 'ui-id-29' and (text() = 'Encounters' or . = 'Encounters')]</value>
      <webElementGuid>3b4ec26c-da98-421c-ba95-6a421301f42b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
