<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ApptTemplate</name>
   <tag></tag>
   <elementGuidId>d5de010c-cdb9-4512-9453-93f6aa62a3d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ApptTemplate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ApptTemplate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Appointment Templates&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54413ec2-edef-46ee-9534-7fd64bc53b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApptTemplate</value>
      <webElementGuid>570d7e47-e89f-478f-8f4a-7cceaef44612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ecf3cef7-1384-4408-b6d9-294e69ab47d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NevAppointmentTemplate</value>
      <webElementGuid>876667b1-11dd-4fa3-b414-022dce36dded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>Scheduler</value>
      <webElementGuid>245a8967-d8e5-4c66-aa40-090a58f7ed37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>../SchedulerAppointment/GetAppointmentTemplateList</value>
      <webElementGuid>824db953-b242-43a7-990d-34cda9423320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SaveScheduleGeneralOfficeAdmin(); ShowOfficeAdminEncounterElement(this);</value>
      <webElementGuid>9ebb20a1-c2c5-431d-b4d2-4ff597d6b199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Appointment Templates</value>
      <webElementGuid>db7a24a5-bb43-459a-97ff-1814e9f1de2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c867637fe66a31d43b218e4631580cef</value>
      <webElementGuid>e9b0b25d-9ef1-4242-a9ff-92e72ddab4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ApptTemplate']</value>
      <webElementGuid>2675e2c9-e411-49ee-adc9-c8ec3cffc1c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ApptTemplate']</value>
      <webElementGuid>5217219b-2de2-4820-b364-df22bbd16305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ApptTemplate' and @href = '#' and (text() = 'Appointment Templates' or . = 'Appointment Templates')]</value>
      <webElementGuid>d3178c9b-94d2-4f02-89e4-ddb0ec4b3a5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
