<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_drpAppointmentType_I</name>
   <tag></tag>
   <elementGuidId>1698e6be-c584-4b88-98bb-deea6099ac9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drpAppointmentType_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'drpAppointmentType_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drpAppointmentType_I</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e30fc9b5-c721-4501-9f29-082064831890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Metropolis dxeEditAreaSys dxh0</value>
      <webElementGuid>d5b113a4-13bb-419b-96f0-dabe328a087a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpAppointmentType_I</value>
      <webElementGuid>7d10955d-0c53-4cdc-9585-42161b845c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>drpAppointmentType</value>
      <webElementGuid>49d51a10-845a-47e0-a4c0-9c13b066e96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('drpAppointmentType')</value>
      <webElementGuid>74b7e413-bff8-4075-9616-a49ada5c6354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('drpAppointmentType')</value>
      <webElementGuid>40f6475a-aa7a-4180-a691-6d6f0e22a407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.ETextChanged('drpAppointmentType')</value>
      <webElementGuid>83d561b5-79a6-45b8-97a9-d61f74fc393d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>--Select--</value>
      <webElementGuid>28d64127-090a-4f8d-a1f7-639865bc5896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30b9107c-e629-4640-baf0-3723a5367528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b74cb2d4-a715-435a-8504-a8e8e9d11263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>savedspellcheck</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>63d8c1db-aa15-4315-a2be-a7af216b56c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>83018056-bc7a-4379-a99b-ee4c9201ee26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-96e3bbf42b96fb2b98eca377a426c5ce</value>
      <webElementGuid>d4291bc7-b699-4e2d-b90f-d9d34638fd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'drpAppointmentType_I']</value>
      <webElementGuid>dbdb80ad-8ee2-4d9d-8891-9cbb68cfc966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'drpAppointmentType_I']</value>
      <webElementGuid>375466b7-3ac8-4503-aefd-79686082ab88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'drpAppointmentType_I' and @name = 'drpAppointmentType' and @type = 'text']</value>
      <webElementGuid>7b7fae53-9f6a-4dc7-8b70-98c93583afbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
