<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BtnAddEventToTemplate</name>
   <tag></tag>
   <elementGuidId>e195c4c2-975a-4c24-b30d-fe7e25108cb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BtnAddEventToTemplate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'BtnAddEventToTemplate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add Event to Template&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>795962a0-5b76-45ad-af12-1e323097d59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b7c059a-63cf-4796-b815-92947d9948e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary mini-button</value>
      <webElementGuid>c359c67e-c367-4231-94d3-1aee141bce83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnAddEventToTemplate</value>
      <webElementGuid>ad75d6e6-d58d-4f7c-935d-2fb622cdbfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add Event to Template</value>
      <webElementGuid>79f25084-c3c9-4255-a4f4-78a96100001e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ca4cc2f4eec7c3392a06f82d777e69ba</value>
      <webElementGuid>04442d7d-379e-4863-a3fb-15c0a598e2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'BtnAddEventToTemplate']</value>
      <webElementGuid>7dca7164-bb82-4889-b195-3afa70b5835c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'BtnAddEventToTemplate']</value>
      <webElementGuid>994be7ef-593f-4c8c-8703-369723bbc79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'BtnAddEventToTemplate']</value>
      <webElementGuid>af524a2e-4715-4eec-bb2d-38c4e6f916c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
