<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_wizard_save</name>
   <tag></tag>
   <elementGuidId>65c6ffad-29f6-4a89-ae52-ebae5cd83710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wizard_save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'wizard_save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;SAVE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecf3179f-cb34-4515-aba4-531ba9600a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0cfded26-6560-4aa4-baee-8fd115573976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wizard_save</value>
      <webElementGuid>77df20de-006b-4908-bb16-83d57520fcc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SAVE</value>
      <webElementGuid>5f75ce3f-6b4d-4018-a918-3560bba2da96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SAVE</value>
      <webElementGuid>353ec7e8-591e-47e9-ab9d-38056d14746f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button small-button30 primary</value>
      <webElementGuid>f4eb63b2-cd21-45b1-8734-a2210cbf7a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-db3016bc4bb81a8920391671baf1056c</value>
      <webElementGuid>c8af52e8-0ee8-4c03-aa49-d6a0076472f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'wizard_save']</value>
      <webElementGuid>7adee416-5f84-4823-be80-65508a8e91f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'wizard_save']</value>
      <webElementGuid>0ffabce2-1b8f-4626-b733-06e5f79896a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'wizard_save' and @title = 'SAVE']</value>
      <webElementGuid>0daacba7-a37a-46c3-bb2e-0542fc0cfa62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
