<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ui-id-9</name>
   <tag></tag>
   <elementGuidId>1bb39881-4236-48fd-971d-bac52fd4c9f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '#auth_SecureMessagesMail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\#auth_SecureMessagesMail&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Secure Messages&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f83f5e20-9d7d-433f-bef9-5cbc7171bda8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#auth_SecureMessagesMail</value>
      <webElementGuid>a5b6bde5-52b1-4aa5-85d0-8491fd4ecbe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectorForGoogleAnalytics ui-tabs-anchor</value>
      <webElementGuid>f5dcd6a1-4184-47d1-926f-1a65d35cec42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>7e38e611-44b3-4826-bbd4-8cf9f51c416e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fc6cffaf-987a-4bf6-bbac-e8ca498dd342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-9</value>
      <webElementGuid>f3f31f96-27e3-4041-9acf-bffc28742d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-tab-content-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1607d5be-6c6f-4a0c-adfe-e045ff3f8631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Secure Messages</value>
      <webElementGuid>3461e903-f7ce-45cb-bf81-d259fd7e69a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-908dab4534544b2a84400403ea2716ad</value>
      <webElementGuid>ae141224-a98f-4cfc-ba1a-98bd627c85cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '#auth_SecureMessagesMail']</value>
      <webElementGuid>7e2fd164-4278-4f81-ab5f-16e54bcfec55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '#auth_SecureMessagesMail']</value>
      <webElementGuid>27b28f2d-9395-4073-a7bb-cec8339406b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#auth_SecureMessagesMail' and @id = 'ui-id-9' and (text() = 'Secure Messages' or . = 'Secure Messages')]</value>
      <webElementGuid>3faefe23-a80a-41e6-845e-32e11645786e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
