<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Inbox</name>
   <tag></tag>
   <elementGuidId>b03c8ab4-626f-4164-8ec6-90e40d4469aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@class,'patientRibbonAddDropdown')]//div[text()='Inbox'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[onclick=&quot;selectMenu\(this\)&quot;]:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Outbox$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8da83a28-1b78-41a1-b580-659b0a8c9c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selectMenu(this)</value>
      <webElementGuid>64d82ba5-e96f-4008-8c05-73fae84a3d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outbox</value>
      <webElementGuid>e358e9d1-0bb8-4453-9d48-e738085d6fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-58213303eccc55e06b78672ae8acaffd</value>
      <webElementGuid>3ceca482-b30e-4fad-be4f-c2e8839675e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@onclick = 'selectMenu(this)') and (position() = 1)]</value>
      <webElementGuid>11ea600a-0071-4439-b288-d049d9d1ac7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[contains(@class,'patientRibbonAddDropdown')]//div[text()='Inbox'])[3]</value>
      <webElementGuid>b76e0e5c-ea8e-485f-9e0f-de2d570d7b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Inbox' or . = 'Inbox')]</value>
      <webElementGuid>17d8f5a7-9591-4a30-97bb-8909ec2b9c58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
