<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnCancelDeleteMsg</name>
   <tag></tag>
   <elementGuidId>566444a0-8339-4048-913e-3fcb50e79d84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnCancelDeleteMsg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnCancelDeleteMsg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;NO&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4281d99-6915-4043-87a1-4268540acbd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8aaecb8d-f5fa-4873-b53d-0a0cf12b140e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirmbar-btn-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9b6b1c96-9e72-4792-9fa0-3eb4f2445182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>5e15fcfc-99a7-48c8-be0e-496f7edc5fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semi-bold font20 hide-confirmation ignore-action-toggle margin-right-10px margin-top-10px  notifationButton</value>
      <webElementGuid>62e2001b-cfec-4049-8452-38e9f73f1d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>77fc70b1-6b4a-4209-bacc-7e226a702ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCancelDeleteMsg</value>
      <webElementGuid>5fb9b9a3-5c5a-4fbd-922d-4c4596a97bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-496bb62ce0cf091e9acab6443d4595fb</value>
      <webElementGuid>cee60ba8-9dc2-4b04-ab4f-832a0f646e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnCancelDeleteMsg']</value>
      <webElementGuid>35e7a073-651b-49e5-a8c0-39d7e53a8db6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnCancelDeleteMsg']</value>
      <webElementGuid>cc5c010b-c758-4820-92f8-13fdab84ca76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnCancelDeleteMsg']</value>
      <webElementGuid>f6432db3-4d13-45e9-8fc8-489aaad1ee44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
