<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SelectedEduMaterialSignOff</name>
   <tag></tag>
   <elementGuidId>9a9d4e07-232b-4bf6-a664-47ec76dae5eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'SelectedEduMaterialSignOff']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SelectedEduMaterialSignOff</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Send Education Material from selected Elements on Sign off of encounter&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17869b6b-e1cf-4b18-8908-851956777d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preferencetype</name>
      <type>Main</type>
      <value>EDUCATION_MATERIAL</value>
      <webElementGuid>e3da9a95-a05b-4f96-918c-c6bea7149e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio custom-radio</value>
      <webElementGuid>c5637677-ac1d-4912-946b-2c1566227bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-radiocheck-toggle</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>94417ada-ef01-4658-8ebc-30a04b9e079a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bcd9834d-e8bf-41e0-92cd-16e3f863977c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SelectedEduMaterialSignOff</value>
      <webElementGuid>691446e6-662c-487b-8b4a-fd514fb063ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EDUCATION_MATERIAL_PREFERENCE_ON_ENCOUNTER_SIGNOFF</value>
      <webElementGuid>ffa97839-17eb-444e-b888-c39db5e62ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>UpdateIncProgramsPreference(this)</value>
      <webElementGuid>9f72c12d-6728-4001-a867-5e7126a48d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e4801021-8476-4f51-88f9-4ec051151d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SELECTED_ELEMENTS</value>
      <webElementGuid>8bcd6515-b3a7-42b4-9bf1-6c00a55d0b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preferenceid</name>
      <type>Main</type>
      <value>9183</value>
      <webElementGuid>638571f8-7310-4279-84f2-2b1e4c23bfb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-745b5f61a4981058ff0ea36c62c69205</value>
      <webElementGuid>6d7d5c45-0a4c-4f20-8260-c6bb50e356f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'SelectedEduMaterialSignOff']</value>
      <webElementGuid>0051e902-99c5-4694-953b-36962c0f697c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'SelectedEduMaterialSignOff']</value>
      <webElementGuid>46960406-ae8b-4ed6-a012-a84857d36bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SelectedEduMaterialSignOff' and @name = 'EDUCATION_MATERIAL_PREFERENCE_ON_ENCOUNTER_SIGNOFF' and @type = 'radio']</value>
      <webElementGuid>2133a738-5976-421a-8e4d-4b0329cc8c8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
