<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Eyeclinic.net PortalMaximeyes Patien_ff78b6</name>
   <tag></tag>
   <elementGuidId>677a7f7a-d66f-48bc-9e71-2c19927e2bb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PortalOptions']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PortalOptions</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PortalOptions</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cf488afc-2075-4ca5-a321-2a1f39045dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PortalOptions</value>
      <webElementGuid>975f6bc4-2559-4034-806c-24b3904f0361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PortalOptions</value>
      <webElementGuid>f2dc30ed-47d4-4628-b560-e2f628291668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eyeclinic.net Portal
Maximeyes Patient Portal
</value>
      <webElementGuid>1015cec1-949b-4556-96bf-3454d16f9981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PortalOptions&quot;)</value>
      <webElementGuid>a4123170-4558-4dd7-82e8-1a80c42e0c07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PortalOptions']</value>
      <webElementGuid>41c820dd-6712-44bf-8bb9-f03f042ef444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divVendorsNotificationConfigurationMain']/div/div/div/div/div/span/select</value>
      <webElementGuid>1a06ed26-04ef-4a7c-be01-b48ec60d5eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Vendor'])[1]/following::select[1]</value>
      <webElementGuid>b68d34e0-2767-4ed6-9a7c-b40cfdd8b43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payments'])[1]/following::select[1]</value>
      <webElementGuid>3d65c8fb-61e7-49ee-aa0f-7a9d8504ebee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EYECLINIC.NET PATIENT PORTAL'])[1]/preceding::select[1]</value>
      <webElementGuid>8520cbfb-b308-40b8-ac81-c4266d82bb87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/span/select</value>
      <webElementGuid>71112470-eba1-4c93-a418-dfc7fc26cb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PortalOptions' and @name = 'PortalOptions' and (text() = 'Eyeclinic.net Portal
Maximeyes Patient Portal
' or . = 'Eyeclinic.net Portal
Maximeyes Patient Portal
')]</value>
      <webElementGuid>389a3a72-fe6d-497b-b7af-10f7273ae479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
