<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Privacy Policy</name>
   <tag></tag>
   <elementGuidId>e3b7b4dd-3f36-4bf1-8d6a-0b6598f84ce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-bs-target=&quot;\#staticBackdrop&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-bs-target = '#staticBackdrop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Privacy Policy&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b173cb8-6a26-467b-a325-e9c3858bbb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45175b23-8f50-459b-8469-d442d34c1da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>agree-text fw-normal</value>
      <webElementGuid>e3a56b71-5726-42cb-a933-c4eabcf9756d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>d41ab3cb-30fa-46ed-8a4d-e96cc90f84f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#staticBackdrop</value>
      <webElementGuid>80bd50c4-1eae-4de7-9cc2-320e2119dc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privacy Policy</value>
      <webElementGuid>78327432-235b-4832-ad35-61b98765fb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-edddc6cfe6654fead3160537a9db28f5</value>
      <webElementGuid>2e9d4973-d931-42dc-9ea7-cac777b0e78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-bs-target = '#staticBackdrop']</value>
      <webElementGuid>2b716e4c-e282-4280-9702-15f805ffb2a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-bs-target = '#staticBackdrop']</value>
      <webElementGuid>1d24a5a6-0d31-469d-a06a-e4c4bffc905b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and (text() = 'Privacy Policy' or . = 'Privacy Policy')]</value>
      <webElementGuid>d7d1d3c2-983b-4507-8dc3-fedba141bcab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
