<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PatientInfo_PatientDetail_MiddleInitial</name>
   <tag></tag>
   <elementGuidId>02294c28-e68a-40a9-b4f8-3611d3729075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PatientInfo_PatientDetail_MiddleInitial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'PatientInfo_PatientDetail_MiddleInitial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PatientInfo_PatientDetail_MiddleInitial</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>280aea3a-a430-4e14-9e06-49830f9cad4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>51dcf05e-1419-4a95-84a9-00069b80c667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>MiddleInitial</value>
      <webElementGuid>a63ce139-1033-4cfe-b09f-7a2c17cf8b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~PatientInfo.PatientDetail.MiddleInitial</value>
      <webElementGuid>eee7e5c5-c94e-432e-9a21-8fff25878c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>STRING</value>
      <webElementGuid>cb1ca1a4-2125-4428-a6ee-f19b7942380f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>PatientDetail</value>
      <webElementGuid>4f059206-6e63-4430-82d1-e8cb76fffbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>9614710a-edd0-4336-9cdc-1756f241ca43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PatientInfo_PatientDetail_MiddleInitial</value>
      <webElementGuid>cd1cb12b-53db-4065-a69f-47d2a9e9bc2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>ac4f1ddd-34fd-4eb8-943f-e24417db5e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PatientInfo.PatientDetail.MiddleInitial</value>
      <webElementGuid>2f139989-4ea3-4ee2-958c-726d54a7420a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ChangeMInitialAndSuffix(this,'MInitial')</value>
      <webElementGuid>fa2b78c0-3517-4ba0-9362-72ae4aa0fa33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>validateKeyPressXss(event);</value>
      <webElementGuid>522e30ef-09fc-4d8e-b5cd-7ac5f11504ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>validatePasteXss(this);</value>
      <webElementGuid>3765ef09-b6af-441f-bd13-3a3cbcb7d27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6be85c78-fed3-49b3-b41b-f662d360216a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>013ccecf-8dd2-46d3-90e0-90309f3a48be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b206562d-e230-40ac-bc4a-bfe33127b95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-94ce8a512995e8a5eacd13150a263dd8</value>
      <webElementGuid>91b0e7f8-fc2f-47c0-b49f-3b899112a977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'PatientInfo_PatientDetail_MiddleInitial']</value>
      <webElementGuid>a7cd4b5f-46f3-46fb-9cb9-4c4a1a4f0541</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'PatientInfo_PatientDetail_MiddleInitial']</value>
      <webElementGuid>e8bea531-9682-4b76-9251-d51b85fe8cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PatientInfo_PatientDetail_MiddleInitial' and @name = 'PatientInfo.PatientDetail.MiddleInitial' and @type = 'text']</value>
      <webElementGuid>1bf30957-10cd-453e-964e-3967a17aa9ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
