<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PatientInfo_PatientDetail_Suffix</name>
   <tag></tag>
   <elementGuidId>f9dba63a-9638-4ee1-989f-3aceccffdf19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PatientInfo_PatientDetail_Suffix</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'PatientInfo_PatientDetail_Suffix']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PatientInfo_PatientDetail_Suffix</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b189a19-395b-4e92-8291-810c52c296b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>2542e809-51c3-4723-9d9a-7c1f7a33cbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>Suffix</value>
      <webElementGuid>5727682c-f570-4ffc-9985-995b0e9e95c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~PatientInfo.PatientDetail.Suffix</value>
      <webElementGuid>bb37d677-c1d6-4067-a427-536cf0f5a003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>STRING</value>
      <webElementGuid>55d7b0a9-ca1d-4401-a63a-904786a9fe22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>PatientDetail</value>
      <webElementGuid>fd6ddf7b-488e-4ff0-8039-4893468c6755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PatientInfo_PatientDetail_Suffix</value>
      <webElementGuid>54cf315c-04f9-4bb6-b722-2509ed97ee90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>1b5c90c1-82b2-46b2-8d1e-8689a21c1c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PatientInfo.PatientDetail.Suffix</value>
      <webElementGuid>02e7f7fd-3978-41a9-84ea-bf236edafee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ChangeMInitialAndSuffix(this,'Suffix')</value>
      <webElementGuid>097245ac-cba9-426f-8fec-ce4c33316a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>ClearSuffix(event,this)</value>
      <webElementGuid>712f847f-d59b-45b9-8269-beee629949b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>validateKeyPressXss(event);</value>
      <webElementGuid>93bb9f4a-ad95-4339-8453-0bc9e78b19fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>validatePasteXss(this);</value>
      <webElementGuid>d61f5500-68e5-4f7c-b8ea-e1f76350c3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3cf9360f-5158-47b7-b5e6-a281428e39d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7ba3764a-1d2c-4165-a362-3eb4a5a6b9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4f8bb979b476b52e515289701cb4a72b</value>
      <webElementGuid>d4d97206-8292-4463-8a14-e612de8c49b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'PatientInfo_PatientDetail_Suffix']</value>
      <webElementGuid>f0a08fcc-5c47-41b8-9786-39638d255b10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'PatientInfo_PatientDetail_Suffix']</value>
      <webElementGuid>105b45c9-9703-4f2c-afd8-3be7b07b7fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PatientInfo_PatientDetail_Suffix' and @name = 'PatientInfo.PatientDetail.Suffix' and @type = 'text']</value>
      <webElementGuid>4a9928bc-1a17-4cc5-b26e-32c31ed930cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
