<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PR_Info_Address_Main_City_d3beb480</name>
   <tag></tag>
   <elementGuidId>2055a80f-a755-4fa4-aa19-12c3921bee16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-val-requiredif-dependentproperty=&quot;PatientInfo_IsCityRequired&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-val-requiredif-dependentproperty = 'PatientInfo_IsCityRequired']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PR_Info_Address_Main_City_d3beb480</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d85740a-b43b-43a6-b3dc-b5133e32cc75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PR_Info_Address_Main_City_d3beb480</value>
      <webElementGuid>df6d796e-54f8-4c2e-8043-ce93239e2a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>93a8725c-76a5-4411-81b4-a56310b3dd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>71255e41-b368-498e-bfec-19f869ea869b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nochangeevent</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>5948b5f4-7c0a-4bb3-8e2b-af0607e48a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>Zionsville</value>
      <webElementGuid>672c6887-f7ae-439f-aeb3-8a7bd188f793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>09ad54ee-9d94-4f32-9ed0-67e4a73f3b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif</name>
      <type>Main</type>
      <value>You must enter a City.</value>
      <webElementGuid>8603cc5b-0fa0-4f14-92f5-f19de783d6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-dependentproperty</name>
      <type>Main</type>
      <value>PatientInfo_IsCityRequired</value>
      <webElementGuid>d9c2d10b-a0d6-4a61-8f82-6d2e56fa8e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-targetvalue</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>8f240a91-930d-46ed-869b-6251e03f090f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PatientInfo.PatientAddress.AddressDemographic[0].City</value>
      <webElementGuid>eb7895e5-ce73-488a-b1a6-4293b220a02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>patientAddressChange(this,'d3beb480',false)</value>
      <webElementGuid>1ee0a7fd-c165-4574-89fa-6a1d00c65bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>validateKeyPressXss(event);</value>
      <webElementGuid>e3dfab7b-686f-48cb-a78b-e20cc8402ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>validatePasteXss(this);</value>
      <webElementGuid>50544a20-3709-47aa-ac8e-34aa70102092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5a99693d-9108-4db5-a70a-48b991dd99fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Zionsville</value>
      <webElementGuid>8cbb4266-deb6-4574-ba7c-144c6175fadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>03932d4d-add2-45c6-9803-56b9a6678b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>7fbde89d-7339-4901-b786-1d3703fed3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>98a5b16b-5975-4658-b003-4ab5849d223c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6e87896d-639f-4e58-a72b-139033223a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d86143b5be806419ab96b710627cfc69</value>
      <webElementGuid>325340ec-2c59-41aa-993f-015f31096f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-val-requiredif-dependentproperty = 'PatientInfo_IsCityRequired']</value>
      <webElementGuid>184b4e77-1a46-408b-93ed-3678292bde79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-val-requiredif-dependentproperty = 'PatientInfo_IsCityRequired']</value>
      <webElementGuid>d365fe7a-9024-4feb-8dad-52d74ffcc8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PR_Info_Address_Main_City_d3beb480' and @name = 'PatientInfo.PatientAddress.AddressDemographic[0].City' and @type = 'text']</value>
      <webElementGuid>9688c1a3-f5a1-41d3-9837-43b130c5372f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
