<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PR_EMAIL_d3beb4801</name>
   <tag></tag>
   <elementGuidId>be39e713-efd1-4fa6-8608-c49aded9cb04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;PatientInfo\.PatientPhoneEmail\.PhoneNumber\[1\]\.Email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'PatientInfo.PatientPhoneEmail.PhoneNumber[1].Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PR_EMAIL_d3beb4801</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8eb47b3a-fd04-4564-9efe-895bd2344d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nochangeevent</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>ad2e13b3-2dca-4dfd-aff9-b0c73a620e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>11582682-d336-41ed-a7c8-d2cef4aba2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-email</name>
      <type>Main</type>
      <value>Email is not valid</value>
      <webElementGuid>11af864d-1c25-48d0-a148-7ef15d678529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif</name>
      <type>Main</type>
      <value>You must enter an email</value>
      <webElementGuid>d7973738-2d01-4709-b7d7-1fc083c7f3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-dependentproperty</name>
      <type>Main</type>
      <value>PatientInfo_IsEmailRequired</value>
      <webElementGuid>f6b32d5b-081e-4395-8dab-c8502f7e5c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-targetvalue</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>befba275-069b-4ce4-9925-4fdc6c950305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PR_EMAIL_d3beb4801</value>
      <webElementGuid>07103fe3-62de-4fee-a4c4-fd52bc8eb061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PatientInfo.PatientPhoneEmail.PhoneNumber[1].Email</value>
      <webElementGuid>4eb71664-f039-4f35-9a1b-1ce589340dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>DuplicateValidation(this),PhoneEmailValidation(this)</value>
      <webElementGuid>9fa6051d-912c-4bdc-b842-4c9874a75b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9851eeb5-6600-48a2-86f9-b40777cd59c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>gajakumara@first-insight.com</value>
      <webElementGuid>b6347e3a-05c5-4c8e-b567-620aade529fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>482d2413-6f62-4475-9d34-1dda1a9a271d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>351c9df9-bfb1-4eed-995d-2c9054d141c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data_commtype</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>702dc963-36b6-4521-9713-20f1b8b9902b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-377e08753ca203ccbf91043516c21593</value>
      <webElementGuid>6a897ec9-835f-46bd-a0a2-7989d084500f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'PatientInfo.PatientPhoneEmail.PhoneNumber[1].Email']</value>
      <webElementGuid>2fb04bb7-3cc3-4f67-a47e-e8e044a873cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'PatientInfo.PatientPhoneEmail.PhoneNumber[1].Email']</value>
      <webElementGuid>dd63110b-bc33-482b-916a-8a1b2f45eeec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PR_EMAIL_d3beb4801' and @name = 'PatientInfo.PatientPhoneEmail.PhoneNumber[1].Email' and @type = 'text']</value>
      <webElementGuid>0aeae9dc-31a7-4863-b0f5-6b3d3c052d25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
