<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PatientInfo_PatientDetail_HeightInch</name>
   <tag></tag>
   <elementGuidId>ad9e4b0b-6fbb-45f4-8d6c-b9df4bd3bf35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PatientInfo_PatientDetail_HeightInch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'PatientInfo_PatientDetail_HeightInch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PatientInfo_PatientDetail_HeightInch</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d771ccaa-3165-4e43-9b11-0b9812133247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>05f1409b-86c4-480c-b736-e6047f1b4fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>HeightInch</value>
      <webElementGuid>3e9f658d-4ab9-493a-9345-c0927b0613b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~PatientInfo.PatientDetail.HeightInch</value>
      <webElementGuid>3a0d4183-5ff9-42cc-a7a2-c5ca3e71160c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>INT</value>
      <webElementGuid>62cb9750-cb24-4423-91be-624e71d7502b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>096c5ee9-2c87-48ab-8017-a98db9148801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field HeightInch must be a number.</value>
      <webElementGuid>5a5df5d4-0c08-4ac0-b251-298daec3b007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PatientInfo_PatientDetail_HeightInch</value>
      <webElementGuid>5070aebc-f163-45d5-93dd-ffbb3506688f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a661a927-21d5-4d83-bd4e-86538bfb011e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PatientInfo.PatientDetail.HeightInch</value>
      <webElementGuid>465bd6fd-15a3-4b63-8f8c-7352958b814b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>removeLeadingZero('I')</value>
      <webElementGuid>d31783d4-535d-4cb9-8680-d94b8b2bf609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>numbersOnly(event,'I')</value>
      <webElementGuid>b39ba243-4e41-41d7-bf73-34b93f5091a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f368e68c-06b9-44b2-8e85-de44a6491b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b5d6e8bcffff6e2b0ef553c1eb64f2ab</value>
      <webElementGuid>835788cc-5b34-4c79-b399-1d3c6688a562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'PatientInfo_PatientDetail_HeightInch']</value>
      <webElementGuid>1a892e87-fc10-4578-a53c-7f3767ecc10e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'PatientInfo_PatientDetail_HeightInch']</value>
      <webElementGuid>c8c61b10-347f-4b22-8265-4d6b270739c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PatientInfo_PatientDetail_HeightInch' and @name = 'PatientInfo.PatientDetail.HeightInch' and @type = 'text']</value>
      <webElementGuid>d07ba471-e71a-4ef1-b98e-dd0899e9b17c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
