<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PR_Info_Address_Main_Line1_d3beb480</name>
   <tag></tag>
   <elementGuidId>8516cc0a-3623-40c4-862c-aeac998cb4d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;PatientInfo\.PatientAddress\.AddressDemographic\[0\]\.Line1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'PatientInfo.PatientAddress.AddressDemographic[0].Line1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PR_Info_Address_Main_Line1_d3beb480</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f136404-8e16-4997-b34f-20425d7e1917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PR_Info_Address_Main_Line1_d3beb480</value>
      <webElementGuid>f6eed118-88c8-4755-991c-6b98502a9dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>4d8dcfc2-4c6f-404a-afa7-215638d3630b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>Line1</value>
      <webElementGuid>43d7d501-a0e5-42cd-b89f-fa64171105ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>c05076db-fc3b-46d6-baa8-8b8893b463af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nochangeevent</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>23a5afea-c8d5-4a44-88d5-405df8b2b7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>1234 Main Street</value>
      <webElementGuid>03f399f9-7968-4800-ad89-a973b19ac18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>14792574-bc7c-4958-b55a-c15b95599c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif</name>
      <type>Main</type>
      <value>You must enter a Line 1 Address.</value>
      <webElementGuid>2027fe88-c088-4044-8cee-78d1068de08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-dependentproperty</name>
      <type>Main</type>
      <value>PatientInfo_IsLine1Required</value>
      <webElementGuid>e7bcd9e4-5906-4e7f-be64-0c7f2464c29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-targetvalue</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>57925a57-bb18-48bc-b4c2-a32433c85946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>55</value>
      <webElementGuid>30af252e-8276-4fad-8fe0-70750935828d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PatientInfo.PatientAddress.AddressDemographic[0].Line1</value>
      <webElementGuid>c95ce192-2cb6-4255-9959-ae724d7ab411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>patientAddressChange(this,'d3beb480',false)</value>
      <webElementGuid>147b10dc-0785-4811-8244-12a1bfdf6993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>validateKeyPressXss(event);</value>
      <webElementGuid>fd78111c-2f96-48ff-b7ba-7556901f6263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>validatePasteXss(this);</value>
      <webElementGuid>525ff6d0-90aa-47ac-9eec-57f7f24b991f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1bad27ed-6f58-448f-b928-7450d19f4be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1234 Main Street</value>
      <webElementGuid>d89db84d-c24e-4806-a8db-694bb7247228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8ffc2479-f95f-40d7-b4ce-8d574698e205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c0af8283-c619-4283-a9dc-7eb0b3c44a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3aaf98b9e94f94d0262dea69c79e8bee</value>
      <webElementGuid>2c8e8533-d836-44de-b914-1711303c3ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'PatientInfo.PatientAddress.AddressDemographic[0].Line1']</value>
      <webElementGuid>72344e0e-e6a7-4e07-ba76-4dc7ee6b43ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'PatientInfo.PatientAddress.AddressDemographic[0].Line1']</value>
      <webElementGuid>86cfbcf4-2aa8-44ea-996c-d5bef82a6f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PR_Info_Address_Main_Line1_d3beb480' and @name = 'PatientInfo.PatientAddress.AddressDemographic[0].Line1' and @type = 'text']</value>
      <webElementGuid>b3b01fc2-2ccd-47c3-b795-3f7e529b820a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
