<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PR_Info_Address_Main_ZipCode_d3beb480</name>
   <tag></tag>
   <elementGuidId>82d08f0f-ef93-4791-8f6c-a6d1f758a090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;PatientInfo\.PatientAddress\.AddressDemographic\[0\]\.ZipCodeString&quot;][data-val-requiredif-dependentproperty=&quot;PatientInfo_IsZipCodeRequired&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@name = 'PatientInfo.PatientAddress.AddressDemographic[0].ZipCodeString') and (@data-val-requiredif-dependentproperty = 'PatientInfo_IsZipCodeRequired')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PR_Info_Address_Main_ZipCode_d3beb480</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4884e4c-60a2-44bf-95fb-326e0717c32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PR_Info_Address_Main_ZipCode_d3beb480</value>
      <webElementGuid>66bce61e-6d31-43d3-bd34-557d173149d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>ZipCode</value>
      <webElementGuid>0d711e34-0030-4858-927f-f4c6c8a27281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>896c2843-9ef8-48ec-bbc3-ced774fa08ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nochangeevent</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>7ab88591-3757-48cb-97e1-c6201c12ef1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>46077</value>
      <webElementGuid>a4c87b25-162a-4a15-a6d1-eec7ee1deae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2577879b-b728-4a95-ba61-61727ad7e4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif</name>
      <type>Main</type>
      <value>You must enter a Zip Code.</value>
      <webElementGuid>50797342-eed1-4cca-a4d1-3db1b3c71005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-dependentproperty</name>
      <type>Main</type>
      <value>PatientInfo_IsZipCodeRequired</value>
      <webElementGuid>7718d05e-99aa-43ba-a836-79e2dcecc1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-targetvalue</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>8a5c14d1-a521-4189-8cf1-0409f6fc7599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>780e25a4-2b43-4ebd-a48a-071bb6abdcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PatientInfo.PatientAddress.AddressDemographic[0].ZipCodeString</value>
      <webElementGuid>86532508-0b2a-4538-91ee-a606aaed6dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2f4cc12-6969-4975-9c74-f7841a2a2c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>46077</value>
      <webElementGuid>186fad79-04ba-47f6-953e-921f9f380de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ab8995d6-8794-4624-a6cf-b524adfe3cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>22eba99f-99aa-4290-8e61-d45e0cbf9504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>19ded7f4-5e82-41f0-9fb6-9d98865b195a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b1761b84a2af7dd652d3143e88003b44</value>
      <webElementGuid>7c9c6ce0-463e-41a7-b169-2caeef276af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@name = 'PatientInfo.PatientAddress.AddressDemographic[0].ZipCodeString') and (@data-val-requiredif-dependentproperty = 'PatientInfo_IsZipCodeRequired')]</value>
      <webElementGuid>cbe2b31f-a993-4b6b-a5a5-8ce5011cb719</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@name = 'PatientInfo.PatientAddress.AddressDemographic[0].ZipCodeString') and (@data-val-requiredif-dependentproperty = 'PatientInfo_IsZipCodeRequired')]</value>
      <webElementGuid>88d8f669-6d36-4ad2-a494-da88759019a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PR_Info_Address_Main_ZipCode_d3beb480' and @name = 'PatientInfo.PatientAddress.AddressDemographic[0].ZipCodeString' and @type = 'text']</value>
      <webElementGuid>93529aff-5f4a-42bb-9729-5df38e56fed7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
