<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PatientInfo_PatientDetail_FirstName</name>
   <tag></tag>
   <elementGuidId>19aba8d9-fa33-4584-bfc0-ef86feaadf57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PatientInfo_PatientDetail_FirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'PatientInfo_PatientDetail_FirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PatientInfo_PatientDetail_FirstName</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6867d9e-7650-4682-91ca-70aa8d8d36c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>15eb3b7e-8f76-49a9-bdcc-0a34f25fffb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>5bc595fd-89a3-4a20-bf95-ed5d5455ea63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~PatientInfo.PatientDetail.FirstName</value>
      <webElementGuid>12323c50-800f-4091-964d-2e0a17a94576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>STRING</value>
      <webElementGuid>fd05180f-e1ce-455e-be1d-451559e61b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>PatientDetail</value>
      <webElementGuid>aaf6a75a-73b3-4e85-8ef4-1ca2cc4c8a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>David</value>
      <webElementGuid>53b30645-525a-4cf0-b787-e18c3ce4a6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e02204e0-9308-4b1f-92db-1f60f51c1c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>First Name length can't be more than 100.</value>
      <webElementGuid>94717150-5dbb-4de7-8d1d-eac63c3e5c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>7cbcdffb-132c-41c6-ac46-333af17846b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>You must enter a First name.</value>
      <webElementGuid>c2dfa6a8-9f0c-499c-b2aa-f1101ea3b484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PatientInfo_PatientDetail_FirstName</value>
      <webElementGuid>2d71e1dd-f7d2-4621-81cb-1e51dfff31d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>304e239f-0c39-401f-add8-d7054651179a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PatientInfo.PatientDetail.FirstName</value>
      <webElementGuid>a7e0c985-224f-4aa7-9b29-471fea00d582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ChangeFirstAndLast(this,'FName')</value>
      <webElementGuid>58a4965d-1194-4a97-8f86-a81a357ee46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>validateKeyPressXss(event);</value>
      <webElementGuid>53f3b664-1a3d-408a-a572-890d970fccd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>validatePasteXss(this);</value>
      <webElementGuid>f40e187c-1b15-44d8-80eb-14748e086bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16420845-57fd-49a4-b752-1f1370a71ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>David</value>
      <webElementGuid>27f430cd-5f1f-46f0-babd-2c58b3dd3d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5676bc2a-d131-4e6b-b55b-772346ef4721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-27dae6b6f9c2402e6c7a31d107160be3</value>
      <webElementGuid>5347fcbe-1857-41d9-8489-89f898d95b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'PatientInfo_PatientDetail_FirstName']</value>
      <webElementGuid>1a323b1a-d8ef-4168-b8e0-8ad760e4d76c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'PatientInfo_PatientDetail_FirstName']</value>
      <webElementGuid>4eaf0d11-48fb-45b0-a3b6-6ed10559c330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PatientInfo_PatientDetail_FirstName' and @name = 'PatientInfo.PatientDetail.FirstName' and @type = 'text']</value>
      <webElementGuid>f2c943ca-e096-4d7d-bce0-018a6f22378a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
