<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_chkIsPrint</name>
   <tag></tag>
   <elementGuidId>5f37824a-f874-4f46-a764-edea90447f48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'chkIsPrint']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chkIsPrint</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#chkIsPrint</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3f33335-dbc1-458c-8641-5d3c229d0a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-checkbox</value>
      <webElementGuid>0b74e397-f957-4651-ad45-61a4f129a450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d7e7d5a3-eaf6-4ac1-852e-4e3ca44ef0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chkIsPrint</value>
      <webElementGuid>3c0d45d3-20af-442c-a62f-14b8967f615f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Recipient.IsPrint</value>
      <webElementGuid>4dcb5f89-5502-4d68-9fa1-a290c5920a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f66d24fb-205a-4777-80e7-74b817a49c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c02bfd0b-10a7-4e85-86da-8cdba2998e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-99ea41e92dbf5f212b88ff2655d0af28</value>
      <webElementGuid>27557bab-a51c-44c9-a55a-767ae89b2544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'chkIsPrint']</value>
      <webElementGuid>535aa896-6561-46f4-a9b3-cb4e2a59d474</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'chkIsPrint']</value>
      <webElementGuid>5750138d-5400-4f1b-9e61-c46fe0fa6be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'chkIsPrint' and @name = 'Recipient.IsPrint' and @type = 'checkbox']</value>
      <webElementGuid>0b6a8ada-eb66-4ecb-bd26-ba87099a66f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
