<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnProceedSaveNewPreferencePP</name>
   <tag></tag>
   <elementGuidId>a5cbcf88-02e3-408d-910c-29cca33384c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnProceedSaveNewPreferencePP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnProceedSaveNewPreferencePP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;PROCEED&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9633d738-a3e5-488f-abbd-ac33173f13c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>31200bbc-f675-4721-98c2-1c7118b382d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>PROCEED</value>
      <webElementGuid>40a9ae70-08d2-4a4f-9aa2-fd9ca067cd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnProceedSaveNewPreferencePP</value>
      <webElementGuid>5e4e3b00-7b77-4caa-92eb-2be74e6f8e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button med-small-button30 primary</value>
      <webElementGuid>00f224ba-2264-46ce-8231-3a9290cc49e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-567722e405bf5c8ee8fc40e0cae699e1</value>
      <webElementGuid>fc8cbd14-4d5a-4256-8922-60508ea9dc08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnProceedSaveNewPreferencePP']</value>
      <webElementGuid>497b39bb-2b54-475c-8845-e886724be50e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnProceedSaveNewPreferencePP']</value>
      <webElementGuid>59ba0240-0ffb-477e-a58d-df154960208c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnProceedSaveNewPreferencePP']</value>
      <webElementGuid>b87d713f-89a8-4c83-86b9-5ba92b88a7a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
