<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>b5b0c059-d052-4570-8aff-8151ff6342d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class and contains(concat(' ', normalize-space(@class), ' '), ' sm:block ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn ') and (position() = 1)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sm\:block .btn:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>25893e80-679d-4e7b-8c03-0c372dad7136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary position-relative align-items-center btn-md rounded flex-1</value>
      <webElementGuid>fcc0a0a8-860e-4d93-972e-ae7f276b2de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df445396-e65f-4d34-88e0-a1ce038d516e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>8d65f83a-ad7f-4e3e-9387-9e56b4ef4855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-551fc9ff875f8f66562556f33bebdf00</value>
      <webElementGuid>f339a111-185a-4e13-9688-c2b94b8e5c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class and contains(concat(' ', normalize-space(@class), ' '), ' sm:block ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn ') and (position() = 1)]</value>
      <webElementGuid>c5f60caa-26c0-4e0b-8ed7-2160d3b9645c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@class and contains(concat(' ', normalize-space(@class), ' '), ' sm:block ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn ') and (position() = 1)]</value>
      <webElementGuid>4c86c096-cbc3-4b1c-8235-54730bff74f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>d8547334-74bd-44fa-959d-fda2e3eaf579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
