<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ui-id-26</name>
   <tag></tag>
   <elementGuidId>6e7bac41-edcc-4e9a-b7fe-a575bd44a620</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '#divPermissionWithLocation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\#divPermissionWithLocation&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Permissions that can be restricted by location&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb928d95-094d-4b53-b29d-0fe9d6911855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#divPermissionWithLocation</value>
      <webElementGuid>ab899ab7-74e7-495d-8490-a9c9283f22e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-tabs-anchor</value>
      <webElementGuid>92476569-17e6-4b94-86dd-2e15541fb22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>080aaf10-4581-4197-afc5-17a960ad5898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a6d2c752-acb9-4175-b0dc-699a0583e65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-26</value>
      <webElementGuid>e42738b6-e3b1-4357-8381-f9bd8f526ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Permissions that can be restricted by location</value>
      <webElementGuid>444455ba-682d-435f-9b65-56be7e213128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3c2281c8d360c2825494f774bb5bcd13</value>
      <webElementGuid>4888ab64-65a2-4e02-be96-01c5af983db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '#divPermissionWithLocation']</value>
      <webElementGuid>5d3d4303-b1a8-4ee3-bb5b-1a9dbe8b705a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '#divPermissionWithLocation']</value>
      <webElementGuid>352b110c-cdc3-49ab-9744-3ccc522b841e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#divPermissionWithLocation' and @id = 'ui-id-26' and (text() = 'Permissions that can be restricted by location' or . = 'Permissions that can be restricted by location')]</value>
      <webElementGuid>c29e73f7-e76e-4bcc-9ead-e5f78ca0e05b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
