<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ui-id-28</name>
   <tag></tag>
   <elementGuidId>123b0cfc-2c2e-4396-802e-5442ee9aa8fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@title = 'This permission will control which users have access to view patient records.']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[title=&quot;This\ permission\ will\ control\ which\ users\ have\ access\ to\ view\ patient\ records\.&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Permissions&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe2c3c11-eb0f-4c5c-9a28-8887687edfe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Permissions</value>
      <webElementGuid>cf0dcbc3-dbba-49d5-8c33-a07be32c9bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>This permission will control which users have access to view patient records.</value>
      <webElementGuid>314c0ff9-f3b4-408f-b1bf-1a2ee9dd491c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-tabs-anchor</value>
      <webElementGuid>f7a1dc23-7209-4e25-8e78-0ed61fc8e288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>c002bdc0-fca8-4ed9-bcc3-7d986f74a94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7e470082-57bf-4ff1-b79c-9faecf293e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-28</value>
      <webElementGuid>3cb189b9-896d-4dc5-bf47-8d20f9e1e6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Permissions</value>
      <webElementGuid>ffce6d44-95a0-4c7b-8a78-8324e273fefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1fd2ac3334934f43ae5fd59905d81550</value>
      <webElementGuid>cb507f7d-ccfd-4900-ba03-23ce207868d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@title = 'This permission will control which users have access to view patient records.']</value>
      <webElementGuid>d9e11fd0-c68f-4df3-9a52-d1f140890368</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@title = 'This permission will control which users have access to view patient records.']</value>
      <webElementGuid>cf4f40a7-dff4-4acd-b37e-f53d9f80db12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#Permissions' and @title = 'This permission will control which users have access to view patient records.' and @id = 'ui-id-28' and (text() = 'Permissions' or . = 'Permissions')]</value>
      <webElementGuid>2d4ba797-a9cb-4b37-a03e-c2b818322a5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
