<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pending</name>
   <tag></tag>
   <elementGuidId>523dfb99-510c-4d2e-a7ab-e06b61e72bbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'p') and (position() = 4)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-medium ') and (position() = 2)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-child(4) .font-medium:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Pending&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>10eacd60-bdf8-4dd2-aa2a-99037abd13bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-red-500 font-medium ml-1</value>
      <webElementGuid>250070db-8633-422a-9644-dc500a13c61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pending</value>
      <webElementGuid>517138c5-c6e0-4f42-9755-c43a52aa02bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7fb5f3eeaf00ecdb33a3d6593f187dca</value>
      <webElementGuid>e5ca6227-6865-49a3-870e-9a53d3d98b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'p') and (position() = 4)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-medium ') and (position() = 2)]</value>
      <webElementGuid>dff83193-c9f7-480b-a932-e9ab727f09d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'p') and (position() = 4)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-medium ') and (position() = 2)]</value>
      <webElementGuid>d3c0f77e-e8cd-4af2-9fd6-95da34481afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pending' or . = 'Pending')]</value>
      <webElementGuid>c4bd21c2-e564-46df-a7c5-fa529597baeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
