<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PhoneEmailEntry_985cd63e</name>
   <tag></tag>
   <elementGuidId>0510ae83-2ed2-475d-aa10-3e2062b8e5d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'PhoneEmailModel[0].PhoneEmailEntry']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;PhoneEmailModel\[0\]\.PhoneEmailEntry&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;PhoneEmailModel\[0\]\.PhoneEmailEntry&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8db316b7-3313-48d6-9d5e-f1fb8f6769cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>4fa91d3d-feca-4758-b762-54e804126257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PhoneEmailEntry_985cd63e</value>
      <webElementGuid>14b03f41-2ff0-4333-bcb5-737cee629ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhoneEmailModel[0].PhoneEmailEntry</value>
      <webElementGuid>d83a7878-9012-48e8-90ca-23aa216369f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b86cf02e-af15-4733-8e59-6ca67a499df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>gajakumara@first-insight.com</value>
      <webElementGuid>c1a14a60-a832-49c1-a935-44acd088bbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>25e99cf5-9b61-429e-b988-641ca108bd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>336459ad-f831-4499-848e-86cf6c9064d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-55c35ecfb95ed8c37322db9c3658859f</value>
      <webElementGuid>79eef6f2-bfab-49ce-bb61-ef5bd71fe3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'PhoneEmailModel[0].PhoneEmailEntry']</value>
      <webElementGuid>1ec60218-818d-4508-b443-61d0073a1fae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'PhoneEmailModel[0].PhoneEmailEntry']</value>
      <webElementGuid>1f894a80-1b82-4c1a-ade9-cc356d83a825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PhoneEmailEntry_985cd63e' and @name = 'PhoneEmailModel[0].PhoneEmailEntry' and @type = 'text']</value>
      <webElementGuid>fe82de2d-b553-4566-b45d-0bf320db2ba3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
