<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btnmainForward</name>
   <tag></tag>
   <elementGuidId>1f4bff33-d070-4cdb-ac86-0d86209edb15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnmainForward</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnmainForward']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Forward&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7070a7e4-1c98-4006-b56e-499cd84252b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button small-button50 primary</value>
      <webElementGuid>8a247621-58c9-43e6-a649-c0d968f2fd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnmainForward</value>
      <webElementGuid>d5faa516-0a84-4e72-ab47-cad4151fa1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forward</value>
      <webElementGuid>bce149cb-d576-4d5d-ba94-2de6bca20c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fd8582c5c5168e2deba7bb538bd0ed37</value>
      <webElementGuid>7f16a188-a71c-419f-823f-3aed5156cd54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnmainForward']</value>
      <webElementGuid>9b77350d-7344-4521-9c03-4fe3248b1399</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnmainForward']</value>
      <webElementGuid>e50e43d1-a917-40c9-a5c7-bc5ca452a252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnmainForward' and (text() = 'Forward' or . = 'Forward')]</value>
      <webElementGuid>c04708cb-f5c7-4c22-ad4a-31d1d79e23b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
