<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Patient or Referring Physician</name>
   <tag></tag>
   <elementGuidId>482c1660-0c7f-46d4-8a64-ea0627acfe49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ForwardInboxInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ForwardInboxInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Search Patient or Referring Physician&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3fd4ad19-6590-4ff2-a0c7-cf27b7838454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5eaaa1b0-d478-4835-b7eb-c68ff32e3845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input InboxInput font20</value>
      <webElementGuid>32217a8b-8ab9-48e2-b91d-3256466a8a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>55</value>
      <webElementGuid>2ae7c2f6-4814-4eed-9a08-3d3c9727e271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Patient or Referring Physician</value>
      <webElementGuid>0dff8af9-d914-4bb8-a687-c988e5f73180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5f3810ee-c163-4041-abcd-72b803fa3e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ForwardInboxInput</value>
      <webElementGuid>800c8dfd-531e-43ee-a446-57c5459cdc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-59233095915ea07647a57dd64e79f7f3</value>
      <webElementGuid>53c20530-3734-49c1-8c7b-9219ae2d0614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ForwardInboxInput']</value>
      <webElementGuid>4b89b0b4-2b19-410d-96df-29c2d69817a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ForwardInboxInput']</value>
      <webElementGuid>76539e93-0abe-4dff-ad78-e055efb20993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search Patient or Referring Physician' and @id = 'ForwardInboxInput']</value>
      <webElementGuid>6611dd04-1f11-4b14-b8cc-1181f607b3dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
