<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ui-id-9</name>
   <tag></tag>
   <elementGuidId>f6c95654-c910-4c8a-8fe3-c72e2983ced0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '#auth_SecureMessagesMail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\#auth_SecureMessagesMail&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Secure Messages&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>09af8d4e-a458-4368-b85b-c038afc44106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#auth_SecureMessagesMail</value>
      <webElementGuid>1e14a3f4-2ce4-4244-b445-77ae16359e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectorForGoogleAnalytics ui-tabs-anchor</value>
      <webElementGuid>2a883005-b6c5-419f-86de-d9cee1852ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>004aabdc-6af4-4034-a22f-f36852f25b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>98385bf1-eee1-45b5-861b-e6f98bb36f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-9</value>
      <webElementGuid>f2314bfc-d255-4f1e-bead-0241078cd2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-tab-content-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36ab4445-a464-4505-806e-a017469fc3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Secure Messages</value>
      <webElementGuid>4fbff4a9-28a8-4ed5-a43e-c4caccd27549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-908dab4534544b2a84400403ea2716ad</value>
      <webElementGuid>44db985b-d6ce-4130-96c2-1db392254cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '#auth_SecureMessagesMail']</value>
      <webElementGuid>d8485c74-1946-40b9-96f0-782753a2aae4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '#auth_SecureMessagesMail']</value>
      <webElementGuid>ccc53b5b-178a-4790-8088-ca8fe2aa749b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#auth_SecureMessagesMail' and @id = 'ui-id-9' and (text() = 'Secure Messages' or . = 'Secure Messages')]</value>
      <webElementGuid>74fc3a41-360c-42cf-8a50-56d8105140a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
