<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PhoneEmailEntry_1579ea8f</name>
   <tag></tag>
   <elementGuidId>cd95682f-e077-4757-ac25-b151391826ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'PhoneEmailModel[0].PhoneEmailEntry']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;PhoneEmailModel\[0\]\.PhoneEmailEntry&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;PhoneEmailModel\[0\]\.PhoneEmailEntry&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69932410-5c34-486e-ac03-7ae402675d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PhoneEmailEntry_1579ea8f</value>
      <webElementGuid>d0e15bef-ccc0-45af-98a3-cdd52f5ffbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhoneEmailModel[0].PhoneEmailEntry</value>
      <webElementGuid>b5a2c704-5a59-44a9-bc83-13d6a5ab583d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>496105e1-522d-4551-9614-e42f586b0b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>399503cc-30f7-42b9-91e2-29512fc71001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>e4975e6d-807b-462e-a4bc-ecda64c3b9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a67eaca0-c6f4-4494-9f65-84b243a98b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-55c35ecfb95ed8c37322db9c3658859f</value>
      <webElementGuid>7099deb7-6fac-4ac8-af27-221079d47464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'PhoneEmailModel[0].PhoneEmailEntry']</value>
      <webElementGuid>49b34083-95da-438e-80ca-c22eefc51100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'PhoneEmailModel[0].PhoneEmailEntry']</value>
      <webElementGuid>de07b8a8-b037-49b6-89ff-f2561f00c0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PhoneEmailEntry_1579ea8f' and @name = 'PhoneEmailModel[0].PhoneEmailEntry' and @type = 'text']</value>
      <webElementGuid>375f827c-baa1-4a15-93e7-ff7d7d3bbcbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
