<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Clinic_1</name>
   <tag></tag>
   <elementGuidId>aa347529-ac59-4be0-93be-2cae738599a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-sort=&quot;ascending&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;PatientExtPhysiciangrid&quot;]/div/div[5]/div/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=columnheader[name=&quot;Clinic &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2067f715-2f62-4de1-94c4-8fcb9a51c425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer dx-datagrid-action dx-cell-focus-disabled</value>
      <webElementGuid>2e9cd2d4-9ae8-46f5-aca4-8298affc8ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2c12b5ee-e6cf-4c23-beea-48ca637ba8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>columnheader</value>
      <webElementGuid>19efd10b-c7ce-4579-b2b0-855704fdb87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b5b4153a-dbe6-48ce-a2e6-5980be836db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-sort</name>
      <type>Main</type>
      <value>ascending</value>
      <webElementGuid>9116e753-9c16-4307-a005-5d8ad86b435b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clinic</value>
      <webElementGuid>fe7b5dd5-047f-4097-8321-7a43fcd247d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a3fcbda75181a47a5fe035c02f4b87bb</value>
      <webElementGuid>6f2b6e39-d606-407b-8ebc-408aa0ee09b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-sort = 'ascending']</value>
      <webElementGuid>780c838a-3eb9-4586-93b7-60ae1c52d432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id=&quot;PatientExtPhysiciangrid&quot;]/div/div[5]/div/table/tbody/tr/td[3]</value>
      <webElementGuid>9ea4f4fb-1aa9-4027-8c63-12a7ca487f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Clinic' or . = 'Clinic')]</value>
      <webElementGuid>3b8dffa6-7990-4844-a165-07f5d5567392</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
