<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_gajakumarafirst-insight.com_1</name>
   <tag></tag>
   <elementGuidId>4f98578a-a772-48f1-a5e4-d48e16340176</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@title = 'gajakumara@first-insight.com']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[title=&quot;gajakumara\@first-insight\.com&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;gajakumara@first-insight.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1b631406-aa9d-4b00-ab21-567bdc1fcb47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer dx-cell-focus-disabled</value>
      <webElementGuid>e7ca5268-d3c5-4158-9b3e-dfa07e5a001c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1fb1fa3b-aea5-404a-84cc-bf1062e83431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>0d43762a-5562-43b3-9b6d-942a6f246639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>ee1ec9f5-4b55-428a-928b-a6ebedade7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1cf1d811-4dca-452e-94a2-105ea9e1c847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>gajakumara@first-insight.com</value>
      <webElementGuid>29388e38-895d-4fc3-bccb-dac0a16e2b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>gajakumara@first-insight.com</value>
      <webElementGuid>78b17628-1125-4c56-ae7e-448182f93e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bd3406a315930829f1302dcc99b8209e</value>
      <webElementGuid>db1b05e0-0ad9-46b0-ad8b-c06fd3b373d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@title = 'gajakumara@first-insight.com']</value>
      <webElementGuid>80d3cd49-030d-427d-a2b7-5c6bf38bba68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@title = 'gajakumara@first-insight.com']</value>
      <webElementGuid>33f2ab5e-8383-432a-9985-1ba8e0b114e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'gajakumara@first-insight.com' and (text() = 'gajakumara@first-insight.com' or . = 'gajakumara@first-insight.com')]</value>
      <webElementGuid>ea28ea80-ce7a-48c8-8e2f-6c641f47acd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
