<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Katalon</name>
   <tag></tag>
   <elementGuidId>e6af0de4-1e28-4e3e-a372-d7dfdb56d955</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@role = 'gridcell') and (position() = 2)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;gridcell&quot;]:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;Katalon&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0c427709-3a70-4598-81ec-a7aa8467dc55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer</value>
      <webElementGuid>a27dfda2-c832-433c-ab0b-aa10283d7777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>43556624-6d9e-4888-9510-6929bf2a10c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>bde680f9-7c94-4f11-b5b9-bad60424fb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7d6d010c-955e-4122-b0af-a44e68f7c431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon</value>
      <webElementGuid>5eeb0cd5-ccab-4a44-9bd0-94e03ccb3671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c78b7f5ff056d13447a0b0fde27f86c6</value>
      <webElementGuid>c1009f5a-e56f-4c3c-8a00-ee61444dc50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@role = 'gridcell') and (position() = 2)]</value>
      <webElementGuid>f7cd574a-64b6-4d29-8f3a-fe7f46acfc76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@role = 'gridcell') and (position() = 2)]</value>
      <webElementGuid>94997a05-74dd-411e-b85d-6c1cefb3e41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Katalon' or . = 'Katalon')]</value>
      <webElementGuid>14a9ad0b-4097-4a46-a96a-d7cefb88a4ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
