<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Test Diag</name>
   <tag></tag>
   <elementGuidId>75b29878-06d3-44ac-9d9a-99bd9d91e757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Procedures > table > tbody > tr > td:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Procedures']/table/tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Test Diag&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6a3930c7-059f-4cf5-9db5-a9174711760d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>f0668803-862b-45cb-9bc0-26ed2a28a946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Diag</value>
      <webElementGuid>ea5b3f79-001f-4a62-bda4-9471c8b9e060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;Procedures&quot;]/table[1]/tbody[1]/tr[1]/td[4]</value>
      <webElementGuid>db87ef3a-1242-46f0-8101-be36b5948c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SOC Verification On PP/Page_Patient Portal/iframe_Visit Date 01162026_w-full h-full border-0</value>
      <webElementGuid>9391353a-83ec-40ca-9385-e3d560e3e6ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Procedures']/table/tbody/tr/td[4]</value>
      <webElementGuid>2829fb6c-45fc-4733-82d6-4c7514000ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[1]/following::td[1]</value>
      <webElementGuid>ab56e362-4173-4f86-af67-e749d619f72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automated VF'])[1]/following::td[2]</value>
      <webElementGuid>b13be35b-55a1-45d6-8d47-89a8c557200f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plan of Treatment'])[2]/preceding::td[1]</value>
      <webElementGuid>a182aa80-77fd-465e-a436-0b611ecb1eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Information Available.'])[6]/preceding::td[1]</value>
      <webElementGuid>6e12fb78-6d1c-4364-a584-fafe5e507d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test Diag']/parent::*</value>
      <webElementGuid>7f40eb6f-d302-4113-a105-3deef5db6865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/table/tbody/tr/td[4]</value>
      <webElementGuid>20f92f02-6dcf-47e7-8770-a7f6d11668e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Test Diag' or . = 'Test Diag')]</value>
      <webElementGuid>1a8a63b8-bdd7-4fd3-b686-b71c039e9ca5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
