<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_opacity-100</name>
   <tag></tag>
   <elementGuidId>5de1d463-3813-4d70-be0c-a367442b3783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.justify-content-center [focusable=&quot;false&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@class and contains(concat(' ', normalize-space(@class), ' '), ' justify-content-center ')]//*[@focusable = 'false']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>473d520a-6854-4d79-ac4a-6b613a5f8d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>b9dfd677-183f-4c3b-a78d-72d1050a4755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>a3c2910d-bf2e-4375-8f8f-b0e5de8bb014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>89568cd4-209b-4723-b5eb-da0b7d025cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 22 16</value>
      <webElementGuid>6c12bb67-28e4-47f2-9493-a1b7052bc8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>d7aa3b79-b557-4c38-a6e1-da924eaaa09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>opacity-100</value>
      <webElementGuid>7a566f3a-16be-44f3-b184-3e0f9d869200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fb5ffa12-f17c-4106-bf60-9b84165b0d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>811f86ce-8cff-4e0d-aa88-d0d8ad1f2d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ef11f608438ae1c10b6111ab6fe22402</value>
      <webElementGuid>d7ea56e8-4148-40b5-a06e-1d3921510cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@class and contains(concat(' ', normalize-space(@class), ' '), ' justify-content-center ')]//*[@focusable = 'false']</value>
      <webElementGuid>00e4e5df-53f7-4169-889e-43aaba2f4283</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@class and contains(concat(' ', normalize-space(@class), ' '), ' justify-content-center ')]//*[@focusable = 'false']</value>
      <webElementGuid>7403b733-2dde-4e93-8515-80485d92b11c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
