<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Chief Complaint  HPI_encTabList_2</name>
   <tag></tag>
   <elementGuidId>0b2d824d-5c97-4f6a-b2e9-98001f5577d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#encTabList_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='encTabList_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Final Findings&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ccbf839d-e05f-421e-b185-2637393b80a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>Element</value>
      <webElementGuid>84baef11-19c2-48dc-b18e-adcd6e96c507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Final Findings</value>
      <webElementGuid>e71010af-bef1-409c-a1fd-43e16d70ac69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Final Findings</value>
      <webElementGuid>579f79dd-a53b-40a6-acfa-eee9e78ca247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncateWord ui-tabs-anchor</value>
      <webElementGuid>482aa518-a02e-4386-a325-1db325cc80bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#encounterform13140</value>
      <webElementGuid>79ec3059-39bf-43ad-832e-f17a8a5e916f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>encTabList_2</value>
      <webElementGuid>b8158ea5-181d-45f0-bd79-540f3f99ebf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>238e5b25-b858-42e2-b006-0a1403c88417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>34ae89c5-b844-4727-8cce-5ed744099e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Final Findings
</value>
      <webElementGuid>dbb6484b-d246-40bc-b275-1abe18d06a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;encTabList_2&quot;)</value>
      <webElementGuid>b391abb1-efae-4458-8fa2-02d1e2547344</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='encTabList_2']</value>
      <webElementGuid>2c899cdb-14bc-41bf-83c4-e88c33b6b3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainpageul']/li[4]/a</value>
      <webElementGuid>f9178874-46ef-4dc7-8ca0-a3fb7022258b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Final Findings')]</value>
      <webElementGuid>5caebed6-8c26-4996-b20b-dd0e3566682f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chief Complaint &amp; HPI'])[1]/following::a[8]</value>
      <webElementGuid>26680551-687b-4b55-b8bf-a09e846996aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intake Form'])[1]/following::a[9]</value>
      <webElementGuid>c9860a31-291e-44e9-a0c1-cf2cfbd6408d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tests &amp; Miscellaneous'])[1]/preceding::a[6]</value>
      <webElementGuid>1ae1e741-e6c8-46bb-96c7-330f803de42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Electronic Files'])[2]/preceding::a[7]</value>
      <webElementGuid>294cba2a-b1d2-4ce7-9dc1-14a50901bafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Final Findings']/parent::*</value>
      <webElementGuid>1d5f9e8a-926e-47d7-b418-f497cd392285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#encounterform13140')]</value>
      <webElementGuid>485821c0-c366-4ea8-84af-8f6d967a8693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/ul/li[4]/a</value>
      <webElementGuid>0bcc991f-c45b-45f1-ba9d-b9d30a6a2b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'Final Findings' and @title = 'Final Findings' and @href = '#encounterform13140' and @id = 'encTabList_2' and (text() = '
Final Findings
' or . = '
Final Findings
')]</value>
      <webElementGuid>cb0e4868-cf24-4d9f-9b21-0f9977a78b40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
