<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirmation_btnCreateANewEncounter</name>
   <tag></tag>
   <elementGuidId>7a7ee950-4a40-459c-9b34-ee3881498377</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnCreateANewEncounter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnCreateNewEncounter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;CREATE NEW&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acf14c9d-dcbc-496e-a8d7-684c98b390f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b5780e68-f314-4550-ae14-f76a5de5c4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirmbar-btn-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>66fd98f7-2cea-4699-8f4b-6c429eb54ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CREATE NEW</value>
      <webElementGuid>df05a3e6-194b-49ce-953e-a9da7756ddd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semi-bold font20 hide-confirmation ignore-action-toggle margin-right-10px margin-top-10px  notifationButton</value>
      <webElementGuid>a5823e66-1bc4-4cc6-b4a4-3bb59cc9b712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>42030590-ad75-4fa5-95ec-848675964232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCreateANewEncounter</value>
      <webElementGuid>77d5c27e-88c1-48ec-a3da-b3277acab326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCreateANewEncounter&quot;)</value>
      <webElementGuid>e5c5f3ac-d776-4d59-8900-192fe185d367</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnCreateANewEncounter']</value>
      <webElementGuid>85801fd4-bf01-4f61-bd31-e82ac562ace0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newConfirmationBarWithCustomButton']/div/div/div/div/div[2]/div/div[2]/div/input[2]</value>
      <webElementGuid>d2d90c78-d680-49ae-b7b7-314a68068f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div[2]/div/div[2]/div/input[2]</value>
      <webElementGuid>6ae40941-d7ab-46c1-9107-02874cbfa09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnCreateANewEncounter']</value>
      <webElementGuid>4740dc3a-18a0-49cd-b533-097244c909ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
