<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Loading_STATUS_GF_df4a_GF_DDD_L_LBI0T0</name>
   <tag></tag>
   <elementGuidId>2cbb3e7b-d66f-47bf-8103-afe82ef97533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#STATUS_GF_df4a_GF_DDD_L_LBI0T0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='STATUS_GF_df4a_GF_DDD_L_LBI0T0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#STATUS_GF_df4a_GF_DDD_L_LBI0T0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f7d9ceeb-8314-464c-982f-7762d6dbbc08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>STATUS_GF_df4a_GF_DDD_L_LBI0T0</value>
      <webElementGuid>09d20d93-3b8d-48a9-8b0c-cf3a1ace6302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_Metropolis dxeListBoxItemHover_Metropolis dxeListBoxItemSelected_Metropolis</value>
      <webElementGuid>db4b3839-8c70-408f-abf1-822240ca1947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>64dad362-342a-472a-9455-bf78ac40056f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;STATUS_GF_df4a_GF_DDD_L_LBI0T0&quot;)</value>
      <webElementGuid>478acd65-04dc-4f7b-a55f-33babdf8e606</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='STATUS_GF_df4a_GF_DDD_L_LBI0T0']</value>
      <webElementGuid>9ec88e1e-aaf8-4420-85f0-34eca177de6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='STATUS_GF_df4a_GF_DDD_L_LBT']/tr/td</value>
      <webElementGuid>17b4bc49-9377-4e70-8de3-fa251f175124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading…'])[2]/following::td[14]</value>
      <webElementGuid>23dac3a2-bd47-49d4-8ea3-83e4c0f25ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hyperlipidemia'])[1]/following::td[17]</value>
      <webElementGuid>b929ebb3-8e1b-4cac-99a9-abfc1db01428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[2]/preceding::td[1]</value>
      <webElementGuid>7539a7a3-64bf-42e1-a4eb-58400138de8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolved'])[3]/preceding::td[2]</value>
      <webElementGuid>ad0e0e2f-460f-4487-a165-0fae96e98b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div[2]/div/div/div/div/table/tbody/tr/td/div/div/table[2]/tr/td</value>
      <webElementGuid>aa5b6582-18d5-44c1-b135-de46882c5c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'STATUS_GF_df4a_GF_DDD_L_LBI0T0' and (text() = 'Active' or . = 'Active')]</value>
      <webElementGuid>9236f295-9e06-4a53-86d5-070d85ac078a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
