<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ProvGroup_provFilterBoxPIM</name>
   <tag></tag>
   <elementGuidId>7e83efb7-3551-45d1-9e97-058fff0f1ca1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='provFilterBoxPIM']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#provFilterBoxPIM</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#provFilterBoxPIM</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a19753ee-65f0-433a-b5d9-9d9c40882b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd67cd6b-eeb6-4c5f-9144-3a53a4250761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>provFilterBoxPIM</value>
      <webElementGuid>9e478202-572b-47cc-b043-ae84149b1f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-provscontainerid</name>
      <type>Main</type>
      <value>idDvProvGroup</value>
      <webElementGuid>334dfcf9-3d94-4910-9d96-1fb3735d3f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;provFilterBoxPIM&quot;)</value>
      <webElementGuid>f32d95ab-64b0-40d1-bbc0-5d1027464625</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='provFilterBoxPIM']</value>
      <webElementGuid>85e49c98-9704-4e71-bd31-b4d25435e072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ProInterGrid']/div[2]/div/div/input</value>
      <webElementGuid>caac00b7-2430-46f2-8aba-432cacb1244b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>47d1b43e-3e43-4ab6-9300-1f292bb0dc8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'provFilterBoxPIM']</value>
      <webElementGuid>7c26491f-c2e4-496e-8420-fbf2a7304cdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
