<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TOC Req_mif-Hamburger fg-gray font30</name>
   <tag></tag>
   <elementGuidId>4116a4ff-5abc-4609-bdb7-6a6486e4ed55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='showMoreMenu(this)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mif-Hamburger.fg-gray.font30</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9c413efe-59ce-4780-ad4e-717c9c053666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mif-Hamburger fg-gray font30</value>
      <webElementGuid>a12d23bf-5332-4e31-8c6d-68ef36b72987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showMoreMenu(this)</value>
      <webElementGuid>839c0c98-97c4-4ae6-9f9f-e36441f822d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>More</value>
      <webElementGuid>7240e43d-ec34-4cc3-b239-270a01b24a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patientEncounterHeader&quot;)/div[@class=&quot;col-xs-12 col-sm-12 col-md-12 col-lg-5 no-padding marT10&quot;]/ul[@class=&quot;ribbon-encounter-left-icons&quot;]/li[1]/a[@class=&quot;line-height34&quot;]/span[@class=&quot;mif-Hamburger fg-gray font30&quot;]</value>
      <webElementGuid>444e047c-2c2c-433a-9080-6d05b9b91586</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='showMoreMenu(this)']</value>
      <webElementGuid>e52e42d4-9de3-48ae-8271-c3e041473f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='patientEncounterHeader']/div[2]/ul/li/a/span</value>
      <webElementGuid>7af0eb8c-33fb-41ea-b89b-d3cd300268c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a/span</value>
      <webElementGuid>b24cf1be-6765-42dc-aea8-706848ef3ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'More']</value>
      <webElementGuid>36c87d9d-1fec-4dc0-85c4-88bf8d762d68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
