<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnSavePatientEmailIdPP</name>
   <tag></tag>
   <elementGuidId>a9cbd081-7f3c-43f4-97ec-78b288b6f9c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnSavePatientEmailIdPP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnSavePatientEmailIdPP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67361760-79e2-4b9c-88ac-773f2cbe663d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f20eb60f-3a0f-4247-9a75-bf17ed55f9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary small-button padButtonLR</value>
      <webElementGuid>3bda63fe-bcba-40e3-9958-b34dcf45f3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSavePatientEmailIdPP</value>
      <webElementGuid>1d95949b-7108-40f1-81ea-d89c4c1dd9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>52ce69e1-f2ad-4107-961b-241abb725aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0710556071286470b8ed37f932d715a8</value>
      <webElementGuid>0977994d-0bb4-463d-8e71-9d5960e00876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnSavePatientEmailIdPP']</value>
      <webElementGuid>ab58ccaf-fa7f-48dd-9c3c-471e67b8c08b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnSavePatientEmailIdPP']</value>
      <webElementGuid>77cb5da1-3402-4b08-a31e-eafa4f181ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnSavePatientEmailIdPP']</value>
      <webElementGuid>04b6e481-dec3-4e99-aea4-82d211771282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
