<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnDeleteMsgs</name>
   <tag></tag>
   <elementGuidId>9409374e-f8ca-4902-a50e-79640aeba988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnDeleteMsgs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnDeleteMsgs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;YES&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04d6b54f-53b8-4bf9-9346-7efed128aca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>505de07d-b4f7-4b0e-b7b6-e32cf2ec9eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirmbar-btn-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>81840cb8-6433-4560-8110-cebcb9047bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>YES</value>
      <webElementGuid>69f5f71c-c947-42a3-9222-95c96e07f2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semi-bold font20 hide-confirmation ignore-action-toggle  margin-right-10px margin-top-10px notifationButton</value>
      <webElementGuid>4c66ff56-7d79-4a15-83a6-21bfaf81aafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>c533d4dc-0a40-4e63-a111-04445a72b6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDeleteMsgs</value>
      <webElementGuid>00096f66-11db-45f7-b4d0-b632fd9f392a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e6e203e3d3adbc0e8b54047518599e56</value>
      <webElementGuid>a2b7679c-bd7f-4f6f-8b10-cc1edca93e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnDeleteMsgs']</value>
      <webElementGuid>f5906b0e-409e-4977-8d3d-f300c4b9997b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnDeleteMsgs']</value>
      <webElementGuid>5c2b7524-9116-419d-887f-f6993c3f9b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnDeleteMsgs']</value>
      <webElementGuid>9c090e3f-7ade-4a72-92f2-d437de795fe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
