<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_custom-checkbox</name>
   <tag></tag>
   <elementGuidId>08103ccb-7c8e-4546-ab05-ebb02129fec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;idquicklinkGridForOutbox&quot;]/tr[1]/td[1]/span/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.odd[data-isdirect=&quot;False&quot;][data-message-type=&quot;outbox&quot;]:nth-child(1) .custom-checkbox[data-toggle=&quot;checkbox&quot;][type=&quot;checkbox&quot;][value=&quot;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;  To: Provider Portal Attachments  05/18/2026&quot;i] >> internal:label=&quot;&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85fd21f1-697d-4fdd-ba67-5d84fa9a00bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fafb4914-a3b8-45f2-ba85-2c59972762f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c503beb9-8446-4936-8750-0e605b023c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-checkbox</value>
      <webElementGuid>12131dd6-c5eb-4fb2-8811-a2a1c15b0e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-dc12560f92b7834826305abb3e7fcc99</value>
      <webElementGuid>39e1ca78-487c-41ce-a33a-9a9d1e5806e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (@data-isdirect = 'False') and (@data-message-type = 'outbox') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' custom-checkbox ') and (@data-toggle = 'checkbox') and (@type = 'checkbox') and (@value = '')]</value>
      <webElementGuid>557a32c1-9174-4a46-b4cd-05dd5c40e688</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id=&quot;idquicklinkGridForOutbox&quot;]/tr[3]/td[1]/span/label/input</value>
      <webElementGuid>1cb9134b-889d-4ff1-9d1a-c08082ee8739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//*[@id=&quot;idquicklinkGridForOutbox&quot;]//input)[1]</value>
      <webElementGuid>2932fdd1-074a-42c0-b3c5-1abc59482afa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
