<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_custom-checkbox</name>
   <tag></tag>
   <elementGuidId>08103ccb-7c8e-4546-ab05-ebb02129fec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (@data-isdirect = 'False') and (@data-message-type = 'outbox') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' custom-checkbox ') and (@data-toggle = 'checkbox') and (@type = 'checkbox') and (@value = '')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.odd[data-isdirect=&quot;False&quot;][data-message-type=&quot;outbox&quot;]:nth-child(1) .custom-checkbox[data-toggle=&quot;checkbox&quot;][type=&quot;checkbox&quot;][value=&quot;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;  To: Provider Portal Attachments  05/18/2026&quot;i] >> internal:label=&quot;&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45f1b33a-c684-4ffb-b719-a981c99f28b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f24e71cf-1f79-43c3-ab0a-58cdfe8031b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>262ab4f2-9250-443b-a2cd-4b460024753e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-checkbox</value>
      <webElementGuid>4ac41778-32d1-43a2-88d4-a2f6cef7192f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-dc12560f92b7834826305abb3e7fcc99</value>
      <webElementGuid>1fddaca4-0130-4e2d-9170-a8a9a174fae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (@data-isdirect = 'False') and (@data-message-type = 'outbox') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' custom-checkbox ') and (@data-toggle = 'checkbox') and (@type = 'checkbox') and (@value = '')]</value>
      <webElementGuid>4ea65fa2-7e5b-4c13-9247-ab03a9bffa97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (@data-isdirect = 'False') and (@data-message-type = 'outbox') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' custom-checkbox ') and (@data-toggle = 'checkbox') and (@type = 'checkbox') and (@value = '')]</value>
      <webElementGuid>017cbc41-edcd-46ae-8534-5f6e4c5d2805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>3f70c41c-3b53-446a-9912-667cef2ad947</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
