<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_openmoreactionsoutbox</name>
   <tag></tag>
   <elementGuidId>4da4ff7c-45c2-4b46-9470-1d7adac177d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'openmoreactionsoutbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#openmoreactionsoutbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#openmoreactionsoutbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cbf08c90-251f-465c-9f5c-85411f1398eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mif-Ellipses secmsg font22 fg-white floatR line-height20 marR10</value>
      <webElementGuid>26ac4172-b7b9-4ea3-818c-a482cc4c4c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenMoreActions(this)</value>
      <webElementGuid>10f1f4ff-1608-4f40-bbc6-201be73a107e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>openmoreactionsoutbox</value>
      <webElementGuid>5360ecec-f112-444e-86cb-a292543da1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1a0c293c6de56d3b67da7fb7e1d04577</value>
      <webElementGuid>eea77633-a093-423f-97d7-9997555433ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'openmoreactionsoutbox']</value>
      <webElementGuid>fcb78f60-0fc3-4405-9085-e29344206635</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'openmoreactionsoutbox']</value>
      <webElementGuid>b0fd3f65-2422-432f-bc5d-a65352b83b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'openmoreactionsoutbox']</value>
      <webElementGuid>e30b3a13-ea06-4c6e-bb41-dacb994c0379</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
