<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Invalid Security Code</name>
   <tag></tag>
   <elementGuidId>19386cc0-b034-40cf-a44e-f87c8665de44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Invalid Security Code&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f61ebe86-3702-4189-94ac-850c3ba3de26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f585bda1-341d-49e3-9258-5799540d8c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>170926f9-296a-45c5-bfc0-31db5506c859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-in</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aca782c5-7b67-4502-bd83-46a2da55946f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Toastify__toast Toastify__toast-theme--colored Toastify__toast--error Toastify__toast--close-on-click</value>
      <webElementGuid>f7ef5a6f-a7ee-430a-8b1f-4936d9241399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>c052011b-ebf3-4315-a4cc-b132d7220080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Security Code</value>
      <webElementGuid>4cecaea3-e813-4a63-b98a-165b94a98901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4&quot;)</value>
      <webElementGuid>08d38f53-bb89-4a0f-b99e-59bfa4c2afe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='4']</value>
      <webElementGuid>33ca750f-fe9c-4b9f-b16b-b674bcbf8cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div/div</value>
      <webElementGuid>202b2166-fbba-4832-b997-99b44fcfae66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Code Sent'])[1]/preceding::div[8]</value>
      <webElementGuid>2de33f61-e5a9-49e6-9ae1-4351980b19b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter security code received on your Phone/Email'])[1]/preceding::div[9]</value>
      <webElementGuid>7fc2a639-3719-48f3-91b6-ffd1d6469ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid Security Code']/parent::*</value>
      <webElementGuid>7456ba00-6ebf-47cb-84e2-e5f158e83553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div</value>
      <webElementGuid>3a875851-9015-4716-8683-874b5f29d69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '4' and (text() = 'Invalid Security Code' or . = 'Invalid Security Code')]</value>
      <webElementGuid>016122b2-1c7c-4460-91c3-cf7a6d0f1a16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
