<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Inbox_1</name>
   <tag></tag>
   <elementGuidId>df01e8d4-8053-4f57-9e40-d48d79a07d97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;inboxmain&quot;]/span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.patientRibbonAddDropdown:nth-child(65) [onclick=&quot;selectMenu\(this\)&quot;]:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Inbox$/ >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3774a80b-2319-4a46-b9b7-057792cf0033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selectMenu(this)</value>
      <webElementGuid>1a005452-3865-4532-920c-a14c166223c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inbox</value>
      <webElementGuid>6529ec80-3b58-4411-920d-7dbbeb584d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ea9f6a37e9436200e8a8d05dc2e1b1df</value>
      <webElementGuid>c300640d-28e0-4d7c-bae1-5a0c68c672a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' patientRibbonAddDropdown ') and (position() = 65)]//*[(@onclick = 'selectMenu(this)') and (position() = 1)]</value>
      <webElementGuid>8b699ffa-3b38-4b3e-be6b-50ed88c0cdb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id=&quot;inboxmain&quot;]/span[1]</value>
      <webElementGuid>f26e1e3b-2ebf-4f27-9890-856c2d67e66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id='inboxmain']//span[normalize-space()='Inbox']</value>
      <webElementGuid>e435d22b-95d3-4e16-862f-0852729131d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
