<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PR_EMAIL_3b6128db1</name>
   <tag></tag>
   <elementGuidId>5a8f8aec-830e-4be6-8567-3b4ca3fc680d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'PatientInfo.PatientPhoneEmail.PhoneNumber[1].NumberWoExtension']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;PatientInfo\.PatientPhoneEmail\.PhoneNumber\[1\]\.NumberWoExtension&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;PatientInfo\.PatientPhoneEmail\.PhoneNumber\[1\]\.NumberWoExtension&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>413cd0d3-07da-4d91-86af-7db8c5cbc18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nochangeevent</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>32bcea0e-10e2-4470-9d12-dc6ea2ccb380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d00e413c-3eaa-4d52-9a39-be0b84c12c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif</name>
      <type>Main</type>
      <value>You must enter phone number</value>
      <webElementGuid>689946a2-2d6f-48bb-bdd8-a483559baa23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-targetvalue</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>cdf1bc09-f3a2-4007-80f0-e95157f9b511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PR_EMAIL_3b6128db1</value>
      <webElementGuid>9c6d7b2b-1cc8-420f-a1c3-cbef907749af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PatientInfo.PatientPhoneEmail.PhoneNumber[1].NumberWoExtension</value>
      <webElementGuid>f7cc956c-d36f-4dd3-b861-c0d669d80163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>DuplicateValidation(this),PhoneEmailValidation(this)</value>
      <webElementGuid>6ce5e5b0-646b-439c-911a-538aae22549f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eefce2a6-77f0-4379-b06f-5bf2dbd05193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>96956088-4069-42c0-a0ac-5fbc57576d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>dc3fe395-3932-40fb-a615-1586e58bb6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-validation-error</value>
      <webElementGuid>8fef26da-fabd-4560-afa4-a892dd37fd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data_commtype</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>4c6901f1-4c31-423b-9cec-b273d536ccc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-email</name>
      <type>Main</type>
      <value>Email is not valid</value>
      <webElementGuid>fab4abdd-2058-44b3-bf14-6bc7ee0565c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-71399a886c53f4d70233538beb17d8fe</value>
      <webElementGuid>f6b533e1-c9ae-43e0-9e54-abc7aef702b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'PatientInfo.PatientPhoneEmail.PhoneNumber[1].NumberWoExtension']</value>
      <webElementGuid>258cc58e-37d8-4170-8631-64d94d2a58e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'PatientInfo.PatientPhoneEmail.PhoneNumber[1].NumberWoExtension']</value>
      <webElementGuid>1c5d0616-dc19-44e2-890a-0d5815afd2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PR_EMAIL_3b6128db1' and @name = 'PatientInfo.PatientPhoneEmail.PhoneNumber[1].NumberWoExtension' and @type = 'text']</value>
      <webElementGuid>95f95a60-a356-4f04-b42e-4c10a2498b9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
