<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_btnCompose</name>
   <tag></tag>
   <elementGuidId>88f1846d-88a0-4243-b4f7-a6fc3749459d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnCompose']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnCompose</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Compose Messages' and @id = 'btnCompose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Compose Messages&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2326021f-da00-4846-9869-52a5fedfce33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mif-circle-plus font22 fg-white floatR line-height20 marR20 secmsg</value>
      <webElementGuid>38bb469c-f875-431c-be25-cb94a2f663d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Compose Messages</value>
      <webElementGuid>9707632f-6658-4d6a-85d6-39815db1dbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCompose</value>
      <webElementGuid>b149ea71-3ba8-4440-9d9f-dcf3ca67e637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>handleBtnComposeClick()</value>
      <webElementGuid>224793ee-045f-480b-9772-5c268ecc5ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-baf32a847ecf6347e796299b2852ae3f</value>
      <webElementGuid>9a54c6d4-8417-4c9e-b315-bce2b5187dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnCompose']</value>
      <webElementGuid>060683ef-0457-46c5-b044-08cc40adf70a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnCompose']</value>
      <webElementGuid>8e2b20be-ca71-4f44-95ed-68cec9484dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Compose Messages' and @id = 'btnCompose']</value>
      <webElementGuid>94275be0-916e-41fa-b3b0-df50cc7e2888</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
