<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_test17</name>
   <tag></tag>
   <elementGuidId>f7191908-9795-4f14-b858-2a842657c051</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblAdvanceFindPatientRecords']//tbody//tr[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-email=&quot;rohitk\@first-insight\.com&quot;] td:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;test17&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3ebc05bc-1303-4787-9056-4c2f6b0f3998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        test17
                    </value>
      <webElementGuid>96aa1032-c171-423d-b69b-bbfbbac728e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9a65d61030ebef96bc5966d70184dd37</value>
      <webElementGuid>300a8bbf-5741-401d-be42-f6db086f8e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-email = 'rohitk@first-insight.com']//*[(name() = 'td') and (position() = 2)]</value>
      <webElementGuid>2a5a0f38-d7c8-4e87-934e-c97e4bd36142</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//table[@id='tblAdvanceFindPatientRecords']//tbody//tr[1]</value>
      <webElementGuid>e66552c6-06b6-46b5-bb71-0cc850d71b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//*[@class=&quot;striped table bordered devtable fixedGridTable fixedGridTableWidth dataTable no-footer&quot;])[2]</value>
      <webElementGuid>279dc6ba-d4e5-430e-aa7d-96fb64ea2a8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
