<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_First Name_ activate to sort column ascending</name>
   <tag></tag>
   <elementGuidId>2bf89d6a-2138-44a3-8a41-ed84673f0868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'First Name: activate to sort column ascending']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;First\ Name\:\ activate\ to\ sort\ column\ ascending&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First Name: activate to sort column ascending&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>1687b699-5900-4bcb-b9c6-ac459a157cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thirdth sorting</value>
      <webElementGuid>d91ed94f-7118-4df3-859f-383c734b45c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e538f332-6b41-44a3-a056-26c1ef282127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tblAdvanceFindPatientRecords</value>
      <webElementGuid>e807bccf-a7a4-4706-bbaa-d3fd8f84b3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ab45b1ad-ea9a-4d2c-bee4-cbdb8314b328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>786a6802-5992-427e-83f2-7c228850cf2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>First Name: activate to sort column ascending</value>
      <webElementGuid>fd1989d1-1d09-4e78-8ef2-0ca165db46f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>6961646c-ac80-45d6-b604-e7685b51c25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-999515522bfad0954bb0d6ae4f5b189a</value>
      <webElementGuid>fb67163e-9c04-4476-a950-2bb48cdbd685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'First Name: activate to sort column ascending']</value>
      <webElementGuid>14de4a8f-22ed-4f86-ae99-9296d9c394b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'First Name: activate to sort column ascending']</value>
      <webElementGuid>1c9e06a2-a50d-4b49-ba71-a295d7660b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'First Name' or . = 'First Name')]</value>
      <webElementGuid>c22e7c5f-7c66-4eb6-928e-092f8fbdd9f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
