<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Final Procedures</name>
   <tag></tag>
   <elementGuidId>722e0f68-66a0-4974-ba9b-e1a87c219bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FinalPro</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#de_tabs-4' and @id = 'FinalPro' and (text() = 'Final Procedures' or . = 'Final Procedures')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='FinalPro']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Final Procedures&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>51536ae1-332b-4669-9224-c3d80a2f02f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#de_tabs-4</value>
      <webElementGuid>96c3f825-977e-45db-acd7-e2c9edd67993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fdDETabAnchorClick(this)</value>
      <webElementGuid>a4e485ee-add7-4ad4-b7ec-5aefbcc1d511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FinalPro</value>
      <webElementGuid>59481da5-c3dc-4a29-82b2-8da2c870270e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-tabs-anchor</value>
      <webElementGuid>bc12a20e-df35-4837-b2eb-93ea4def23eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ad2d6960-e1af-4499-81f1-a1bf42673364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>974a199e-2332-4c35-b6ed-979f5b34e92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Final Procedures</value>
      <webElementGuid>5f750518-a70b-4c47-990d-15a0717e12ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FinalPro&quot;)</value>
      <webElementGuid>ebd6fd0b-0f87-4500-82ff-63225807132b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='FinalPro']</value>
      <webElementGuid>113027ed-ad50-42da-9701-fd7b38169be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DataEntryTabs']/ul/li[5]/a</value>
      <webElementGuid>1876ec6e-4138-4cfb-a9dc-c2cc2a4c6947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Final Procedures')])[2]</value>
      <webElementGuid>f6a34a7b-46ce-4773-9c7a-3641eefa80a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plans'])[2]/following::a[1]</value>
      <webElementGuid>f802e164-d890-4d33-9bd9-944e5f24a2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assessments'])[2]/following::a[2]</value>
      <webElementGuid>68747833-3afd-4856-850d-8a8491f8ddad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#de_tabs-4')]</value>
      <webElementGuid>2d97cfad-5e1f-4964-ad54-5fa55268c225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/ul/li[5]/a</value>
      <webElementGuid>40eb4bfb-1a46-4206-ac8e-b8538a2cd44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#de_tabs-4' and @id = 'FinalPro' and (text() = 'Final Procedures' or . = 'Final Procedures')]</value>
      <webElementGuid>6143d133-8c46-42eb-8722-d1f98b59f137</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
