<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Radiating_SEVERITY_GF_9933_GF_B-1Img</name>
   <tag></tag>
   <elementGuidId>2c683e10-d76d-40b4-8df2-19e06bc12ad6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'SEVERITY_GF_9933_GF_B-1Img' and @src = '/DXR.axd?r=1_110-rQDpv' and @alt = 'v']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='v'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SEVERITY_GF_9933_GF_B-1Img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;v Disabling Mild Moderate Severe&quot;s] >> internal:attr=[alt=&quot;v&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>41117261-1c30-4079-a220-d3332b62f8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SEVERITY_GF_9933_GF_B-1Img</value>
      <webElementGuid>1057bcf7-d077-457c-9645-23b6df6e81e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxEditors_edtDropDown_Metropolis</value>
      <webElementGuid>2a28765a-e188-4dc8-b7ee-6bac475472cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DXR.axd?r=1_110-rQDpv</value>
      <webElementGuid>896f5b8c-0487-4be3-bcd9-0082bfb6ad99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>16f87ac6-6f12-4118-afd2-02b7bd3662f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SEVERITY_GF_9933_GF_B-1Img&quot;)</value>
      <webElementGuid>f58f8b49-7b49-4aab-a057-8b85ec1a9211</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='SEVERITY_GF_9933_GF_B-1Img']</value>
      <webElementGuid>b7dfb733-6e4a-450e-8ac1-850a95a6dc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='SEVERITY_GF_9933_GF_B-1']/img</value>
      <webElementGuid>211651a4-e2da-45ee-b2d9-c8dfc353eb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='v'])[4]</value>
      <webElementGuid>4dc561c8-dc13-4797-944b-504ebd62316c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div[2]/table/tbody/tr/td[4]/img</value>
      <webElementGuid>6da95cd7-d926-467d-94a3-9d38a9c35439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'SEVERITY_GF_9933_GF_B-1Img' and @src = '/DXR.axd?r=1_110-rQDpv' and @alt = 'v']</value>
      <webElementGuid>4b31bc0c-1713-489d-899f-fd52ad7b891f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
