<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Severe_DURATION_GF_9933_GF_B-1Img</name>
   <tag></tag>
   <elementGuidId>5ddd9206-1e5f-4ed9-a60a-f6c3a4c48777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'DURATION_GF_9933_GF_B-1Img' and @src = '/DXR.axd?r=1_110-rQDpv' and @alt = 'v']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='v'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DURATION_GF_9933_GF_B-1Img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;v Seconds 1 min 5 min 20 min 30 min 1 hour All am All pm All day&quot;s] >> internal:attr=[alt=&quot;v&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2ac227cc-aaf9-457a-922a-5aeb679fa5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DURATION_GF_9933_GF_B-1Img</value>
      <webElementGuid>c020ef28-0c44-4312-b69c-38b6f48b4306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxEditors_edtDropDown_Metropolis</value>
      <webElementGuid>8b0f9510-ff03-437f-a46f-e83efdd37dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DXR.axd?r=1_110-rQDpv</value>
      <webElementGuid>03f00749-9d23-4e37-a9b8-549a759e511f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>8681420a-8892-435a-870c-8ec91196e1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DURATION_GF_9933_GF_B-1Img&quot;)</value>
      <webElementGuid>3452dbf1-6ace-49c3-bd90-c84fc5252f54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='DURATION_GF_9933_GF_B-1Img']</value>
      <webElementGuid>400256c4-4dca-421e-ba0c-ce248ae3883d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='DURATION_GF_9933_GF_B-1']/img</value>
      <webElementGuid>9b6d7af0-8e6b-4804-a511-8aaa5d901de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='v'])[5]</value>
      <webElementGuid>92ca018f-23ac-4f37-8b7f-f2b960e53dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div[2]/table/tbody/tr/td[4]/img</value>
      <webElementGuid>c8ec8db1-e986-43b3-93fa-d70fbd204a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'DURATION_GF_9933_GF_B-1Img' and @src = '/DXR.axd?r=1_110-rQDpv' and @alt = 'v']</value>
      <webElementGuid>1fab5204-19af-472f-8dc8-fa553005c6ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
