<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Are you sure you want to sign off the_f71194</name>
   <tag></tag>
   <elementGuidId>43126dba-c796-4dec-89e2-fa8f82315b66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Yes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Yes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;YES&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2d52289-efad-43a0-9be9-22cd5df0a1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f3fbe45b-15d1-4be8-bc4a-06f474b83d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>YES</value>
      <webElementGuid>b2267659-b1f6-4bbb-b573-6da0e9646584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn1</value>
      <webElementGuid>7e1f5dfe-c81f-49ab-ad19-44d1a6a6ac8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semi-bold font20 hide-confirmation ignore-action-toggle  margin-right-10px margin-top-10px  padButtonLR notifationButton</value>
      <webElementGuid>aa5f5e8b-1891-4fd9-922e-ef4010d09538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>b00f5575-d1bd-40f4-a777-4b58ee5f5694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>f03c54a3-6282-4a59-babb-4daea4dd2923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Yes&quot;)</value>
      <webElementGuid>b1151b05-2443-432f-8138-afb63baecbf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Yes']</value>
      <webElementGuid>94768de7-9bb1-4058-a2a6-7ee5191e8b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ConfirmationBar']/div/div/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>36afbb15-68b1-44dc-be16-730cd6b85c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>53db5b82-d932-425a-91bf-f498c5f7ff17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btn1' and @id = 'Yes']</value>
      <webElementGuid>b43545d9-13f3-4abc-8ce4-98dae05e4237</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
