<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Drug_MEDICATION_BRAND_NAME_I</name>
   <tag></tag>
   <elementGuidId>7fef4bd9-229c-4322-9799-3684871525c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MEDICATION_BRAND_NAME_I</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'MEDICATION_BRAND_NAME_I' and @name = 'MEDICATION_BRAND_NAME' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MEDICATION_BRAND_NAME_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MEDICATION_BRAND_NAME_I</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>def69172-0cc9-45ee-acc1-7a4388497f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Metropolis dxeEditAreaSys dxh0</value>
      <webElementGuid>d746d5a7-4d76-4001-8d6c-6a232f7dfda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MEDICATION_BRAND_NAME_I</value>
      <webElementGuid>f91d7c39-2fcf-45ed-95c1-7c2eec162a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MEDICATION_BRAND_NAME</value>
      <webElementGuid>5103c96c-4398-43b1-b034-fa5b0d66309f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('MEDICATION_BRAND_NAME')</value>
      <webElementGuid>f55bf03c-ba63-4b70-aac0-a61064b28787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('MEDICATION_BRAND_NAME')</value>
      <webElementGuid>283f05f6-8ac1-4a63-b14b-e90a468da04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.ETextChanged('MEDICATION_BRAND_NAME')</value>
      <webElementGuid>53cffb9b-c840-426d-9d53-4ea6b891967b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20b9da37-fa1a-466f-bb64-a92e5d3a248e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e7d1f15f-f2a7-4883-9446-9dfb3ca83c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>3bf7aca4-9c27-46a2-8a9c-c9907fef7b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MEDICATION_BRAND_NAME_I&quot;)</value>
      <webElementGuid>0b9ce550-afb5-47f6-baa0-2db05bf21a69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MEDICATION_BRAND_NAME_I']</value>
      <webElementGuid>a94462c3-ea1f-4206-a170-4d1ec889e3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='MEDICATION_BRAND_NAME']/tbody/tr/td[2]/input</value>
      <webElementGuid>129eb2dc-5c83-40d0-a73b-41291ae38567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/table/tbody/tr/td[2]/input</value>
      <webElementGuid>a9d2310e-664c-4e25-a4fd-44ec675a0037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MEDICATION_BRAND_NAME_I' and @name = 'MEDICATION_BRAND_NAME' and @type = 'text']</value>
      <webElementGuid>0f0328cf-5629-46cf-90ec-e6f22cd70788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
