<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pediatric Vital Signs_4250.Vital_Sign_971c23</name>
   <tag></tag>
   <elementGuidId>9fa4037a-7865-4076-a1ea-366b579188db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;4250.Vital_Signs.TEMPERATURE&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = '4250.Vital_Signs.TEMPERATURE']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='4250.Vital_Signs.TEMPERATURE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;\34 250\.Vital_Signs\.TEMPERATURE&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>527609ac-0e20-4d08-a89f-e0073107a6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a089911b-4b09-4cdd-b24b-dbe77e5d967e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sysdef</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>16a23710-cd35-468e-b680-83cdfb31035d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4ef942d8-3e14-4d3c-a35e-f22f0181a514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reffield</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f0a15ec-ebbc-4c80-9359-b8eae0acb33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isrefered</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b7c73e7d-afa3-4cc7-9ac5-2c4a85db9292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>9fa9f01b-ac6b-4f5e-96f7-8ef25763b005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>4250.Vital_Signs.TEMPERATURE</value>
      <webElementGuid>22e827ac-bdc0-485f-9cd3-b16fe36dc477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5319</value>
      <webElementGuid>7805f5d1-b320-4da3-a7b7-96ff854811bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec_ctrldispname</name>
      <type>Main</type>
      <value>Temperature</value>
      <webElementGuid>199f6531-4b85-487c-a764-e336aca63c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-canbehidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cea81af0-5d23-44b6-98db-27bea47d56b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cid</name>
      <type>Main</type>
      <value>1571</value>
      <webElementGuid>2b63b991-8a34-4595-b838-d0917b619a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isreadonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>db248d53-4f95-49ad-8fef-f09eeaae4f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementid</name>
      <type>Main</type>
      <value>109</value>
      <webElementGuid>7acb309f-425a-4198-8212-9a6fe1762019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enc_elementpagerelid</name>
      <type>Main</type>
      <value>4250</value>
      <webElementGuid>f1c78f6c-fc0b-4f6c-a80c-2c27446a2709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec_valuelistname</name>
      <type>Main</type>
      <value>Laser_Surgery_Temp</value>
      <webElementGuid>3d4cf55b-631c-41b8-b549-ef3b44f14647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>8748581f-7f70-4158-aadb-fedbbdd8e09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>232c90e9-09cb-4d0f-8b9b-21a90f98ced5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>eE_SetCurrentTime(this,false,&quot;TEMPERATURE_TIME&quot;)</value>
      <webElementGuid>bfa23186-ab76-43db-97e3-ef9d96f8d9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refelmid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>36ff1e50-6c01-4a23-825c-650ef0eb88d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~F_F~Vital_Signs.TEMPERATURE</value>
      <webElementGuid>3e5efc2c-7207-4d25-81d6-b363f4ce1ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>TEMPERATURE</value>
      <webElementGuid>076c6002-ce04-45ef-97ca-360f702f59db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Vital_Signs</value>
      <webElementGuid>ed291e46-9af4-4b2c-8dfc-7797a3b7dd53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;encformbase7165&quot;)/div[@class=&quot;layerClass&quot;]/div[@class=&quot;box1&quot;]/div[@class=&quot;defaultElemStyle&quot;]/input[@class=&quot;ui-autocomplete-input&quot;]</value>
      <webElementGuid>13ab8f30-fa36-438d-91fb-b7875f0172c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='4250.Vital_Signs.TEMPERATURE']</value>
      <webElementGuid>36a0e987-d69f-49e6-a862-f65cec9a1a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='encformbase7165']/div/div/div/input[13]</value>
      <webElementGuid>f155ebcc-2153-40cf-b9bd-de7834bc91fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[13]</value>
      <webElementGuid>154180de-7c05-412b-87eb-f1370e089212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = '4250.Vital_Signs.TEMPERATURE']</value>
      <webElementGuid>7490d492-aa08-43d9-83d2-6c4ccd7ee09f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
