<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type_ORDER_TYPE</name>
   <tag></tag>
   <elementGuidId>95a32a28-4cd9-4ad1-b1f0-08ef620c1b41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ORDER_TYPE</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ORDER_TYPE' and @name = 'ORDER_TYPE' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ORDER_TYPE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ORDER_TYPE</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54878fcf-6a52-459c-b59c-e686a173f7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ORDER_TYPE</value>
      <webElementGuid>c9d25108-a2d4-46d7-9a50-49086c913734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nochangeevent</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>36df4b82-7903-451c-9887-80d65c22f323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ORDER_TYPE</value>
      <webElementGuid>cbda6000-5c83-41c9-9f96-6d7d1ee19083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7682345-27c0-4bc3-b6b1-4bb15102e52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>195572fd-6649-4e32-8a79-c311aeb8fadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>80c81d5b-ffbe-4d06-be09-3c4af1ff92ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec_valuelistname</name>
      <type>Main</type>
      <value>Auxiliary_Tests_Automated_VF_Type,TYPE</value>
      <webElementGuid>c0594934-781b-46db-93f7-9d660eedfe1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>b29d7e06-5fc1-4784-a91c-cc19e4e73df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ORDER_TYPE&quot;)</value>
      <webElementGuid>4039e7b9-034e-4cb7-8d4f-ec1560c15f1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ORDER_TYPE']</value>
      <webElementGuid>97bf669b-bf12-4826-a03a-d99391f623c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AuxiliaryLabData']/div/div/div/div[3]/div/span/input</value>
      <webElementGuid>b3209ba0-cc3b-40ab-93b5-de82215726f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/input</value>
      <webElementGuid>22382053-0ad6-4bc4-bdd4-7be06872adfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ORDER_TYPE' and @name = 'ORDER_TYPE' and @type = 'text']</value>
      <webElementGuid>0b0e6479-5866-450d-a1a7-de6669a12c1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
