<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loading_DESCRIPTION_GF_b04f_GF_I</name>
   <tag></tag>
   <elementGuidId>dcc7aab8-f748-4ae6-805b-50e8b4e17b8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[2]/tbody/tr/td[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DESCRIPTION_GF_b04f_GF_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#DESCRIPTION_GF_b04f_GF_I</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24389ffb-3124-4340-a76a-99b68bc1d24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Metropolis dxeEditAreaSys dxh0</value>
      <webElementGuid>63bcfd77-9407-4e6d-be55-a5c76cfdfcf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DESCRIPTION_GF_b04f_GF_I</value>
      <webElementGuid>c6b0c999-53bc-4fd9-9f04-775f0bd8fecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DESCRIPTION_GF_b04f_GF</value>
      <webElementGuid>ec4d7335-8830-42c9-80ad-8e3e980ea5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('DESCRIPTION_GF_b04f_GF')</value>
      <webElementGuid>eaa27c31-4bca-49ed-8a19-e7f1509a2694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('DESCRIPTION_GF_b04f_GF')</value>
      <webElementGuid>bd37bdd6-08d9-455e-8858-79c037967cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.ETextChanged('DESCRIPTION_GF_b04f_GF')</value>
      <webElementGuid>7e014235-5500-43f7-b6eb-e7f43bc92579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3fcdcefe-46bb-4d15-a738-edcb699f206d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>411ce085-4d9a-4e2d-ab21-e94cb6a5f4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>3a37a927-126b-47a1-9620-8d4076170c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DESCRIPTION_GF_b04f_GF_I&quot;)</value>
      <webElementGuid>beea3c8c-13da-4941-b690-bbe777e74540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DESCRIPTION_GF_b04f_GF_I']</value>
      <webElementGuid>53513bf7-3e77-4044-9e50-6910f236f727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DESCRIPTION_GF_b04f_GF']/tbody/tr/td[2]/input</value>
      <webElementGuid>2f3892cb-54ce-44bf-b60c-194058c568d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/input</value>
      <webElementGuid>78414452-6631-4163-afbc-5454f13dbdc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DESCRIPTION_GF_b04f_GF_I' and @name = 'DESCRIPTION_GF_b04f_GF' and @type = 'text']</value>
      <webElementGuid>4e70c50a-63ec-4f51-b875-83541d57b8e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
