<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Recordof_btnAddCollapse</name>
   <tag></tag>
   <elementGuidId>aed6f4de-6f93-46f3-9fd8-7aba936c2f90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAddCollapse</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'btnAddCollapse']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnAddCollapse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;SAVE&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ec2d031-fd67-4bad-b690-04ee9cad4566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button small-button50 primary</value>
      <webElementGuid>6889590a-c31a-46d4-9cb7-5958b821478c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6f5ed01-4719-46ee-a890-0aae6269131c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddCollapse</value>
      <webElementGuid>4b326c34-deb1-4df3-a35c-b5f96a9e965b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SAVE</value>
      <webElementGuid>2029e955-e896-45a6-af47-62be4caf9148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AddAuxiliaryLabOrderTestPanelData(this, true)</value>
      <webElementGuid>d2c12592-97b7-43af-a19a-99e62490f8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>AUXILIARY_&amp;_LAB_TESTS</value>
      <webElementGuid>de36c60e-5582-4442-b87a-025a3d908a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddCollapse&quot;)</value>
      <webElementGuid>7e98e86e-2b56-491b-bf13-08309f9961e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnAddCollapse']</value>
      <webElementGuid>62f05a91-b207-40fc-8457-8079b6d02076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AddEditAuxLabOrdersPopup']/div/div/div[2]/div/div/input</value>
      <webElementGuid>b68b33eb-9177-4632-919d-b5509c5cc98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/input</value>
      <webElementGuid>7383bf45-19f2-42a4-ba57-1d86a0aaf3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnAddCollapse']</value>
      <webElementGuid>46bd28be-ef57-463c-ac65-21e8ef415689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
