<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search Problem Field</name>
   <tag></tag>
   <elementGuidId>2299865f-8270-4fed-9968-56ac2db46fa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='problemListGridView_df4a_EEG_DXSE_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#problemListGridView_df4a_EEG_DXSE_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#problemListGridView_df4a_EEG_DXSE_I</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c7a3892-a815-4308-ac18-965fb7288240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Metropolis dxeEditAreaSys</value>
      <webElementGuid>91df53a7-0433-4967-a6a7-0097cce942c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>problemListGridView_df4a_EEG_DXSE_I</value>
      <webElementGuid>a13f9962-7fa9-42e4-b2fc-3e9a19949fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>problemListGridView_df4a_EEG$DXSE</value>
      <webElementGuid>5a02c425-d21a-4b2d-ac4f-4699f383f1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('problemListGridView_df4a_EEG_DXSE')</value>
      <webElementGuid>bcfcb61f-3179-4834-afd0-eb7165dc829d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('problemListGridView_df4a_EEG_DXSE')</value>
      <webElementGuid>ac462167-64ce-4a5c-b60e-1cb48aaee7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.EValueChanged('problemListGridView_df4a_EEG_DXSE')</value>
      <webElementGuid>fe5ad309-55ae-4e4a-b11e-af6103a366f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Existing Problems</value>
      <webElementGuid>7a8c2c89-19e6-4652-8bf5-60daf1e4280a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4d3f2f6-84d6-4806-8ce2-2e0d931037bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;problemListGridView_df4a_EEG_DXSE_I&quot;)</value>
      <webElementGuid>2fb7be7e-031e-47c2-a570-20dfe32e74a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='problemListGridView_df4a_EEG_DXSE_I']</value>
      <webElementGuid>817d365d-81de-4d79-b4ff-faac507254d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='problemListGridView_df4a_EEG_DXSE']/tbody/tr/td/input</value>
      <webElementGuid>e9a4b874-ec57-4895-8b4e-81f685f9d3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/table/tbody/tr/td/div/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>8127d538-cdff-4bf0-935d-cd4f74ede2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'problemListGridView_df4a_EEG_DXSE_I' and @name = 'problemListGridView_df4a_EEG$DXSE' and @type = 'text']</value>
      <webElementGuid>600135ef-8d83-42aa-b999-e77ced94a32b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
