<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Patient Portal_uploadEMToPatientPortal</name>
   <tag></tag>
   <elementGuidId>e0dc57f5-ca05-41ed-839e-bc7bdd7030b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='uploadEMToPatientPortal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uploadEMToPatientPortal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Upload to Patient Portal&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a7c653d6-0b88-4fa0-ba07-576a8135a502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mif-Upload fg-purple font23 marL10</value>
      <webElementGuid>876827b1-c19b-4d9e-8d69-083c86cccf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadEMToPatientPortal</value>
      <webElementGuid>8f09e476-0947-48b3-b0b0-131e552301a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Upload to Patient Portal</value>
      <webElementGuid>7bb718d3-8d32-4338-9ae4-4ed1962693f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadEMToPatientPortal&quot;)</value>
      <webElementGuid>5af5c646-3f8b-484b-b247-ed2712d4d668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='uploadEMToPatientPortal']</value>
      <webElementGuid>37b39f5c-00a4-4653-aeb5-80627d0bcf77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='12362']/div/div[2]/div/div/div/div/div/span[6]</value>
      <webElementGuid>1bee09f2-89b4-453f-b3d2-f7a039e7056a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/span[6]</value>
      <webElementGuid>a520e404-8710-45e7-b12a-ee999e9fa02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'uploadEMToPatientPortal' and @title = 'Upload to Patient Portal']</value>
      <webElementGuid>47fd0300-f163-4916-8aae-f348adcc6e86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
