<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TOC Req_mif-Hamburger fg-gray font30</name>
   <tag></tag>
   <elementGuidId>5bc35c16-0c56-4736-a777-befa7f5bbb62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mif-Hamburger.fg-gray.font30</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'More']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='showMoreMenu(this)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>41b53873-7941-4b72-9ea7-fd623eef9f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mif-Hamburger fg-gray font30</value>
      <webElementGuid>ecd08e8f-9a15-4f8a-9442-eb769c241cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showMoreMenu(this)</value>
      <webElementGuid>4385d54b-8cfe-4f05-a25e-a44b87570959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>More</value>
      <webElementGuid>d832f81e-e148-4aee-8e54-d2dd60e231b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patientEncounterHeader&quot;)/div[@class=&quot;col-xs-12 col-sm-12 col-md-12 col-lg-5 no-padding marT10&quot;]/ul[@class=&quot;ribbon-encounter-left-icons&quot;]/li[1]/a[@class=&quot;line-height34&quot;]/span[@class=&quot;mif-Hamburger fg-gray font30&quot;]</value>
      <webElementGuid>a99d32fc-e6c3-4b86-abb0-14bd27a9c539</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='showMoreMenu(this)']</value>
      <webElementGuid>0ee6c156-0478-49a2-82d5-669f10d50071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='patientEncounterHeader']/div[2]/ul/li/a/span</value>
      <webElementGuid>a976f68b-b5b4-4c0b-992a-c7b8d9c650be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a/span</value>
      <webElementGuid>7a8d89eb-ca98-458a-a58b-119a05758a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'More']</value>
      <webElementGuid>434a7aee-0ade-4e98-bdf5-60feaeae497a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
