<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_100414</name>
   <tag></tag>
   <elementGuidId>95697d4d-c38e-4303-8db1-bea68e832305</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#out > table > tbody > tr:nth-of-type(9) > td:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '100414' or . = '100414')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='out']/table/tbody/tr[9]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;100414&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ab6e83f6-f378-4315-8aca-9eecc35b38b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>35%</value>
      <webElementGuid>9caeeafa-bb0a-42fe-be68-9dfdcc327547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>432b7acb-e988-42ab-84a5-95dcd782d978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100414</value>
      <webElementGuid>e23bd08a-0747-48b2-a0d7-b93be921c4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;out&quot;)/table[1]/tbody[1]/tr[9]/td[2]</value>
      <webElementGuid>9b035b6b-e7f4-4230-b6d9-df940cd388de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='out']/table/tbody/tr[9]/td[2]</value>
      <webElementGuid>b066c90f-de1a-41be-801e-4a51b276fcea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Id:'])[1]/following::td[1]</value>
      <webElementGuid>11d46828-7c4e-4153-9565-0d911efe7cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous Address:'])[1]/following::td[5]</value>
      <webElementGuid>133fb5d8-68aa-4185-bec3-1baf1938da47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOB:'])[1]/preceding::td[1]</value>
      <webElementGuid>6f949d3f-6620-46bc-a1a5-1973ddcfc833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sex:'])[1]/preceding::td[3]</value>
      <webElementGuid>50115e7c-9cc0-4780-a3bc-0725a518b637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/table/tbody/tr[9]/td[2]</value>
      <webElementGuid>e85fc9ef-2438-405b-9266-b8e558094274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '100414' or . = '100414')]</value>
      <webElementGuid>50f83a7e-7f76-4bfe-b77c-27e44b90646f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
