<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_100259</name>
   <tag></tag>
   <elementGuidId>433b49dd-ef1c-4da8-aed8-1137398e1999</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '100259' or . = '100259')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Encounter ']/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;100259&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>8c561350-bbf2-4b5f-ae42-81ef169eb1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>6e1b645a-ef79-4623-8d5e-b8d2dcd74079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100259</value>
      <webElementGuid>d388fc50-2bbc-49c5-a34e-1fa219ab113d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Encounter &quot;)/table[1]/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>19922a34-c865-4b81-b9d7-fd9db3068004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Encounter ']/table/tbody/tr/td</value>
      <webElementGuid>aac4501d-ddeb-43b0-ae77-99157060372b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encounter Provider'])[1]/following::td[1]</value>
      <webElementGuid>96a00ee1-c53f-4dc9-98ad-9ac32cde004b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encounter Date'])[1]/following::td[1]</value>
      <webElementGuid>d4877a17-82bf-4afe-b3ff-d96936ed9fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Element Test Encounter'])[2]/preceding::td[1]</value>
      <webElementGuid>a91e234d-aa18-4ace-bba2-44b0a98a14ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Portal'])[17]/preceding::td[3]</value>
      <webElementGuid>b77a3b30-983d-4b4e-a859-10cd844ac973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/table/tbody/tr/td</value>
      <webElementGuid>c0008c6b-8fc9-4df3-bece-bea1c6993120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '100259' or . = '100259')]</value>
      <webElementGuid>b29bf41e-83f0-43c6-bf5d-9c72deaaea85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
