<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Asthma_DESCRIPTION_GF_df4a_GF_DDD_L_LBI3T0</name>
   <tag></tag>
   <elementGuidId>ead3479c-4df7-46d6-b9c3-167fc78dd954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='DESCRIPTION_GF_df4a_GF_DDD_L_LBI3T0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DESCRIPTION_GF_df4a_GF_DDD_L_LBI3T0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Obesity&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>8b8fdd41-08eb-4cca-8d52-474af66c0086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DESCRIPTION_GF_df4a_GF_DDD_L_LBI3T0</value>
      <webElementGuid>9aada944-2e0e-4bf5-a876-38d7b9f8f5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_Metropolis dxeListBoxItemHover_Metropolis dxeListBoxItemSelected_Metropolis</value>
      <webElementGuid>567700fc-9689-4fc1-8008-d8e5ac1855d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Obesity</value>
      <webElementGuid>5630411b-1e04-437c-8b22-b66467cc31d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DESCRIPTION_GF_df4a_GF_DDD_L_LBI3T0&quot;)</value>
      <webElementGuid>a8d3cb79-eff2-4027-9bfb-9cd619f7f294</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='DESCRIPTION_GF_df4a_GF_DDD_L_LBI3T0']</value>
      <webElementGuid>b8d4ad65-9de4-4a3e-8afe-4cf52ee2f568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DESCRIPTION_GF_df4a_GF_DDD_L_LBT']/tr[4]/td</value>
      <webElementGuid>498a4bd6-f539-4d25-9901-77e182b8303a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asthma'])[1]/following::td[1]</value>
      <webElementGuid>de06e456-5dbf-4504-87a6-c56b7675fa26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diabetes mellitus'])[1]/preceding::td[1]</value>
      <webElementGuid>1b36a0c5-7e2d-4fa9-82be-6b47f28349c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allergic rhinitis'])[1]/preceding::td[2]</value>
      <webElementGuid>d7cf22c1-aefc-4c42-8e37-cc1295f31df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Obesity']/parent::*</value>
      <webElementGuid>9213a327-54b7-4c3a-a44b-38545eda5bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tr[4]/td</value>
      <webElementGuid>2d37b200-0336-41bc-b4fa-5ee2c5119ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'DESCRIPTION_GF_df4a_GF_DDD_L_LBI3T0' and (text() = 'Obesity' or . = 'Obesity')]</value>
      <webElementGuid>d0bfff78-5c87-4e85-9695-c68f1945a421</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
