<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Aching</name>
   <tag></tag>
   <elementGuidId>7fb54ba4-2e4b-486e-9b47-a766bfc81b3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'QUALITY_GF_9933_GF_DDD_L_LBI0T0' and (text() = 'Aching' or . = 'Aching')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='RLL'])[1]/following::td[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#QUALITY_GF_9933_GF_DDD_L_LBI0T0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Aching&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f0b66dd5-4cb4-4242-bcb7-f6ebb1b54de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QUALITY_GF_9933_GF_DDD_L_LBI0T0</value>
      <webElementGuid>5a883763-ae55-45b8-aeb2-1cb1eeb561da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_Metropolis dxeListBoxItemHover_Metropolis dxeListBoxItemSelected_Metropolis</value>
      <webElementGuid>4cc92e75-1fba-4b7a-8739-62c57dfed566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aching</value>
      <webElementGuid>277e4bad-87b3-4645-a30f-5866747a3cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QUALITY_GF_9933_GF_DDD_L_LBI0T0&quot;)</value>
      <webElementGuid>b2353ebe-dcd9-491d-8b27-2427a8438e50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='QUALITY_GF_9933_GF_DDD_L_LBI0T0']</value>
      <webElementGuid>2a8532a5-f373-4002-be46-8f51b0744ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='QUALITY_GF_9933_GF_DDD_L_LBT']/tr/td</value>
      <webElementGuid>d0d78e91-e0dc-4346-b715-d2bada319fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RLL'])[1]/following::td[8]</value>
      <webElementGuid>13c55e03-4af3-4023-8dd8-1d478b6e2a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUL'])[1]/following::td[9]</value>
      <webElementGuid>7f7122c2-c90f-4f2b-83c5-7ffececb2527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Burning'])[1]/preceding::td[1]</value>
      <webElementGuid>02e37f04-18f1-4b28-b7d2-8306eb0f696b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Radiating'])[1]/preceding::td[2]</value>
      <webElementGuid>faa402a6-c3a4-4a1e-b8d5-43aef36dec10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aching']/parent::*</value>
      <webElementGuid>ef47c79b-ed51-483a-aaa3-2122f0925fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div[2]/div/div/div/div/table/tbody/tr/td/div/div/table[2]/tr/td</value>
      <webElementGuid>3a669a14-04e0-4a93-a403-bda0ff4523d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'QUALITY_GF_9933_GF_DDD_L_LBI0T0' and (text() = 'Aching' or . = 'Aching')]</value>
      <webElementGuid>377944e3-ce36-4351-99d8-5bab4fff18c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
