<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Asthma</name>
   <tag></tag>
   <elementGuidId>eb80a8f1-7d71-443f-9913-5f29d97f992a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'DESCRIPTION_GF_d9d0_GF_DDD_L_LBI2T0' and (text() = 'Asthma' or . = 'Asthma')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Gastroesophageal reflux disease'])[1]/following::td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DESCRIPTION_GF_d9d0_GF_DDD_L_LBI2T0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Asthma&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0039e9c8-f1d4-49c7-b754-c45093572e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DESCRIPTION_GF_d9d0_GF_DDD_L_LBI2T0</value>
      <webElementGuid>2ce3d13b-3474-4e98-b3df-fdb95823e2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_Metropolis dxeListBoxItemHover_Metropolis dxeListBoxItemSelected_Metropolis</value>
      <webElementGuid>398c538d-c929-4a4f-b91c-d1737b50efa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asthma</value>
      <webElementGuid>a1b18a0e-aaea-4ee4-a3fa-8c16137e685c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DESCRIPTION_GF_d9d0_GF_DDD_L_LBI2T0&quot;)</value>
      <webElementGuid>1c028caf-2174-4b0b-abca-041d0acda859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='DESCRIPTION_GF_d9d0_GF_DDD_L_LBI2T0']</value>
      <webElementGuid>69891990-29a5-4f2b-9206-7ce5b390fcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DESCRIPTION_GF_d9d0_GF_DDD_L_LBT']/tr[3]/td</value>
      <webElementGuid>8fce10b0-031d-442c-9bc5-6f9a6bf63f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gastroesophageal reflux disease'])[1]/following::td[2]</value>
      <webElementGuid>7c4a2c88-92ca-46c8-90ae-6183a65090d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Obesity'])[1]/preceding::td[1]</value>
      <webElementGuid>9b80226f-a3aa-48c4-8841-a39e648ebe17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diabetes mellitus'])[1]/preceding::td[2]</value>
      <webElementGuid>18c481a7-c855-4378-91e0-1259c5f6083a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Asthma']/parent::*</value>
      <webElementGuid>6a287ed1-c90e-4e3e-bfb2-b875d03113cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/table/tbody/tr/td/div/div/table[2]/tr[3]/td</value>
      <webElementGuid>103d0d36-b03c-43e1-be3c-7f2b84a4f195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'DESCRIPTION_GF_d9d0_GF_DDD_L_LBI2T0' and (text() = 'Asthma' or . = 'Asthma')]</value>
      <webElementGuid>0b41ebf6-6e91-4abb-b1f2-381772d12a55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
