<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Chronic_SOURCE_GF_b04f_GF_DDD_L_LBI0T0</name>
   <tag></tag>
   <elementGuidId>8521fe37-b08b-4bc9-a085-ad2fc28104bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Chronic'])[2]/following::td[15]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SOURCE_GF_b04f_GF_DDD_L_LBI0T0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;EHR&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>58ecc03b-7aaa-4522-bed2-770f3752b665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SOURCE_GF_b04f_GF_DDD_L_LBI0T0</value>
      <webElementGuid>d311bcbb-0799-4ca8-9616-a564e113de92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_Metropolis dxeListBoxItemHover_Metropolis dxeListBoxItemSelected_Metropolis</value>
      <webElementGuid>f41b0145-cc82-4a3a-8dfe-4be51dac3c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EHR</value>
      <webElementGuid>b11ddbef-f5a5-4869-8b3a-bbe8eb139ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SOURCE_GF_b04f_GF_DDD_L_LBI0T0&quot;)</value>
      <webElementGuid>3e49a3b7-d8c7-44b9-a208-6ab2ba78f53f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='SOURCE_GF_b04f_GF_DDD_L_LBI0T0']</value>
      <webElementGuid>20b4a324-bcce-4af9-abc2-12fa7d74011c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='SOURCE_GF_b04f_GF_DDD_L_LBT']/tr/td</value>
      <webElementGuid>f9d533e7-25e4-4594-b82d-77abb940afca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chronic'])[2]/following::td[15]</value>
      <webElementGuid>01b9b683-e7df-430e-bfb6-6756853e1f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolved'])[3]/following::td[16]</value>
      <webElementGuid>62c91a24-a0a2-4689-b10c-288ab69a2f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EHR - Dr'])[1]/preceding::td[1]</value>
      <webElementGuid>a5275c84-733a-4e1b-86b1-69f012a56aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EHR - Tech'])[1]/preceding::td[2]</value>
      <webElementGuid>b26814e3-4e6f-4f10-87f5-371a855a8924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EHR']/parent::*</value>
      <webElementGuid>e48b6131-ff33-4f6b-a212-5c00fa0e5b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div[2]/div/div/div/div/table/tbody/tr/td/div/div/table[2]/tr/td</value>
      <webElementGuid>b64e9a40-1e1c-4ff8-a616-8e322300dcfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'SOURCE_GF_b04f_GF_DDD_L_LBI0T0' and (text() = 'EHR' or . = 'EHR')]</value>
      <webElementGuid>e91a2031-5444-43a4-abc9-57954944ff0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
