<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_EHR</name>
   <tag></tag>
   <elementGuidId>75ac6f81-d32f-43ab-92ef-49b002101ca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'SOURCE_GF_d9d0_GF_DDD_L_LBI0T0' and (text() = 'EHR' or . = 'EHR')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Chronic'])[2]/following::td[15]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SOURCE_GF_d9d0_GF_DDD_L_LBI0T0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SOURCE_GF_d9d0_GF_DDD_L_LBI0T0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>068debe4-25f1-4a08-b890-01aa277e0a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SOURCE_GF_d9d0_GF_DDD_L_LBI0T0</value>
      <webElementGuid>67ab4036-4aa3-4d3f-8b5b-d7e9024b03d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_Metropolis dxeListBoxItemHover_Metropolis dxeListBoxItemSelected_Metropolis</value>
      <webElementGuid>728c976c-e05e-4eab-b036-6d1fef72b1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EHR</value>
      <webElementGuid>ebc5096c-c1bd-46fe-b381-7b39b56fa5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SOURCE_GF_d9d0_GF_DDD_L_LBI0T0&quot;)</value>
      <webElementGuid>5115f72d-f04c-4ab0-9928-9e33cbb8bcf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='SOURCE_GF_d9d0_GF_DDD_L_LBI0T0']</value>
      <webElementGuid>e5403b93-b96c-4412-a257-1ab3f39e9b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='SOURCE_GF_d9d0_GF_DDD_L_LBT']/tr/td</value>
      <webElementGuid>16c1980b-0db2-4e5e-905a-36c21c8cb10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chronic'])[2]/following::td[15]</value>
      <webElementGuid>e4937b9d-6dfd-4e3f-8ed8-5388af0f497f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolved'])[3]/following::td[16]</value>
      <webElementGuid>51a2ae00-11db-4666-9b59-160f4f7a927d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EHR - Dr'])[1]/preceding::td[1]</value>
      <webElementGuid>591e3c70-fa7f-4244-bdfd-d9f04a8f0f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EHR - Tech'])[1]/preceding::td[2]</value>
      <webElementGuid>b9436f7c-5730-4beb-9f44-0218747ad750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr[4]/td[5]/div[2]/div/div/div/div/table/tbody/tr/td/div/div/table[2]/tr/td</value>
      <webElementGuid>3253c3b1-c3ad-40ba-8f0a-8e9b9b03fc8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'SOURCE_GF_d9d0_GF_DDD_L_LBI0T0' and (text() = 'EHR' or . = 'EHR')]</value>
      <webElementGuid>7363abd7-b5b2-4655-aabe-8e13c9ba4caf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
