<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Feels better after washing with cold water</name>
   <tag></tag>
   <elementGuidId>c1ff968a-fd08-414a-a009-a01ad80319d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'MODIFYING_FACTORS_GF_9933_GF_DDD_L_LBI0T0' and (text() = 'Feels better after washing with cold water' or . = 'Feels better after washing with cold water')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MODIFYING_FACTORS_GF_9933_GF_DDD_L_LBI0T0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Feels better when cold compress is applied'])[1]/preceding::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Feels better after washing with cold water&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5d95eb39-f558-41cf-a6b1-6f6486a7d046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MODIFYING_FACTORS_GF_9933_GF_DDD_L_LBI0T0</value>
      <webElementGuid>cafdb756-c7b7-490f-aa5a-2810f9c0361e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_Metropolis dxeListBoxItemHover_Metropolis dxeListBoxItemSelected_Metropolis</value>
      <webElementGuid>c2752f10-526e-44af-a86a-f1b947bff72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Feels better after washing with cold water</value>
      <webElementGuid>50ed90fb-b3da-4dac-8b4b-33d1b8eb3b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MODIFYING_FACTORS_GF_9933_GF_DDD_L_LBI0T0&quot;)</value>
      <webElementGuid>06abec59-2bb8-460a-9531-13a96a4833e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='MODIFYING_FACTORS_GF_9933_GF_DDD_L_LBI0T0']</value>
      <webElementGuid>1a65f5c1-b42c-4c39-b281-1b18ea9de323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='MODIFYING_FACTORS_GF_9933_GF_DDD_L_LBT']/tr/td</value>
      <webElementGuid>4a39cd7f-bd57-4054-b738-5eb7809f43cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Using computer'])[1]/following::td[7]</value>
      <webElementGuid>29ebadaa-7fe5-4876-9f70-57f32b48da61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reading fine print'])[1]/following::td[8]</value>
      <webElementGuid>85f277d6-d269-4720-908b-b98ee98ea127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feels better when cold compress is applied'])[1]/preceding::td[1]</value>
      <webElementGuid>41aca8a8-754e-44e4-8275-b868388f8c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Value List'])[1]/preceding::td[11]</value>
      <webElementGuid>b3986173-34df-4113-9f55-ecfb92715558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Feels better after washing with cold water']/parent::*</value>
      <webElementGuid>269eaa79-650e-4f5f-a77a-3e1ccfb1f5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div[2]/div/div/div/div/table/tbody/tr/td/div/div/table[2]/tr/td</value>
      <webElementGuid>ac45ae22-b41a-499e-a3eb-3c097af66d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'MODIFYING_FACTORS_GF_9933_GF_DDD_L_LBI0T0' and (text() = 'Feels better after washing with cold water' or . = 'Feels better after washing with cold water')]</value>
      <webElementGuid>b0eac43b-fde4-4d62-83e0-f3de40c3d7eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
