<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Loading_STATUS_GF_b04f_GF_B-1</name>
   <tag></tag>
   <elementGuidId>a49c1e6f-e966-4ae4-8c21-665c32470355</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading…'])[2]/following::td[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#STATUS_GF_b04f_GF_B-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#STATUS_GF_b04f_GF_B-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>15365692-4e32-40a2-b850-a3fc2ed88411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>STATUS_GF_b04f_GF_B-1</value>
      <webElementGuid>88cfefc0-41b3-4847-a8f3-77aaf20f93b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeButton dxeButtonEditButton_Metropolis dxeButtonEditButtonHover_Metropolis</value>
      <webElementGuid>bd2d5354-4027-4d77-897c-41fbf656661e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>return ASPx.DDDropDown('STATUS_GF_b04f_GF', event)</value>
      <webElementGuid>dec9110a-429b-4bbd-82f6-83cdb35972f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;STATUS_GF_b04f_GF_B-1&quot;)</value>
      <webElementGuid>f328aa6c-c797-4bfb-a1f8-77e26611a79e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='STATUS_GF_b04f_GF_B-1']</value>
      <webElementGuid>e5970257-865e-4cb5-b553-dc8190a4964b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='STATUS_GF_b04f_GF']/tbody/tr/td[4]</value>
      <webElementGuid>b8f2b7b7-fb41-4349-9607-cfee5994951a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading…'])[2]/following::td[11]</value>
      <webElementGuid>6e61a92d-b3fa-4f62-bdb9-f8b09d5d005b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='alcohol abuse'])[5]/following::td[14]</value>
      <webElementGuid>1afad8d1-e35c-43ad-b802-b80f7f9d2ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/preceding::td[2]</value>
      <webElementGuid>df03788f-d4f2-40d4-831c-a0403f409ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[2]/preceding::td[3]</value>
      <webElementGuid>fdfc8404-d136-4161-b845-88e4e1ed7ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div[2]/table/tbody/tr/td[4]</value>
      <webElementGuid>6d1bbbcb-444a-402d-a588-f28aeee153d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'STATUS_GF_b04f_GF_B-1']</value>
      <webElementGuid>692581e4-5477-4ba4-b5bd-72af6c7ae044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
