<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Loading_DESCRIPTION_GF_b04f_GF_B-100</name>
   <tag></tag>
   <elementGuidId>897de83f-4c21-43e7-b6dc-2b6ffeab810b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='DESCRIPTION_GF_b04f_GF_B-100']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DESCRIPTION_GF_b04f_GF_B-100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#DESCRIPTION_GF_b04f_GF_B-100</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>917a6861-2aba-463c-9765-6ac3876200e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DESCRIPTION_GF_b04f_GF_B-100</value>
      <webElementGuid>48aedd7b-3e85-4808-b732-2825667b95a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeButton dxeButtonEditButton_Metropolis dxeButtonEditClearButton_Metropolis  dxHideContent dxeButtonEditButtonHover_Metropolis</value>
      <webElementGuid>7ac57f40-8ad1-4795-ac63-528b873a6cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>ASPx.BEClear('DESCRIPTION_GF_b04f_GF', event)</value>
      <webElementGuid>ef60714f-b960-43b3-982f-62f096e79cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DESCRIPTION_GF_b04f_GF_B-100&quot;)</value>
      <webElementGuid>a4ada325-83aa-4eb8-b6ba-6f858dd7d7a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='DESCRIPTION_GF_b04f_GF_B-100']</value>
      <webElementGuid>02f369c9-bc3c-4b9d-baeb-cf7bad5862d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DESCRIPTION_GF_b04f_GF']/tbody/tr/td[3]</value>
      <webElementGuid>f7596fe4-a3fc-43a7-b7de-7af0e1fa1249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading…'])[1]/following::td[3]</value>
      <webElementGuid>43f6aab3-350e-4247-83fb-4d3878b98961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data to display'])[5]/following::td[18]</value>
      <webElementGuid>9024a8a3-5a0b-445d-aac2-656621b13cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading…'])[2]/preceding::td[5]</value>
      <webElementGuid>b68d9754-cced-4e82-85d7-344031e43ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='January 2026'])[2]/preceding::td[51]</value>
      <webElementGuid>79769cf3-2653-4cef-a80c-355fc1a34c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[3]</value>
      <webElementGuid>557e530a-f327-4295-876d-d12edcf6aa99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'DESCRIPTION_GF_b04f_GF_B-100']</value>
      <webElementGuid>fc7f6e4a-98bc-460a-b5ce-8576b0f04fb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
