<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Watery</name>
   <tag></tag>
   <elementGuidId>e79e9b78-bbe7-4e3c-98cd-59a829f93b95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ASSOCIATED_SYMPTOMS_GF_9933_GF_DDD_L_LBI2T0' and (text() = 'Watery' or . = 'Watery')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Itchy'])[1]/following::td[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ASSOCIATED_SYMPTOMS_GF_9933_GF_DDD_L_LBI2T0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Watery&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>57ecc04b-739e-4d24-949d-d65aaad4ed85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ASSOCIATED_SYMPTOMS_GF_9933_GF_DDD_L_LBI2T0</value>
      <webElementGuid>3c46615a-8161-4240-86b3-b93b0526693d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_Metropolis dxeListBoxItemHover_Metropolis dxeListBoxItemSelected_Metropolis</value>
      <webElementGuid>85cf5312-d070-415c-9448-a238ed408165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Watery</value>
      <webElementGuid>f6046db1-99f1-4fb9-b0b7-5be9aaa5d569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ASSOCIATED_SYMPTOMS_GF_9933_GF_DDD_L_LBI2T0&quot;)</value>
      <webElementGuid>b8cd24e8-e90a-434e-9745-559568402c87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='ASSOCIATED_SYMPTOMS_GF_9933_GF_DDD_L_LBI2T0']</value>
      <webElementGuid>25f6f3bc-9767-48d3-a4dc-b3cfcb142db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ASSOCIATED_SYMPTOMS_GF_9933_GF_DDD_L_LBT']/tr[3]/td</value>
      <webElementGuid>41859283-5b64-4953-b785-e7f0854f63b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Itchy'])[1]/following::td[1]</value>
      <webElementGuid>e08f4106-0fd1-4d00-9395-519d43b1362f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Irritated'])[1]/following::td[2]</value>
      <webElementGuid>8df7f2c6-3512-47c4-988a-00b98d18f839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Value List'])[1]/preceding::td[4]</value>
      <webElementGuid>2ee78939-c57d-4e54-86b1-d115a21127ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Associated Signs Symptoms'])[1]/preceding::td[4]</value>
      <webElementGuid>1d00fc36-cae1-41a7-9558-a3e23723e037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Watery']/parent::*</value>
      <webElementGuid>5c85cc86-7852-4833-97c4-48a96eebfd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div[2]/div/div/div/div/table/tbody/tr/td/div/div/table[2]/tr[3]/td</value>
      <webElementGuid>084cad2a-80f0-4353-bcc0-95d18c8d2edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'ASSOCIATED_SYMPTOMS_GF_9933_GF_DDD_L_LBI2T0' and (text() = 'Watery' or . = 'Watery')]</value>
      <webElementGuid>180d8825-7829-4512-a430-0ac0cd1fbc3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
