<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Clinic Notes_CLINIC_NOTES</name>
   <tag></tag>
   <elementGuidId>0db4291b-faa1-47fd-aaa8-eabbf393d7c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CLINIC_NOTES</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'CLINIC_NOTES' and @name = 'CLINIC_NOTES']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='CLINIC_NOTES']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#CLINIC_NOTES</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1ae2ddc6-7306-46e0-a8aa-86b891b0949a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>41784e3f-ffa4-4756-8055-8069f67e7b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nochangeevent</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>3639a0b3-3a8b-49e4-bdc8-b99d6107897a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CLINIC_NOTES</value>
      <webElementGuid>a5a172e3-2476-44f8-b201-f1a5758d655b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CLINIC_NOTES</value>
      <webElementGuid>862d6a12-02b3-450b-bfd1-568845144f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3dd1591a-59c6-406f-b83d-7da991e2c880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>769925b6-f770-4131-869f-478437e87deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>5573451b-d725-42e2-b128-a4158d64ee14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CLINIC_NOTES&quot;)</value>
      <webElementGuid>1373fc2b-529c-404f-99ce-aec4b204a460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='CLINIC_NOTES']</value>
      <webElementGuid>5d12df78-ebee-405e-9ed6-c2381910f793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AuxiliaryLabData']/div[3]/div/div/div/div[2]/div[2]/span/textarea</value>
      <webElementGuid>2a7f708a-eafe-4f9c-8e0e-70570f010b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/textarea</value>
      <webElementGuid>d2e3177b-22f1-4b56-b572-1261c498239c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'CLINIC_NOTES' and @name = 'CLINIC_NOTES']</value>
      <webElementGuid>8f677621-2cdf-4a67-8334-b3a1f293c397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
