<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test_Patient_Portal_Scripts</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>guntupallip@first-insight.com;surajp@first-insight.com;vikramk@first-insight.com;</mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>bcd84b46-cd12-491f-b9ee-aa6ded49ec89</testSuiteGuid>
   <testCaseLink>
      <guid>337a981f-1c8c-40f9-8aca-5f41c0be00eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Create_New_Account_Patient_Not_Found_in_MaximEyes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0507723e-71ac-4990-a09d-a9b569c8bba2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0740d97d-ce92-48a2-b8a4-e603758e8f78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f098c879-76c7-47f8-a390-804bd4104e02</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19f2af88-5880-4b20-8be5-f7267970f12c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCForExisting_Patient_Match_Full _Account_Activation_Flow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6532e98f-82ac-4e2b-bac4-8aa3f1d86e47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCForPatient_Signup_for_Patient_Portal_From_Maximeyes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5b8af681-d445-4494-99a3-389a5994e448</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_PatientOpt_Out_From_Maximeyes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1522792d-187d-4274-b993-38d04020521f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd023fc9-34de-4704-810d-c4c2ad57de94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0740b80d-6715-47fd-a6d2-0c3eb741af97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8064052-1b8c-49b6-a0f7-407e59af16d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce49d235-123b-4d70-82bd-9f800b22def1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c119bca-3f1a-421b-8116-807b5b089ca3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31ae0d43-0331-47f1-a4ad-ff39153445a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff65c050-aeed-43b9-9c6a-bdc7a785c984</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a812a09e-d557-4afd-88a3-5611311e8108</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0d44638-9f5c-4a78-b7cb-f5258c2c3a49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Patient_Reset_Password_Flow_from_Email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac8e2d22-ad76-404d-abbf-e48604fcec34</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fdc1d9f8-5421-43fb-9536-e50465360281</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Patient_Reset_Password_Flow_from_Maximeyes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e6c8666-6a41-400f-bf69-481c9ef3a25f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae1419c4-2e3c-4b8b-a95d-57cc20c851f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_No_Insurance_Card_Checkbox_Functionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d88f3610-ccbb-4bcf-9e5a-26c572c80416</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Locking_Account_After_Three_Attempts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7a633cc-f91d-402d-b3a5-a353b42265e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>096567ae-8e96-4830-be77-d1ffcbd71de0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b29a864-400d-4adb-8648-274d7ba97d26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>670564d3-bcf3-4235-9e7b-fb9e773691af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e78fa1e8-0fff-4ee2-b3bc-e899e62e7587</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>492557a6-68ae-4e87-ac50-24e46b9257e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Update_Demographics_Work_Flow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cbb395c-5a42-4c85-931a-692c812fdb25</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3b0db9f-c78c-4f1b-b664-0af6dadf3a86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Messages_WorkFlow_in_Patient_Portal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35ff2831-f330-4813-bd26-61886bdd7dea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52b07031-c559-4a27-b9f0-8bed1387096b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73f6c93c-9190-462f-a6ff-45801caf3053</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f04a4e3-e91b-4149-8333-9c82881b88ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10ee969e-8170-4e42-9fe0-aece6dc21ba5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>393d41b8-fd97-4f79-b14d-ca4358bafa40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Health_Summary_Flow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bad06aa-59dc-4382-882c-fd509ec0c841</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>80307571-c48a-4245-9f2f-72c516652b45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Den_Num_Count_MIPS</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>fd7362dd-58c7-44d3-8b3e-08f93ff3522f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Activity_Logs_on_Patient_Portal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0389224a-986f-42a6-8359-54bd7acd9479</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3456f715-3cb8-491a-9c37-d16dd83d36fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Update_Insurance_Work_Flow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e48e93bb-66d8-4576-9470-3abf8d567b8e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10109ac8-2bf1-45cc-a0b5-8cb2aeb23b5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Verify_Active_User_Not_Logged_Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>061e1cec-d68b-4da5-8d55-a9167af6b74f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b544882a-056c-412a-b15d-eddb68efc6f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Maximeyes_To_Patient_Portal_Data_Sync</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>505c105f-d75b-46af-8db7-c4cbaed428cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>de3c3a2d-b87c-431e-8633-9ef89deb647b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Forgot_Username_Patient_Portal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>95c63e95-d95f-4ad5-8a91-ca2ca4adb1b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Forgot_Password_Patient_Portal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6e4a996c-0752-49ec-bc52-8f76dd7c95b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Health_Summary_Enc_Sign_Off</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>697dcb4c-2c7f-4643-ba66-a25e54ddc38c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PatientPortal/TCFor_Patient_Profile_Verification_on_Patient_Portal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b0674ac-e232-422c-8647-4994de2756e3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
