<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Security code digit 1 of 4</name>
   <tag></tag>
   <elementGuidId>a26a5f08-c942-45f7-830d-74468835fb71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.position-relative:nth-child(1) [aria-describedby=&quot;otp-instructions&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' position-relative ') and (name() = 'div') and (position() = 1)]//*[@aria-describedby = 'otp-instructions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Security code digit 1 of 4&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25987a16-b4b2-4d6b-bad7-37a7fd3ab9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp-0</value>
      <webElementGuid>560ce58a-4240-4f5d-8506-d0a6e78c94ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3c94009-ea10-4e01-950f-7689da04b3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>085edfed-85a8-488d-8b79-5c3f72f73f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-center fs-4 fs-md-3 border-2 rounded me-2 border-secondary</value>
      <webElementGuid>3510f3e5-d8b8-412d-ae87-c121674d540c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>otp-instructions</value>
      <webElementGuid>eec33540-e6ba-4952-8207-39b2c7618112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>190536f4-1e15-4023-b9c1-f06bb967eb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>780d935b-c8f2-4296-93b8-d92d02a6efdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1ed1f031ba1d53b0b245536971dd1a16</value>
      <webElementGuid>ca34447b-270d-400b-bbb8-f000d41479bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' position-relative ') and (name() = 'div') and (position() = 1)]//*[@aria-describedby = 'otp-instructions']</value>
      <webElementGuid>3e75907b-c00e-4b61-912c-1e00196b0329</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' position-relative ') and (name() = 'div') and (position() = 1)]//*[@aria-describedby = 'otp-instructions']</value>
      <webElementGuid>f505f1a0-603d-4f11-b534-630a704a5e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otp-0' and @type = 'text']</value>
      <webElementGuid>abffddf8-5a33-444a-8c81-46c4414fc780</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
