<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I Accept</name>
   <tag></tag>
   <elementGuidId>168998ae-a574-4814-82bd-0532def8ccf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acceptTerms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'acceptTerms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;I Accept&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcdcc4a6-db2f-460c-aafd-3df130e93b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>680e9653-680e-4981-b1f9-e9dc0efd378d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptTerms</value>
      <webElementGuid>f010197e-0c23-468f-a4e7-16a3a8cd882c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>cabbaa39-5c1b-4598-8a22-c9f5ac114e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0c4d78405f12bf4b97758c47c559c800</value>
      <webElementGuid>3ea6a013-b8fd-42ff-8db7-4780364b7856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'acceptTerms']</value>
      <webElementGuid>9cb95750-8012-4006-821e-2a2cefe33a0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'acceptTerms']</value>
      <webElementGuid>321326f2-cd50-4902-8b9a-99e5fb552c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'acceptTerms']</value>
      <webElementGuid>ffb4e8f9-fd11-4ee6-a36c-615d2b9d81b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
