<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CLOSE</name>
   <tag></tag>
   <elementGuidId>2ad8ebb6-3461-4b47-87fd-3421b38012cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div[2]/div/div[2]/div[2]/div[3]/div/div/div[2]/div[4]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;CLOSE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16c35a87-f318-4d7d-abd9-b3bee0ac622e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-0 hover:underline-black</value>
      <webElementGuid>d06f22f0-0081-48d3-9bab-bcba1872842e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CLOSE</value>
      <webElementGuid>27412812-1b8e-4b24-8d6a-d37bec79812d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen flex flex-col w-screen&quot;]/div[@class=&quot;flex-1 container mx-auto px-4 py-8&quot;]/div[@class=&quot;flex gap-8 mb-8&quot;]/div[@class=&quot;w-1/2 space-y-3&quot;]/div[@class=&quot;bg-white p-3&quot;]/div[@class=&quot;flex items-center justify-between&quot;]/div[@class=&quot;relative z-999&quot;]/div[@class=&quot;fixed inset-0 flex items-center justify-center z-10&quot;]/div[@class=&quot;bg-white rounded-3xl shadow-2xl&quot;]/div[@class=&quot;flex max-w-md overflow-hidden border-none rounded-2xl&quot;]/div[@class=&quot;bg-white w-full p-4&quot;]/div[@class=&quot;flex justify-end gap-4 mt-4 text-sm font-medium text-primary&quot;]/button[@class=&quot;border-0 hover:underline-black&quot;]</value>
      <webElementGuid>c1995354-0bab-4b0c-97f5-ad61e0bc8de8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div[2]/div/div[2]/div[2]/div[3]/div/div/div[2]/div[4]/button</value>
      <webElementGuid>69cf10a8-d88e-4c49-bbae-dd8f15f794cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::button[29]</value>
      <webElementGuid>b088b363-753d-445d-8e62-740230451d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::button[29]</value>
      <webElementGuid>16cc4250-bf04-49df-8ea5-b894da99558b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAVE'])[1]/preceding::button[1]</value>
      <webElementGuid>a41e82b7-79bc-47dd-a67b-289e6d54f32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permissions for Health Summary'])[1]/preceding::button[2]</value>
      <webElementGuid>f91c4e17-c973-4d82-b2d7-a544b9a52ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CLOSE']/parent::*</value>
      <webElementGuid>8583e409-eb9b-4a78-90a3-7ba7cba077e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>1dd30390-39f6-4503-ac98-83153e1abeaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'CLOSE' or . = 'CLOSE')]</value>
      <webElementGuid>45ad8431-8743-4fa7-a6d9-a119e9145e3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
