<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_02_18_2026</name>
   <tag></tag>
   <elementGuidId>0e4c80ae-4f46-4c96-a249-9444440bd93e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='MM/DD/YYYY']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;02/18/2026&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c05a3e9a-6119-4cb3-9980-d0c9c20e51c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border px-4 py-2</value>
      <webElementGuid>60b6b51f-080f-4975-bc9c-b990dd3541f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>02/18/2026</value>
      <webElementGuid>a35eb928-8183-49af-8bc4-1558ed448d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6ec7f9c33573c16d1d1909a51fa07f7a</value>
      <webElementGuid>40274903-b3d7-429d-a601-f58ddfd4d3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'td') and (position() = 2)]</value>
      <webElementGuid>c15bd6cc-5c88-4a4b-bf9c-eb7af2d0351b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@placeholder='MM/DD/YYYY']</value>
      <webElementGuid>13b5b37c-c6e4-4e18-a56d-ba2e368ae762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/main/form/div[5]/div/div/input</value>
      <webElementGuid>92c74a42-a883-4092-a928-ac60670ae0c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
