<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Reason</name>
   <tag></tag>
   <elementGuidId>07dbda29-6a3c-437e-ad7c-9c6d00fbb075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reason</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'reason']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Reason&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>80e53b9b-4525-42da-8d51-6d5538d1a775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-1  rounded </value>
      <webElementGuid>1a3d3bd9-9492-4a71-95da-bbda7aa43b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c9cd3f3e-301a-4165-a265-7807100aefa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>9674af85-b142-4ec8-97c2-bdfa9f2a7b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4db3c93c32f5da60da5bb0d5ce718aac</value>
      <webElementGuid>e946efb1-e605-4704-ae69-665f69adfece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'reason']</value>
      <webElementGuid>cc5d495a-a85c-42c0-809a-3b27a7583310</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'reason']</value>
      <webElementGuid>c82a9b5b-2d9e-4550-9c07-b541ba81034a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'reason']</value>
      <webElementGuid>ce44c2d5-6562-438b-bcdb-b73dce43a995</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
