<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Proceed on cancelled appt page</name>
   <tag></tag>
   <elementGuidId>cdc0685c-544e-4725-a9ce-9c8b87944c6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Proceed&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc841c02-a6c5-4db7-9294-85334049c8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary position-relative align-items-center btn-md rounded bg-blue-500 text-white text-lg px-5 py-2 rounded w-100 hover:bg-blue-600 transition</value>
      <webElementGuid>d99ac06a-2c75-40be-a9ff-7af4f8a57618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f69b3352-59de-4b3f-b2c5-d07fbbf893c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed</value>
      <webElementGuid>60fea0e3-f4aa-450d-aff1-bfd38e15e255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid min-vh-100 min-vw-100 p-0&quot;]/main[@class=&quot;row g-0 min-vh-100 flex-column flex-md-row&quot;]/section[@class=&quot;col-12 col-md-8 d-flex flex-column justify-content-center align-items-center align-items-md-start text-center text-md-start p-4 p-md-5 bg-white&quot;]/div[@class=&quot;d-flex flex-column flex-sm-row gap-3 w-50 w-md-50&quot;]/button[@class=&quot;btn btn-primary position-relative align-items-center btn-md rounded bg-blue-500 text-white text-lg px-5 py-2 rounded w-100 hover:bg-blue-600 transition&quot;]</value>
      <webElementGuid>29b67d36-d647-44fc-9845-881633d56c30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>fec071e2-5154-4d31-bffc-526fca1d891d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/section[2]/div[2]/button</value>
      <webElementGuid>5386db4c-c4f4-4e0d-8db8-d2c6ab5e21d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule New Appointment'])[1]/following::button[1]</value>
      <webElementGuid>1899b0df-7cad-48ad-9c85-7495ee99b405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Appointment is canceled'])[1]/following::button[1]</value>
      <webElementGuid>66f269a2-be80-4f0a-b8a3-839299aee8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version: 1.0'])[1]/preceding::button[1]</value>
      <webElementGuid>830b8a66-92af-4dc7-8b2f-27b907685b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>b3bf9e13-7b42-43ff-9908-ef64df1b182a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Proceed' or . = 'Proceed')]</value>
      <webElementGuid>a2bcded1-538b-475e-866a-f8a3cbba9993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
