<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Reschedule on appt page</name>
   <tag></tag>
   <elementGuidId>b06228bd-006e-473f-a498-15c65d6ef162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Reschedule&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9be2098-e891-46c3-8168-86da09298872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8d72902b-e38e-48d7-8871-8714bb0ba2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>appointment-upcoming-action-link</value>
      <webElementGuid>6e327344-c94e-424c-a57c-1d756e80abb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reschedule</value>
      <webElementGuid>a72544e0-fb7a-4cd3-9390-7313e2c20cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;appointment-page-layout&quot;]/main[@class=&quot;appointment-page-main&quot;]/div[@class=&quot;appointment-desktop-columns&quot;]/section[@class=&quot;appointment-upcoming-panel bg-gray-50 sidebar-pagination-host relative flex flex-col min-h-0 overflow-hidden&quot;]/section[@class=&quot;appointment-upcoming-scroll-area overflow-y-auto flex-1 min-h-0 p-6&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;mb-4 p-4 bg-white border-b border-gray-500 relative&quot;]/div[@class=&quot;absolute bottom-2 right-4 flex gap-2&quot;]/button[@class=&quot;appointment-upcoming-action-link&quot;]</value>
      <webElementGuid>2a58d376-6c89-4bb9-8617-8a9b618ffc01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>8d33bb64-a4a0-4841-91c6-0bf193b49168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/section/div/div/div[2]/button[2]</value>
      <webElementGuid>6d2642ca-abd0-4ab8-9a72-e0c7342f0a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>a7c7eace-8a04-401d-9eac-9643cceef67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmed'])[1]/following::button[2]</value>
      <webElementGuid>5a20888f-1238-486b-89b9-188023b46e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version: 1.0'])[1]/preceding::button[1]</value>
      <webElementGuid>aa4f829f-453b-4220-adeb-b5e39068703d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reschedule']/parent::*</value>
      <webElementGuid>d9d7648f-f2ac-4aff-9169-93eec4a7d4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>478b384d-151c-47da-9767-f57fa4585997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Reschedule' or . = 'Reschedule')]</value>
      <webElementGuid>34b7932f-db14-4ac2-9114-408f51e63baa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
