<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Electronic Files_encTabList_17</name>
   <tag></tag>
   <elementGuidId>201f92f5-63dc-4eb1-80f7-0538ff955c48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#encTabList_17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='encTabList_17']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Drawing&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c4f9574-c38e-49f1-8423-31e61754f7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>Element</value>
      <webElementGuid>a5c0f7e7-9a22-4b88-b0dd-b6559d259906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Drawing</value>
      <webElementGuid>0a5e0edb-773f-470e-8432-15ad5c13d621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Drawing</value>
      <webElementGuid>bc98546a-bb79-4308-86b7-d4fe7b673243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncateWord ui-tabs-anchor</value>
      <webElementGuid>48429b3b-6624-4f47-b41c-cc6f3533623b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#encounterform-6241434</value>
      <webElementGuid>edad5000-862d-4093-986e-6a665ff2b484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>encTabList_17</value>
      <webElementGuid>22594ed0-eff1-4359-aecd-c0f169f2891c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>2b2c9790-71fb-410a-9e1b-e0b5317b1cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2b3cfbe8-229b-4aa7-80b0-332e5eb9d931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Drawing
</value>
      <webElementGuid>8e9d40e0-ec8c-4976-9b8e-38ec4613bbf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;encTabList_17&quot;)</value>
      <webElementGuid>406eaee7-1cdc-47cb-ac50-18e753c74fce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='encTabList_17']</value>
      <webElementGuid>7d7a142b-5a2a-426c-995f-8bb4ceb86d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainpageul']/li[19]/a</value>
      <webElementGuid>a4088717-c7da-4765-b214-2cbd3b928440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Drawing')]</value>
      <webElementGuid>76330813-5936-4760-b68d-0e812d6b5380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Electronic Files'])[2]/following::a[1]</value>
      <webElementGuid>23d2d942-3e41-49a2-a69c-5154e2492526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surgery'])[1]/following::a[2]</value>
      <webElementGuid>982d9834-23f7-477e-ad37-da99341fd8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encounter Summary'])[1]/preceding::a[1]</value>
      <webElementGuid>dacdb8d6-d3f7-4ac9-b763-9f0033d54841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinical Information Reconciliation'])[1]/preceding::a[2]</value>
      <webElementGuid>4774b10a-7431-4972-bded-5b61f9a502ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Drawing']/parent::*</value>
      <webElementGuid>45378949-02f7-4f62-9150-11ce85eb6cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#encounterform-6241434')]</value>
      <webElementGuid>3014fb2b-f5a2-454d-94d8-f328e0b7d6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[19]/a</value>
      <webElementGuid>425a4348-eee6-4d98-9e30-519270c5f8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'Drawing' and @title = 'Drawing' and @href = '#encounterform-6241434' and @id = 'encTabList_17' and (text() = '
Drawing
' or . = '
Drawing
')]</value>
      <webElementGuid>1bc7656f-9906-4785-90ed-347a13b93fcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
