<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Appt Time 8 45 AM</name>
   <tag></tag>
   <elementGuidId>39151770-6484-45b9-8e07-5a2ea9d2361d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scheduler_containerBlock_DXCntv0_21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='scheduler_containerBlock_DXCntv0_21']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#scheduler_containerBlock_DXCntv0_21</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b6d244a6-c043-4587-aaa8-c990c5dc2633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scheduler_containerBlock_DXCntv0_21</value>
      <webElementGuid>c356d48f-3302-4838-9233-8e4cff088b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxscTimeCellBody_Metropolis dxsc-time-cell-body</value>
      <webElementGuid>71ce3dab-7e5a-4257-bdec-06caec413860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>1f862e22-b8ed-4956-b73e-86cf8e56be21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scheduler_containerBlock_DXCntv0_21&quot;)</value>
      <webElementGuid>d955adc3-ea5c-41af-8e69-d6027b110d4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='scheduler_containerBlock_DXCntv0_21']</value>
      <webElementGuid>c5ec9384-b814-4d23-9c2d-ecdc7f7662e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='scheduler_containerBlock_vertTable']/tbody/tr[22]/td[2]</value>
      <webElementGuid>226c55dd-c871-4149-bacf-2717af64fa91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tuesday, November 18'])[1]/following::td[48]</value>
      <webElementGuid>258b4f21-8767-4256-9251-8331edba9d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dr. Ashley_Cole'])[3]/following::td[50]</value>
      <webElementGuid>ada3d171-071d-4041-b92a-9381e4b52102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PM'])[1]/preceding::td[56]</value>
      <webElementGuid>fb2194dd-0853-43e9-b986-e6e7501982bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Deom (26yo) | CL FIT | Pend. Conf.'])[1]/preceding::td[233]</value>
      <webElementGuid>fa3bd7ac-4995-4a86-8c6b-bcb0a80b6f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/table/tbody/tr[22]/td[2]</value>
      <webElementGuid>8b05ec1e-4b56-4e4e-96ef-75e29e8f88b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'scheduler_containerBlock_DXCntv0_21' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>d3afacfa-d578-44a0-a0d7-764fc74f0733</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
