<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CLEAR_searchICD10Codes (1)</name>
   <tag></tag>
   <elementGuidId>6276352a-2aa7-4679-9eda-577462e3cfcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchICD10Codes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='searchICD10Codes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;GO&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>893adf65-bb98-49ef-a96a-a5cf9eba3b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary med-small-button </value>
      <webElementGuid>f0852c88-b9a2-420d-bc42-a74206caa30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search Diagnosis Code</value>
      <webElementGuid>9af87fd3-ce82-4d9e-9940-97a34e749d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchICD10Codes</value>
      <webElementGuid>7e8c068d-60ba-480e-af32-643311aaa812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:triggerICD10(textbox.value,'search')</value>
      <webElementGuid>3d6257db-0f58-407c-9376-3800d0a5c652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GO</value>
      <webElementGuid>807445f8-39cb-4011-89e1-17f09c4c25c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divImoSearchScreen&quot;)/div[@class=&quot;fluid grid box_background FPPopupMargin&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;span3 pad5&quot;]/div[@class=&quot;fluid grid no-margin&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;span11 pad05&quot;]/span[@class=&quot;input-control  default-style&quot;]/button[@id=&quot;searchICD10Codes&quot;]</value>
      <webElementGuid>f8c9e6f6-9b2e-4497-a790-bf6e79e49b4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='searchICD10Codes']</value>
      <webElementGuid>3d09beb5-601a-48d4-825d-dd3d5eb6b0d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divImoSearchScreen']/div/div/div/div/div[3]/div/span/button[2]</value>
      <webElementGuid>3e328e47-717e-4ecf-9711-ed225128de0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLEAR'])[1]/following::button[1]</value>
      <webElementGuid>897aec92-d3b0-42c3-a012-c7d09c3cfa86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[6]/preceding::button[1]</value>
      <webElementGuid>590472b6-2873-42ac-bcb7-5aa649facbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GO']/parent::*</value>
      <webElementGuid>c7dfdc42-749f-43df-90c5-e66ce68090d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/button[2]</value>
      <webElementGuid>8c551f90-fb1e-40a2-8752-9b7792a445a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Search Diagnosis Code' and @id = 'searchICD10Codes' and (text() = 'GO' or . = 'GO')]</value>
      <webElementGuid>67b4734f-7ce4-4126-a9d6-33d7f39bbd4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
