<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Download Data into MaximEyes</name>
   <tag></tag>
   <elementGuidId>1aa39714-7153-41c7-a8cd-b8369ff442f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RcopiaWebBrowserOK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RcopiaWebBrowserOK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Download Data into MaximEyes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff4df966-1d0d-456c-b563-ffd12bf9782b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary small-button padButtonLR</value>
      <webElementGuid>7264d836-77f3-4ded-a9f4-a1ab6e4b758b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6dd39734-6b93-40f3-b238-bc535ca7f971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RcopiaWebBrowserOK</value>
      <webElementGuid>745fa3b1-66c1-4454-ad4e-e1881cc35400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Download Data into MaximEyes</value>
      <webElementGuid>83c8ecce-0edf-4a95-b2b6-989a417a1f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Download Data into MaximEyes</value>
      <webElementGuid>9eadfc78-9785-4946-9b38-fd6eee8f7817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript: DownLoadDataFromRcopia(this, event)</value>
      <webElementGuid>0b572969-fc1e-461e-82b1-ab2a5891894c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RcopiaWebBrowserOK&quot;)</value>
      <webElementGuid>9633198b-1081-4d61-8d4d-77a07233b732</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RcopiaWebBrowserOK']</value>
      <webElementGuid>c3c03e11-2ec1-431d-8169-b6a6d944df3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='18b7d']/div/div[2]/div/div[2]/div/div/input[2]</value>
      <webElementGuid>39bcc4ee-6cf4-4702-9276-c50d7e4248d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input[2]</value>
      <webElementGuid>c4b380e1-76d1-4e3f-a254-1755fe347f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'RcopiaWebBrowserOK' and @title = 'Download Data into MaximEyes']</value>
      <webElementGuid>4b834fe2-564e-4dda-a332-c9fd7dff612b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
