<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Electronic Files</name>
   <tag></tag>
   <elementGuidId>4b3e1d5e-5209-462a-a9de-67427b7ae49c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href=&quot;#Electronic-Files&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Electronic Files&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>629ed0e5-54c5-499e-8e14-210737209cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Electronic-Files</value>
      <webElementGuid>01a0d5d8-d2a3-42db-a613-b4910d30b2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectorForGoogleAnalytics ui-tabs-anchor</value>
      <webElementGuid>a1b3e5ca-9b51-4b1c-b21a-2dd38f4bfd24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ValidationForPatientSubModules(event)</value>
      <webElementGuid>cb664c45-518a-40d7-9ba9-8588917c13ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>a262d132-2227-420b-93e9-d70aefa61fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bc7fbdef-1dc9-4516-abd9-fcc29a6a25db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-13</value>
      <webElementGuid>84f9bc79-aec0-487f-a35f-e9ac9d865ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Electronic Files</value>
      <webElementGuid>fb7fb034-70fa-4350-a00a-40d6768b7e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-13&quot;)</value>
      <webElementGuid>d0a83308-42d0-4e2a-990f-b7299a556d9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-13']</value>
      <webElementGuid>189edb4a-5050-4d75-a743-00172a10a528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ElectronicFilesTabLink']/a</value>
      <webElementGuid>d72499cc-5aed-48f1-90ef-a80493984868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Electronic Files')])[2]</value>
      <webElementGuid>cf819959-a59f-43a9-bdb3-1b18ed88616d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome Form'])[2]/following::a[1]</value>
      <webElementGuid>93ba3632-19a6-4cca-b132-2f230825eec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insurance'])[2]/following::a[2]</value>
      <webElementGuid>990b6120-d8df-490b-824d-553d68772719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rahul Test'])[1]/preceding::a[1]</value>
      <webElementGuid>b85b41f0-b115-4285-912e-a582002d2ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#Electronic-Files')]</value>
      <webElementGuid>e6d8bf27-79fa-49ee-97a7-929e7b1fa101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/ul/li[5]/a</value>
      <webElementGuid>07ee3b18-393c-4277-b9de-125c61f8418b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#Electronic-Files' and @id = 'ui-id-13' and (text() = 'Electronic Files' or . = 'Electronic Files')]</value>
      <webElementGuid>25fad4ef-c6d8-4375-ab23-add6f739bc44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
