<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OD_ADD2_OD</name>
   <tag></tag>
   <elementGuidId>740f2eb2-fe52-4398-bdbb-0311bbe2b322</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ADD2_OD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ADD2_OD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;ADD2_OD&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4a9da79-c1e4-436d-b038-3d2e5c39c21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-call-from</name>
      <type>Main</type>
      <value>addOpticalRX</value>
      <webElementGuid>3244389e-55cc-4f8b-bbde-d597c905bd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec-valuelistname</name>
      <type>Main</type>
      <value>Refraction_Add</value>
      <webElementGuid>40eb87dd-ce8c-4651-88e5-99fafded35b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field-attribute</name>
      <type>Main</type>
      <value>ADD2_OD</value>
      <webElementGuid>ecd3d1da-32b8-49d6-92d8-9371ab52b0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ADD2_OD</value>
      <webElementGuid>ca730d52-ed3d-4e7f-a2a5-0fa61f1915d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ADD2_OD</value>
      <webElementGuid>986d851a-1cea-40d7-8456-87949ace37a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be8d933d-e7b5-4a25-82bc-2fb58343e12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dc680d4a-1d5d-4e38-b620-f89b6a64681b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec_valuelistname</name>
      <type>Main</type>
      <value>Refraction_Add</value>
      <webElementGuid>93c385f6-0074-4598-a47e-fb362bde001f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>2ec97077-a011-40c9-b5da-90e24481054e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>7c71eeca-ebf5-4215-b8e8-8d1e3548749b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ADD2_OD&quot;)</value>
      <webElementGuid>3266b2fa-f802-443c-817d-174e1d195fee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ADD2_OD']</value>
      <webElementGuid>df3b9c76-ffe0-4bd2-a238-80dbf40d0012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ODDATA']/td[8]/input</value>
      <webElementGuid>1836d049-28ab-4c2d-9857-cc891a89ec2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>45bcef43-cb8e-4fe9-89a0-e88d931e6b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ADD2_OD' and @name = 'ADD2_OD' and @type = 'text']</value>
      <webElementGuid>5bc6996d-a2e4-4ae4-940b-fbf74cbae0d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
