<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CA_CreateNew</name>
   <tag></tag>
   <elementGuidId>153c6170-5a78-4a0b-8d49-efcfa48f8174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CreateNew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CreateNew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add New&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae01b245-53fa-448c-9b6b-80aa8acd1202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5c5e1efb-e82f-4003-a476-717fce95947e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add New</value>
      <webElementGuid>d141dfe1-9938-4c0f-9faa-374329a18ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CreateNew</value>
      <webElementGuid>a8a8f201-a484-4b5d-9b34-cd9ac28aec96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SavePatientPopUp(this)</value>
      <webElementGuid>5f2cb492-356d-4b95-b45a-a8e9d04fdae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary small-button padButtonLR</value>
      <webElementGuid>3d55d048-0d91-4bf6-bfa6-c1e33c8bda30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CreateNew&quot;)</value>
      <webElementGuid>46bcd1cf-67f8-4c49-933f-fec6a5118c86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CreateNew']</value>
      <webElementGuid>47146330-2e68-41c4-9cf6-f7529fc899c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='validatePatient']/div[2]/div/div/input</value>
      <webElementGuid>4c4215f5-09ff-4fd3-9883-e57924049e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>273d4eec-93e7-4c13-b726-05650ae50684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'CreateNew']</value>
      <webElementGuid>7e998715-481e-4321-b5c9-e12ac60ea2dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
