<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Preferred Facility_AddNewPatientPopup_adb9ef</name>
   <tag></tag>
   <elementGuidId>3339adf6-7b8c-4e18-8e4b-0820fc0e10c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddNewPatientPopupFacility_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddNewPatientPopupFacility_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AddNewPatientPopupFacility_I</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8efe3f1c-88d8-49f4-949f-c35a98dfd408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Metropolis dxeEditAreaSys dxh0 valid</value>
      <webElementGuid>327d0cb0-40d3-4935-9d12-a661967e7581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddNewPatientPopupFacility_I</value>
      <webElementGuid>104801e3-5036-4a7f-953e-23bbdb1f1eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddNewPatientPopupFacility</value>
      <webElementGuid>0cfea2ae-afc9-4f4f-bc8f-435efb6221eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('AddNewPatientPopupFacility')</value>
      <webElementGuid>82839f16-abd9-43b7-acad-1fbc1f9e2ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('AddNewPatientPopupFacility')</value>
      <webElementGuid>ba01a37f-d064-499c-9e9b-d7d7e945728b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.ETextChanged('AddNewPatientPopupFacility')</value>
      <webElementGuid>909a21a7-bc36-40a8-a7e1-212bda8c0768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>dc3082b7-f9bc-48f2-9747-a83058bb7047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0615c9a8-9139-4d7f-9af0-0a394158d9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>1605dcfd-095e-43e2-ab79-189a1a4406fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>46609f8b-1d7a-4bfa-b64c-dc984ca7ba4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>AddNewPatientPopupFacility_I-error</value>
      <webElementGuid>9b25dca9-957a-4e2b-857d-378d5f6896df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cf48fd87-9410-4ded-9b49-0bd79ec6f1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddNewPatientPopupFacility_I&quot;)</value>
      <webElementGuid>dc4d129b-b635-4009-8538-9e1934a87bcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddNewPatientPopupFacility_I']</value>
      <webElementGuid>c9e3668b-efab-44c8-bdeb-db57a32e1a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='AddNewPatientPopupFacility']/tbody/tr/td[2]/input</value>
      <webElementGuid>f6fb945a-2354-4ec7-b41c-26adc4fba401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>79fd3613-8162-453d-96b5-680284fb61ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddNewPatientPopupFacility_I' and @name = 'AddNewPatientPopupFacility' and @type = 'text']</value>
      <webElementGuid>71c4d158-6d3e-4f98-8c1f-5828e96aa7b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
