<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_AddNew_Patient_LastName (1)</name>
   <tag></tag>
   <elementGuidId>15c4f0b5-2b6e-4179-bff9-6493619d24b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddNew_Patient_LastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddNew_Patient_LastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AddNew_Patient_LastName</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b75fecf4-032f-4d7e-abb7-551d750439f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddNew_Patient_LastName</value>
      <webElementGuid>5b3cea57-2115-4ed9-b4db-3a6f1e8bc77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>propname</name>
      <type>Main</type>
      <value>LastName</value>
      <webElementGuid>469e29fc-b6fa-47b4-ae2a-4ebc81ef3aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>bc1e2025-c2a5-4c6e-818b-88e699e3e3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>LastName</value>
      <webElementGuid>199c40a6-4234-4ead-80fe-f2db27894ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~AddNewPatient.PatientInfo.PatientDetail.LastName</value>
      <webElementGuid>89c19e86-c152-4eeb-9221-2ef2f8004047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>STRING</value>
      <webElementGuid>49b096f9-7a51-4708-b749-0cd0171f5909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>PatientDetail</value>
      <webElementGuid>6468f4de-2890-4f8d-bc85-aefaa84d300b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error-message</name>
      <type>Main</type>
      <value>Last Name is required </value>
      <webElementGuid>a61f5c12-f3fd-443c-9417-a12150376e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>18135562-0fa8-4d52-ad47-30ecf86ca54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>Last Name length can't be more than 200.</value>
      <webElementGuid>c144688d-a93a-4985-ba6e-607241f8c97e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>69d1ae9a-48a9-4197-8975-dfec8288774f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>You must enter a Last name.</value>
      <webElementGuid>68fbb5f4-655f-4359-92aa-9a8229160b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>9d1be28d-895f-41cc-8ce3-bbbf2df6078b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addNewPatient.patientDetails.LastName</value>
      <webElementGuid>419a75cb-ee21-47c8-9387-e60b50f1ab6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OnDataChanged(this)</value>
      <webElementGuid>7c5fa2ec-99a1-4026-815f-986db2211a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f43bfa2-2904-4da4-a46b-fd65229d9db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>2f84b7bc-584b-430e-9817-c9257306c8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-validation-error</value>
      <webElementGuid>0558bb92-b047-4b5f-b78f-5bf782628a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>AddNew_Patient_LastName-error</value>
      <webElementGuid>3b012927-e576-45a6-9eaf-11a27eb00262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>776eccae-b3e9-47af-aad1-c03162fb1769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddNew_Patient_LastName&quot;)</value>
      <webElementGuid>6c27f2e2-1bef-451e-bfbf-78f03af97992</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddNew_Patient_LastName']</value>
      <webElementGuid>b6b0e42a-6954-48be-8744-7f8b2a8dfc14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewPtDetails']/div/div/div/div/div[2]/div/div/div/div[4]/input</value>
      <webElementGuid>79304434-3420-424e-95be-f1e709277c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[4]/input</value>
      <webElementGuid>82678c7d-48bc-40cb-a140-f3863bc79b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddNew_Patient_LastName' and @name = 'addNewPatient.patientDetails.LastName' and @type = 'text']</value>
      <webElementGuid>1de76302-93e4-4fdf-858e-428d86133d9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
