<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Primary_PR_EMAIL_undefined (1)</name>
   <tag></tag>
   <elementGuidId>ec5d8416-e903-48d3-b8da-87964a7629af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PR_EMAIL_undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PR_EMAIL_undefined']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PR_EMAIL_undefined</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7336e9d8-9a50-4c1a-88c9-b36e9f6edf3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid input-validation-error</value>
      <webElementGuid>27dde836-7a62-4837-ab51-74b2826bdce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-commtype</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>46044c47-e8b2-475b-abde-d238416ee1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>Value</value>
      <webElementGuid>221de35d-0f0e-44fb-a5ad-35c269b4689b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>EmailPhone</value>
      <webElementGuid>ccd9e22a-d634-4562-a00b-f0b7885f80da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PR_EMAIL_undefined</value>
      <webElementGuid>40a74d3f-b8bf-4a56-ab3e-6b28353c6cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Value</value>
      <webElementGuid>be299f07-0457-4b10-a9c2-1a445c2e3452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>DuplicateValidation(this)</value>
      <webElementGuid>bbf14030-1dfd-4a40-bcb7-30f5015b921c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca03b589-ff13-430e-9e1d-decb3cb635d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>87e12ba4-5ea3-4fd2-9d48-b412e74524bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>241bdab3-6bdc-4858-a84c-8604b7e6a884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data_commtype</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>e0856176-cb67-4161-ac2f-b963efd3d148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-dependentproperty</name>
      <type>Main</type>
      <value>PatientInfo_IsEmailRequired</value>
      <webElementGuid>3e5e3052-8562-419e-b6e3-0cfc5456b14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-email</name>
      <type>Main</type>
      <value>Email is not valid</value>
      <webElementGuid>e4d2cb9d-ba57-410c-909a-23c8cc8fe71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>PR_EMAIL_undefined-error</value>
      <webElementGuid>107857aa-5c8b-41ca-8720-ce1ee00da1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>df5f3037-a048-4582-a107-0f38466ddcf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PR_EMAIL_undefined&quot;)</value>
      <webElementGuid>441b5848-dbf0-4670-9c2b-3ceec8eecef0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PR_EMAIL_undefined']</value>
      <webElementGuid>42c18e85-70de-4978-ac28-6f0450bb6ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_0']/td[2]/input</value>
      <webElementGuid>d1a2d814-b481-4ce3-b446-e9deeaceef0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>0e83b7e3-0896-4b50-8012-aac16b7ac152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PR_EMAIL_undefined' and @name = 'Value' and @type = 'text']</value>
      <webElementGuid>60a7e39b-290b-4811-befd-f5db6eec933d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
