<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Primary_PR_EMAIL_undefined</name>
   <tag></tag>
   <elementGuidId>13fbca5f-7201-4c8b-b9ef-b125b836450c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PR_EMAIL_undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PR_EMAIL_undefined']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PR_EMAIL_undefined</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd2a281b-4760-4c4f-881c-bdd8e6543f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-validation-error</value>
      <webElementGuid>3369eb1b-2cfc-4143-8fb0-faa855421eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-commtype</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>8b5c48ef-2862-4756-a391-6c4c5fd14cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>Value</value>
      <webElementGuid>ccbc6f31-74a5-490d-b2a9-f0df209d4b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>EmailPhone</value>
      <webElementGuid>fdcf97d5-823d-4a2f-84d3-38387c275d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PR_EMAIL_undefined</value>
      <webElementGuid>813d2613-24aa-4322-82a2-a472fe0419af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Value</value>
      <webElementGuid>f7865b41-97e0-4fc6-a9b9-97a2c1bcc98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>DuplicateValidation(this)</value>
      <webElementGuid>6b86a61a-63a1-4eee-9143-7aec7e756537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6a051ea1-0db6-46bd-a9f5-2ef810f0cadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>d42a35f1-b5b1-4071-b4fe-09f35e070cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>e8e9d843-6d6b-40dd-adfc-bd46ad828cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data_commtype</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>af2b368a-6e78-4cd9-ad1f-152261b3139c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-dependentproperty</name>
      <type>Main</type>
      <value>PatientInfo_IsEmailRequired</value>
      <webElementGuid>cbe7ae9e-97c0-469d-9241-fb00fd116b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-email</name>
      <type>Main</type>
      <value>Email is not valid</value>
      <webElementGuid>f8a35859-efce-4376-a7e4-069f5b653787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PR_EMAIL_undefined&quot;)</value>
      <webElementGuid>72151290-79f4-4a2e-98c0-137900165ff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PR_EMAIL_undefined']</value>
      <webElementGuid>965a420a-f6c4-4235-b532-d0bbf6cb47ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_5a8bb18e-ba15-4886-a1c9-9b68aa614b36']/td[2]/input</value>
      <webElementGuid>2e668d1e-3856-48aa-9c5c-e2e6eb96ea7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>e9c28198-6005-4ed4-94b5-d513d14804bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PR_EMAIL_undefined' and @name = 'Value' and @type = 'text']</value>
      <webElementGuid>2a58491c-3bb3-4874-8d48-c6d6505618c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_f5fe287e-aa43-4e4d-987e-518c6226220c']/td[2]/input</value>
      <webElementGuid>dfb6258d-345a-4696-bd90-2c145111fbf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
