<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_textbox (1)</name>
   <tag></tag>
   <elementGuidId>c13ae1ec-30cb-4e83-ba69-a9c84a7b588f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90eb9d5c-e094-46d4-9ad5-7ceca4d529ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>24df5480-fa8d-451b-bfb7-73a86352a7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d4e4773-c4c9-4b2b-8c3d-6aead6bd0dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>height24</value>
      <webElementGuid>62263e00-73a6-4231-9c4f-f57ccfd62375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ed24b537-1261-4a72-80f6-811f2623589e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textbox&quot;)</value>
      <webElementGuid>b2231028-1122-48b7-abbf-27521880cb95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textbox']</value>
      <webElementGuid>ee029f5a-b10f-42d1-b17b-999e297d8b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divImoSearchScreen']/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>b2d7915d-63f7-48f6-8ff1-108b901fd2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>b4a867b6-5c8d-4b00-b8c6-9e58c0b04032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'textbox' and @type = 'text']</value>
      <webElementGuid>c6279425-addc-4107-84e8-a72da9e54a48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
