<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_AddNew_Patient_FirstName (2)</name>
   <tag></tag>
   <elementGuidId>a3c9e6fd-fa40-4c22-a7bf-98f125d1f4d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddNew_Patient_FirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddNew_Patient_FirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AddNew_Patient_FirstName</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59f4ab00-fe64-4764-ba25-62a16e1ea319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddNew_Patient_FirstName</value>
      <webElementGuid>fb4be8a1-4c05-4fb3-8a29-9222f51c907b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>propname</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>ff5a7709-43f1-440f-8d20-53efe9ba79bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>e366d0da-d1b6-4563-b3b0-716e73593c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>c50a8682-c94a-4092-918f-9ff7fcf5cdef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~PatientInfo.PatientDetail.FirstName</value>
      <webElementGuid>13864541-2de5-4d8b-9321-c92ed74eb44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>STRING</value>
      <webElementGuid>93fbbcfd-b6da-4b55-89d2-e804b5bd9ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>PatientDetail</value>
      <webElementGuid>b681c762-e789-455e-9db2-d38af83eb33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error-message</name>
      <type>Main</type>
      <value>First Name is required </value>
      <webElementGuid>a8c62df1-c165-4e59-a0de-1aa842826fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>09cb60e9-92a5-4589-a841-ac3f046aaac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>First Name length can't be more than 100.</value>
      <webElementGuid>3454fc2e-ab63-4eb8-b2e8-cd304ce05824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0220c82e-b306-4ccb-b3ab-86aecc467bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>You must enter a First name.</value>
      <webElementGuid>1a8d3354-1ea8-46b1-90cf-e4b3574a5b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c55362e7-05cf-4e24-b158-4c4fd061299d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addNewPatient.patientDetails.FirstName</value>
      <webElementGuid>8cbb9697-56b4-44ad-8a9d-f786e49cd246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OnDataChanged(this)</value>
      <webElementGuid>48ffc266-e26e-4ca8-aab8-b22cb7978519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83ef0254-6b7d-49a6-aff6-9443c5bb0885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>71ff6e35-793e-41e7-86a3-e950435c6f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-validation-error</value>
      <webElementGuid>8a5fbd32-a6fe-4217-9b8c-abb65fd0970a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>AddNew_Patient_FirstName-error</value>
      <webElementGuid>ae9ec484-1ff8-4c51-88cd-d83fa9295fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>95a6434d-76d3-43c1-b1ee-c12a2759eedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddNew_Patient_FirstName&quot;)</value>
      <webElementGuid>22bc971a-61f6-4a94-a0c7-62e9fcb5a38b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddNew_Patient_FirstName']</value>
      <webElementGuid>c589210c-c332-4ebb-a862-ffaf385f744d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewPtDetails']/div/div/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>7978802c-38c0-4ae3-bf18-6fdb2b5f5ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>12503545-45a6-4519-96e3-36a36de22944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddNew_Patient_FirstName' and @name = 'addNewPatient.patientDetails.FirstName' and @type = 'text']</value>
      <webElementGuid>e5280575-1a27-4d68-a4c4-5698ccee8e8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
