<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OD_SPHERICAL_OD</name>
   <tag></tag>
   <elementGuidId>a3cdf864-9c5c-4f07-8d49-3c08aa0c8efe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SPHERICAL_OD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SPHERICAL_OD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SPHERICAL_OD</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e2e39e8-1edd-422f-81c1-e16ef0eb3793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-call-from</name>
      <type>Main</type>
      <value>addOpticalRX</value>
      <webElementGuid>20c04235-e059-4f65-9a68-70b95cf4228d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultspot</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>1996fde5-92f5-4e05-bc4b-a7a5932949d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec-valuelistname</name>
      <type>Main</type>
      <value>Refraction_Sphere</value>
      <webElementGuid>b5551438-f344-4936-b0a2-9d6d3788efb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field-attribute</name>
      <type>Main</type>
      <value>SPHERE_OD</value>
      <webElementGuid>dcd66c22-21ce-413b-af23-24285951edca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SPHERICAL_OD</value>
      <webElementGuid>c11daaf8-b62b-4019-98e2-804f1756a318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SPHERICAL_OD</value>
      <webElementGuid>139f75de-88ca-4148-8ea3-4f097c3c0f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c60e22ae-4805-4f00-b48a-3c19ddf2e7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2f2ada5a-5c90-4ef4-b169-520cf9038bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec_valuelistname</name>
      <type>Main</type>
      <value>Refraction_Sphere</value>
      <webElementGuid>cebcae28-bfdb-4a6f-803c-064a8f2e7b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>2ff5fca2-62de-4740-804c-c30f76404fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>611a5680-f4bd-4a1b-a4f7-137216466350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SPHERICAL_OD&quot;)</value>
      <webElementGuid>20424a5b-2fc1-472c-bbf3-68468a8287af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SPHERICAL_OD']</value>
      <webElementGuid>62e4268e-78c2-40b9-862a-b44db71f6be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ODDATA']/td[2]/input</value>
      <webElementGuid>9d15519d-2d35-4abc-b505-46d4fa93180a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>6a90320a-b309-49b2-b97b-d85c6c88df12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SPHERICAL_OD' and @name = 'SPHERICAL_OD' and @type = 'text']</value>
      <webElementGuid>b8d6fa5d-4b54-4fca-8ff8-cfb893a3fc67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
