<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PLANS_Save</name>
   <tag></tag>
   <elementGuidId>a172da6a-bbac-409e-b0d4-b787338a6380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;SAVE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74f39d2c-1ff8-40df-94e4-32e9293ade97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary small-button50</value>
      <webElementGuid>d3016437-6d5d-4a19-983a-0fc4cadd0f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d74e97b-c243-4110-b0d4-48c8e7243323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>d3fc4a55-ee3d-43ef-b80e-522996536942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SAVE</value>
      <webElementGuid>b293dba2-f61c-4ad5-93c8-f9888a7b0d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SAVE</value>
      <webElementGuid>5e791c2d-9264-4c5b-bef9-7fc05ef245e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveFinalDxAndFinalProcElementData(this, event,0)</value>
      <webElementGuid>f9ef5bf4-09ac-456f-b49f-2de1d85daf47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Save&quot;)</value>
      <webElementGuid>36870a4e-639a-4bb4-8be8-2046f69caa82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Save']</value>
      <webElementGuid>709dae5d-cb6d-4188-813d-ccce05338df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FinalDiagonsisMainElement']/div[2]/div/div/input</value>
      <webElementGuid>25d8c7bc-0564-4fc9-a66b-838bad821497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>30dacd2a-66fc-47dd-bec5-a6de7e5fa6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'Save' and @title = 'SAVE']</value>
      <webElementGuid>fedcb3e8-7b5c-4530-8a79-04b8c3d51910</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
