<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit Email Address_btnProceedSaveNewP_fc225c</name>
   <tag></tag>
   <elementGuidId>7c54ad05-fca5-4e46-a34f-cfb1c5583a62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnProceedSaveNewPreferencePP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnProceedSaveNewPreferencePP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;PROCEED&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8671ebb-c11b-4ace-93ef-8e8095234337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77f54695-1163-4753-b61a-bf3889089ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>PROCEED</value>
      <webElementGuid>e3026eff-20d2-45f8-becf-86f2e998a9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnProceedSaveNewPreferencePP</value>
      <webElementGuid>8f5d8136-840b-446d-be26-0ef2c26c293f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button med-small-button30 primary</value>
      <webElementGuid>c3b049e7-8833-40ea-90ea-2684f23d8d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnProceedSaveNewPreferencePP&quot;)</value>
      <webElementGuid>ca6657aa-289e-43bf-a255-7a6a6718e3f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnProceedSaveNewPreferencePP']</value>
      <webElementGuid>738843c0-8594-4669-bf47-e47af1236a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='patientportalsignuppopup']/div[2]/div/div/input</value>
      <webElementGuid>ebdf714b-5ff6-4b0b-8be8-442187776f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>28643f0f-3f2c-4e64-bd7a-d147579b16fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnProceedSaveNewPreferencePP']</value>
      <webElementGuid>5f73d9d4-84b2-40e3-bf5e-072ce10c2804</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
