<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(3.00MM Branch Occlusion 4.8DD _2be33d</name>
   <tag></tag>
   <elementGuidId>9e638d03-81eb-4f0c-84b4-c6143afe9e24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSaveDrawingActionButtons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnSaveDrawingActionButtons']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f432c79a-ae47-4c58-95ca-b5d0a28f3585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d8310cc-01bb-458a-a079-462b29be0b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveDrawingActionButtons</value>
      <webElementGuid>a5214540-98d9-4df0-b896-dba1ab3062a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary small-button30 marL10</value>
      <webElementGuid>08319c25-8fe7-4dc4-9bd9-ed8c80d7404d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>bcbc4285-f25d-4584-a0fa-37bc65207830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SaveTemplateDrawingAndClose()</value>
      <webElementGuid>773810c8-03bb-4d0b-8938-07050adf817d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSaveDrawingActionButtons&quot;)</value>
      <webElementGuid>aaca2c2b-1fbb-4b32-a867-37054f73a202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_MaximEyes/iframe_E-Files_frmEncounterDrawTemplate</value>
      <webElementGuid>c9d93eae-86d7-47cd-9b32-b0f6b4e71289</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnSaveDrawingActionButtons']</value>
      <webElementGuid>8a21f223-d65d-4de7-98c3-cb9787aa9cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEncounterDrawing']/div/div[2]/div/div/div/div/input[2]</value>
      <webElementGuid>484f56b3-c329-4fed-b046-b6886c886694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input[2]</value>
      <webElementGuid>8c9307d6-7a01-4fec-97d0-059e15abcb79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnSaveDrawingActionButtons']</value>
      <webElementGuid>10d63c72-d899-4d23-be7d-2767f5ebb283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
