<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lab_btnSelectSLLab</name>
   <tag></tag>
   <elementGuidId>02de5192-c469-466a-a1c1-cccf2ede92bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSelectSLLab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnSelectSLLab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Proceed&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e67a6dc-4a87-435c-8d36-720922955289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c7111436-c216-4f12-a43a-92b1c21892e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary small-button padButtonLR</value>
      <webElementGuid>810f6e76-a177-417c-89c3-bcc038258c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Proceed</value>
      <webElementGuid>56ca496c-80b6-458f-a454-00d5936e9808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSelectSLLab</value>
      <webElementGuid>687fea0e-de7c-44a3-bdf1-da92820e1596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setLabForSLOrder(this, '', '0');</value>
      <webElementGuid>f1b14419-b2df-4a19-a804-d118d8b1befc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSelectSLLab&quot;)</value>
      <webElementGuid>57cd0bf0-1521-46a9-b74b-24186bc17d29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnSelectSLLab']</value>
      <webElementGuid>432fe36d-d9b1-42b4-91aa-687d736a735b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='191e6']/div/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>8d994d86-b400-49ee-9bb9-37813de9b1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/input</value>
      <webElementGuid>03140fb2-73f6-44bb-a501-bb891052e04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnSelectSLLab']</value>
      <webElementGuid>b2235ad4-8524-4c99-86ae-da8b2e1ef231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
