<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Audited by_AuditedBy</name>
   <tag></tag>
   <elementGuidId>d51cc742-3089-4d5a-b7f3-d1643731c17a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AuditedBy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AuditedBy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AuditedBy</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>557d4789-58f4-40e4-8941-1bab1cd9b18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>911512bf-fe99-427e-82b9-b425ff7342ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>AuditedBy</value>
      <webElementGuid>78053f0e-acde-4f4e-bc1c-ee2ca9166793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>BillDetails</value>
      <webElementGuid>0ab3599b-24da-47ea-9651-eb1a65906b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~AuditedBy</value>
      <webElementGuid>69bcd479-34af-4920-8740-33a4f1a18386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>STRING</value>
      <webElementGuid>d56976d3-9020-4e7f-b31a-3d4d6db3d04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AuditedBy</value>
      <webElementGuid>982c53db-c7af-4ed0-81aa-919d3f964022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AuditedBy</value>
      <webElementGuid>8a18b592-00f4-4124-a9e3-6be25d48bfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7990c15d-0ead-48c3-86f7-5903d5a0210c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>84fd3df1-09f7-47ab-be53-8c7376f37737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AuditedBy&quot;)</value>
      <webElementGuid>755f8af3-980f-48d2-be89-c8ff8bcf13a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AuditedBy']</value>
      <webElementGuid>f7075fe6-3214-472a-bb3a-274db27f72fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divOutstandingCharge_26751']/div/div/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>8d52a209-e9d7-44be-826b-2d4b1b931f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/input</value>
      <webElementGuid>1dd86ddf-be26-4c27-aa98-9a7b39c38884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'AuditedBy' and @name = 'AuditedBy']</value>
      <webElementGuid>72e49ab1-a3f0-42d3-b300-1671f9a41dd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
