<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address (Line 1)_AddNew_Patient_Line1</name>
   <tag></tag>
   <elementGuidId>a6e75f60-04b9-4f87-a1cf-b26710f5abce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddNew_Patient_Line1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddNew_Patient_Line1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AddNew_Patient_Line1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6fdbd2d-0812-4023-b265-f0558096f5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddNew_Patient_Line1</value>
      <webElementGuid>e142b466-cd20-4202-b1df-104823006e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>propname</name>
      <type>Main</type>
      <value>Line1</value>
      <webElementGuid>2e477ca9-f3ef-4327-be18-ceb053ad132e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>88f625c9-0add-4e76-a622-1373bff3e414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>Line1</value>
      <webElementGuid>758876ab-77d5-4d6c-97bc-730d3f890e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~AddNewPatient.AddressModel.Line1</value>
      <webElementGuid>f23fe1ce-9221-46ca-a2d8-9d3e7dd024da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>STRING</value>
      <webElementGuid>df77dbd8-6dd1-40b5-9076-1d4fc98fba85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>PatientDetail</value>
      <webElementGuid>c4c6619a-c0fa-423a-a056-777480ec5d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addNewPatient.addressModel.Line1</value>
      <webElementGuid>fef5daba-0cc0-40ae-bad2-8be88f7126c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>UpdateCommPermission('Address'); OnDataChanged(this)</value>
      <webElementGuid>06763ccd-da9e-44f4-8694-1b9148593646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>validateKeyPressXss(event);</value>
      <webElementGuid>6a7d2906-e03d-4a90-94d3-6f42b3b1c90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>validatePasteXss(this);</value>
      <webElementGuid>08082fb3-1a7d-4d4a-b768-0d1be43e9c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc84ec07-91e1-4fb9-9eda-f1eb72c5fe89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>70f4f0b8-bc23-4b0b-a8fe-3b722be10cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>5f7e0d0d-eb40-4a3a-ac45-cfc30eab3a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddNew_Patient_Line1&quot;)</value>
      <webElementGuid>c88a2f3b-dd5d-4d1c-bc82-133b882415c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddNew_Patient_Line1']</value>
      <webElementGuid>d8d7d90b-4129-4d7b-a6ce-16db0d5e30d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewPtDetails']/div/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>10399495-7f6c-4309-aefb-cef45c914f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/input</value>
      <webElementGuid>6dc94238-3db9-4d08-973d-b223a393cddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddNew_Patient_Line1' and @name = 'addNewPatient.addressModel.Line1' and @type = 'text']</value>
      <webElementGuid>439f6adc-8155-4659-86b9-87706fbd24ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
