<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OD_AXIS_OD</name>
   <tag></tag>
   <elementGuidId>735c6113-632c-4a84-81be-b1bf5f982687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AXIS_OD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AXIS_OD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AXIS_OD</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03409547-e5b1-4e72-83b3-2dcc5073e606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-call-from</name>
      <type>Main</type>
      <value>addOpticalRX</value>
      <webElementGuid>98c1eebd-72ea-4bef-9291-bc47e44ada2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec-valuelistname</name>
      <type>Main</type>
      <value>Refraction_Axis</value>
      <webElementGuid>03c02a3c-2284-4b4f-9d54-7a4b5ef55037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field-attribute</name>
      <type>Main</type>
      <value>AXIS_OD</value>
      <webElementGuid>1fb180f5-f8fc-4c19-bb53-4d9c0da10fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AXIS_OD</value>
      <webElementGuid>83d26be8-a78a-4f6c-8769-747a904b9f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AXIS_OD</value>
      <webElementGuid>fe459de1-0845-41ad-93f9-446cce603a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>SetDefaultValueForAxis(this)</value>
      <webElementGuid>06324227-97fb-4ba7-a343-9966fdfb4ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b49817cc-db10-4bf7-894a-676105f61b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cf860391-6859-4adb-bc73-c9a07d9e3092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec_valuelistname</name>
      <type>Main</type>
      <value>Refraction_Axis</value>
      <webElementGuid>43228b06-9b8a-4cdd-9cc0-dac2850b26a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>35327eb7-1823-4e49-978b-ac0caaa53c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>faff154e-9719-4068-92b3-fd313d600b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AXIS_OD&quot;)</value>
      <webElementGuid>ab99c2f5-297d-4a6c-b6e4-ec1ae805af1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AXIS_OD']</value>
      <webElementGuid>69eece3c-1b1e-44d2-9b5b-f8fad19d4ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ODDATA']/td[4]/input</value>
      <webElementGuid>237bcb88-d329-4c53-8d19-82ff85b744bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/table/tbody/tr/td[4]/input</value>
      <webElementGuid>57cf1b3b-d21e-4f2c-a008-b9c9133ae24e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AXIS_OD' and @name = 'AXIS_OD' and @type = 'text']</value>
      <webElementGuid>42791ae4-5b37-4c4d-b3da-94b4d04de181</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
