<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Encounter Type_EncounterTypeID</name>
   <tag></tag>
   <elementGuidId>a45b5243-8255-47ac-b4b1-5583758b3ca4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EncounterTypeID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EncounterTypeID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#EncounterTypeID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3dfa573d-808c-4661-b940-5837a5d1ed19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>12079887-7fff-4574-bc87-a61874a445da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field EncounterTypeID must be a number.</value>
      <webElementGuid>6e745396-6018-463b-bfd2-075e953451d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Encounter Type is required</value>
      <webElementGuid>63d6a722-59f0-45c3-9c92-6a32245e265e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EncounterTypeID</value>
      <webElementGuid>f40ba006-18cf-46f2-90ed-d62aaaf39bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EncounterTypeID</value>
      <webElementGuid>37c4215c-6629-4244-b226-00f18a93467e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>encounterTypeChange(this)</value>
      <webElementGuid>016b847e-df24-47c5-a9ae-c990e0fc42dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1) Est. Pt Eye Exam2] New Pt Eye Exam3] New Pt Wellness Exam-Scode4] Est. Pt Wellness Exam-Scode5] New Pt Comprehensive Eye Exam with DFE -Medicare, Diabetes6] Est. Pt Comprehensive Eye Exam with DFE - Medicare, Diabetes7] CL Followup8] Diagnostic TestsAnnual Vision Exam - TrainingAutomation Element Test EncounterAutomation Eye Exam Optometry with CLContact Lens Evaluation &amp; Fitting OnlyEye Exam Optometry with CLMedication Rx Without Patient VisitProblem Oriented Visit</value>
      <webElementGuid>22da9d2c-5472-40d9-8652-e8f4f0fa1f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EncounterTypeID&quot;)</value>
      <webElementGuid>70c45769-d9d1-4881-a386-90a6955ed0e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EncounterTypeID']</value>
      <webElementGuid>5685e91a-f46e-43a9-ac06-87bff3910e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_NewPatientEncounter']/div/div/div/div/div/div/div/div[2]/div/div/div/span/select</value>
      <webElementGuid>bbc4edfc-0919-4750-80fd-129ef59c4a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encounter Type'])[1]/following::select[1]</value>
      <webElementGuid>c78e754d-49ae-4c98-b232-b06c7d736354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exam Location'])[1]/preceding::select[1]</value>
      <webElementGuid>fe58a991-8f41-4eb3-a020-6c667d9429c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exam Date'])[1]/preceding::select[2]</value>
      <webElementGuid>6a20b821-1e5c-4030-82d9-3f55b333ad54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/select</value>
      <webElementGuid>3689a3ad-5720-4cb2-9f72-2b5349923347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EncounterTypeID' and @name = 'EncounterTypeID' and (text() = '1) Est. Pt Eye Exam2] New Pt Eye Exam3] New Pt Wellness Exam-Scode4] Est. Pt Wellness Exam-Scode5] New Pt Comprehensive Eye Exam with DFE -Medicare, Diabetes6] Est. Pt Comprehensive Eye Exam with DFE - Medicare, Diabetes7] CL Followup8] Diagnostic TestsAnnual Vision Exam - TrainingAutomation Element Test EncounterAutomation Eye Exam Optometry with CLContact Lens Evaluation &amp; Fitting OnlyEye Exam Optometry with CLMedication Rx Without Patient VisitProblem Oriented Visit' or . = '1) Est. Pt Eye Exam2] New Pt Eye Exam3] New Pt Wellness Exam-Scode4] Est. Pt Wellness Exam-Scode5] New Pt Comprehensive Eye Exam with DFE -Medicare, Diabetes6] Est. Pt Comprehensive Eye Exam with DFE - Medicare, Diabetes7] CL Followup8] Diagnostic TestsAnnual Vision Exam - TrainingAutomation Element Test EncounterAutomation Eye Exam Optometry with CLContact Lens Evaluation &amp; Fitting OnlyEye Exam Optometry with CLMedication Rx Without Patient VisitProblem Oriented Visit')]</value>
      <webElementGuid>8986f581-6a26-4f4f-8751-bcc3feec4582</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
