<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Encounter Type_EncounterTypeID (1)</name>
   <tag></tag>
   <elementGuidId>0d18da00-7a39-4fea-b5f8-322d91ab12b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EncounterTypeID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EncounterTypeID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#EncounterTypeID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2cc6d80b-9695-4ebf-8af0-311ffd737cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4de1c396-c661-429a-8afa-25b8df378196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field EncounterTypeID must be a number.</value>
      <webElementGuid>cdb4ced1-bb79-40e7-b6e1-a132ac95ed49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Encounter Type is required</value>
      <webElementGuid>1a523694-baa6-4ffa-a26d-486c9eb553e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EncounterTypeID</value>
      <webElementGuid>30e63f56-7d31-4bd1-8333-4802608100f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EncounterTypeID</value>
      <webElementGuid>969b029c-903f-47c6-ae30-6d7c546b2eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>encounterTypeChange(this)</value>
      <webElementGuid>e3a01799-909e-491d-807e-33487e3d24dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1) Est. Pt Eye Exam2] New Pt Eye Exam3] New Pt Wellness Exam-Scode4] Est. Pt Wellness Exam-Scode5] New Pt Comprehensive Eye Exam with DFE -Medicare, Diabetes6] Est. Pt Comprehensive Eye Exam with DFE - Medicare, Diabetes7] CL Followup8] Diagnostic TestsAnnual Vision Exam - TrainingAutomation Element Test EncounterAutomation Eye Exam Optometry with CLContact Lens Evaluation &amp; Fitting OnlyEye Exam Optometry with CLMedication Rx Without Patient VisitProblem Oriented Visit</value>
      <webElementGuid>79371b2d-ae15-4cb7-a081-ff0729fd4d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EncounterTypeID&quot;)</value>
      <webElementGuid>fb5652aa-af86-4316-ae4a-6929d19a8a5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EncounterTypeID']</value>
      <webElementGuid>bae8181c-96b1-4034-b234-0d2c4b5e6e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_NewPatientEncounter']/div/div/div/div/div/div/div/div[2]/div/div/div/span/select</value>
      <webElementGuid>a91bfb96-cffa-4c23-8c97-25e996e35b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encounter Type'])[1]/following::select[1]</value>
      <webElementGuid>e7b20365-0fb3-49aa-85c0-312de2017a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exam Location'])[1]/preceding::select[1]</value>
      <webElementGuid>90c0829d-b89b-48d0-982a-cd5b73fcd177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exam Date'])[1]/preceding::select[2]</value>
      <webElementGuid>26527785-213d-4020-aabd-8fb948d8de4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/select</value>
      <webElementGuid>a335000e-353b-45e0-986d-ad24d5b07241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EncounterTypeID' and @name = 'EncounterTypeID' and (text() = '1) Est. Pt Eye Exam2] New Pt Eye Exam3] New Pt Wellness Exam-Scode4] Est. Pt Wellness Exam-Scode5] New Pt Comprehensive Eye Exam with DFE -Medicare, Diabetes6] Est. Pt Comprehensive Eye Exam with DFE - Medicare, Diabetes7] CL Followup8] Diagnostic TestsAnnual Vision Exam - TrainingAutomation Element Test EncounterAutomation Eye Exam Optometry with CLContact Lens Evaluation &amp; Fitting OnlyEye Exam Optometry with CLMedication Rx Without Patient VisitProblem Oriented Visit' or . = '1) Est. Pt Eye Exam2] New Pt Eye Exam3] New Pt Wellness Exam-Scode4] Est. Pt Wellness Exam-Scode5] New Pt Comprehensive Eye Exam with DFE -Medicare, Diabetes6] Est. Pt Comprehensive Eye Exam with DFE - Medicare, Diabetes7] CL Followup8] Diagnostic TestsAnnual Vision Exam - TrainingAutomation Element Test EncounterAutomation Eye Exam Optometry with CLContact Lens Evaluation &amp; Fitting OnlyEye Exam Optometry with CLMedication Rx Without Patient VisitProblem Oriented Visit')]</value>
      <webElementGuid>f1c049cd-1342-4371-a3e7-c2b220989682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
