<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_EM Code Checker_ePrescribe_102724 (1)</name>
   <tag></tag>
   <elementGuidId>369015cd-6a8c-4c48-9289-5ff1c2a92ee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ePrescribe_102724</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='E&amp;M Code Checker'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;E-Prescribe&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e211b2e7-cb08-4668-a2b2-c6b9612a9e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fg-black font14</value>
      <webElementGuid>7bc3b0c2-fa40-4244-9740-475bfbbb762c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-practicepersonid</name>
      <type>Main</type>
      <value>330</value>
      <webElementGuid>163cffcd-de9e-4a70-b916-16e0fc6275b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ePrescribe_102724</value>
      <webElementGuid>1fb6f834-a4e4-412c-8762-2b2cbb495a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordguid</name>
      <type>Main</type>
      <value>102724</value>
      <webElementGuid>b58b9990-9205-402b-bc7f-1687e0e3186a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>encounterEPrescribe(this,'76','184', '102724', 70847)</value>
      <webElementGuid>50effe49-449e-4b71-bcd9-15e3a6dbd723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E-Prescribe</value>
      <webElementGuid>49ac377f-e54c-4788-b7a8-b749f9173709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ePrescribe_102724&quot;)</value>
      <webElementGuid>f95ae6f9-61ce-45dd-ab9c-c29ab8b69b1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ePrescribe_102724']</value>
      <webElementGuid>f0c3dfa9-9140-40ba-8861-da8aa6de6881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='encMainDiv_102724']/div[2]/div/div[2]/div[3]/div/a/span</value>
      <webElementGuid>c06f2885-577d-46c5-97a8-54c5571e7c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E&amp;M Code Checker'])[1]/following::span[1]</value>
      <webElementGuid>5937f379-e8d0-498a-b85b-0c86d4d0789b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUICKLINKS'])[1]/following::span[2]</value>
      <webElementGuid>bb8f5818-dfe7-453e-a80c-6ab74aa9dcc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encounter Overview'])[1]/preceding::span[1]</value>
      <webElementGuid>a2c9bbf0-b54e-46b5-911a-526e9829bdc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summary Of Care(C-CDA)'])[1]/preceding::span[2]</value>
      <webElementGuid>6eb8e02e-6058-46a7-9545-10b4aa8c0335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='E-Prescribe']/parent::*</value>
      <webElementGuid>ec4d1274-1d46-4423-bd4b-afc47c0d287b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/a/span</value>
      <webElementGuid>6dde6fe0-35aa-4017-9f6f-f363ca58f39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ePrescribe_102724' and (text() = 'E-Prescribe' or . = 'E-Prescribe')]</value>
      <webElementGuid>dbc08fad-b003-4275-acaa-2affa30f7164</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
