<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TOC Req_mif-Hamburger fg-gray font30 (1)</name>
   <tag></tag>
   <elementGuidId>7a115634-1a14-43d6-99ab-fb7356d11de1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mif-Hamburger.fg-gray.font30</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='showMoreMenu(this)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3bb3d90-c9cc-4ad2-9c5e-c1c6b819801b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mif-Hamburger fg-gray font30</value>
      <webElementGuid>88ca30c4-c356-4af7-8dcb-83da090f2cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showMoreMenu(this)</value>
      <webElementGuid>0b471cd4-2ad9-4ba5-82f9-5204aa58385d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>More</value>
      <webElementGuid>53a7b876-9e7a-4ff5-a170-60fb0f2e3937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patientEncounterHeader&quot;)/div[@class=&quot;col-xs-12 col-sm-12 col-md-12 col-lg-5 no-padding marT10&quot;]/ul[@class=&quot;ribbon-encounter-left-icons&quot;]/li[1]/a[@class=&quot;line-height34&quot;]/span[@class=&quot;mif-Hamburger fg-gray font30&quot;]</value>
      <webElementGuid>74306125-bedd-40ea-823c-4a654121b002</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='showMoreMenu(this)']</value>
      <webElementGuid>a5407b56-0329-4750-8af2-6d8b025c8bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='patientEncounterHeader']/div[2]/ul/li/a/span</value>
      <webElementGuid>951a5978-cd9e-4a30-a42c-3f3ceb6c9e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a/span</value>
      <webElementGuid>d0837ab6-8b4f-416b-a5ae-25986bc08589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'More']</value>
      <webElementGuid>361bff6a-0bfe-4114-a59c-11d91413ff60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
