<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Patient Portal_ptoverviewsignupforpp</name>
   <tag></tag>
   <elementGuidId>f938bb3f-54a6-4f1e-88a0-ffdddcc82c28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ptoverviewsignupforpp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='PtOverviewSignUpPatientToPortal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ptoverviewsignupforpp</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>03dabb90-692a-478c-8289-4e4538611ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mif-circle-plus font18 fg-skyblue marL5 v-align-bottom</value>
      <webElementGuid>10e5861a-0c8d-4c66-a826-dbb084cf24a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ptoverviewsignupforpp</value>
      <webElementGuid>78d01bdb-a914-4f17-a109-4244284148f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ShowSignupPreferencePopUpPP(false, false)</value>
      <webElementGuid>9e5f9956-99f8-4a52-914a-b06b830c615e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ptoverviewsignupforpp&quot;)</value>
      <webElementGuid>b6325f30-1bed-4eaf-b107-383f2059810a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='PtOverviewSignUpPatientToPortal']</value>
      <webElementGuid>611fb062-c3bf-4682-829f-7c30c94a8899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@onclick=&quot;ShowSignupPreferencePopUp(false, true,'')&quot;]</value>
      <webElementGuid>7a300575-4a1d-4cc6-9447-d3b0666d0e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[@id='PtOverviewSignUpPatientToPortal']</value>
      <webElementGuid>31511ca0-5884-4007-a9cc-9b247a24600c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id='PtOverviewSignUpPatientToPortal']</value>
      <webElementGuid>f0580493-2c16-4865-b73c-10d32846ed29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
