<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_EM Code Checker_ePrescribe_102724</name>
   <tag></tag>
   <elementGuidId>284d6529-79d9-4d5f-9a04-3006a478a57a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ePrescribe_102724</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='E&amp;M Code Checker'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;E-Prescribe&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>94f8ac79-194d-44b2-abfd-df98675c9c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fg-black font14</value>
      <webElementGuid>ca403ee9-77f1-4c26-8f94-0c07ba44d56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-practicepersonid</name>
      <type>Main</type>
      <value>330</value>
      <webElementGuid>4c63e3e7-f6d6-447f-b9ea-b43779462533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ePrescribe_102724</value>
      <webElementGuid>31bc564b-1e5e-4110-bad8-5a6a051ad630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordguid</name>
      <type>Main</type>
      <value>102724</value>
      <webElementGuid>81f1aece-f815-4fea-81e2-27134e30ede3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>encounterEPrescribe(this,'76','184', '102724', 70847)</value>
      <webElementGuid>ff59c6ac-9379-40a3-8a8a-eb237843a382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E-Prescribe</value>
      <webElementGuid>4d63ee5e-0524-4d54-a028-57163f00280e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ePrescribe_102724&quot;)</value>
      <webElementGuid>741ad28e-1ce5-4a34-917b-f2e180a5414b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ePrescribe_102724']</value>
      <webElementGuid>7274c461-49d3-4cbf-94e9-bd64b82bfe1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='encMainDiv_102724']/div[2]/div/div[2]/div[3]/div/a/span</value>
      <webElementGuid>8a771e63-0573-4a0c-ba97-65486fec6b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E&amp;M Code Checker'])[1]/following::span[1]</value>
      <webElementGuid>1b1e5b63-5f80-4311-96b4-1e7d9ade1536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUICKLINKS'])[1]/following::span[2]</value>
      <webElementGuid>1f18c8ab-03fa-4abb-942c-82848224ff9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encounter Overview'])[1]/preceding::span[1]</value>
      <webElementGuid>2445f785-40a6-4616-bd5d-4df805cca792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summary Of Care(C-CDA)'])[1]/preceding::span[2]</value>
      <webElementGuid>7609317e-5f89-4037-adb7-c78d6a4f9fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='E-Prescribe']/parent::*</value>
      <webElementGuid>92bb86ab-b0c7-42be-98b0-fdfc67dbba48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/a/span</value>
      <webElementGuid>59ba0b6c-fe8a-4a6a-9171-7cfe589cdc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ePrescribe_102724' and (text() = 'E-Prescribe' or . = 'E-Prescribe')]</value>
      <webElementGuid>cfd20386-4933-4bc8-af29-af3b97a01a53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
