<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TOC Req_mif-Hamburger fg-gray font30</name>
   <tag></tag>
   <elementGuidId>e2b43544-56f3-4e68-9ba9-f3c77f4acbda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mif-Hamburger.fg-gray.font30</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='showMoreMenu(this)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6a172b04-b413-4e7f-83e9-6557c89a4688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mif-Hamburger fg-gray font30</value>
      <webElementGuid>a54025dc-d407-4315-a834-32b1ca85bcb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showMoreMenu(this)</value>
      <webElementGuid>45c9e2c3-8734-4fa4-a66c-f85fa2818683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>More</value>
      <webElementGuid>b290570f-68ec-42a1-979f-f9793d78b7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patientEncounterHeader&quot;)/div[@class=&quot;col-xs-12 col-sm-12 col-md-12 col-lg-5 no-padding marT10&quot;]/ul[@class=&quot;ribbon-encounter-left-icons&quot;]/li[1]/a[@class=&quot;line-height34&quot;]/span[@class=&quot;mif-Hamburger fg-gray font30&quot;]</value>
      <webElementGuid>15afa803-6346-47d2-8b77-32a3bdb1ba4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='showMoreMenu(this)']</value>
      <webElementGuid>8cb0ab7a-4022-49c5-a534-d95a1e543ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='patientEncounterHeader']/div[2]/ul/li/a/span</value>
      <webElementGuid>ff562ad4-2e08-48cb-aa71-be4b5014d2c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a/span</value>
      <webElementGuid>d186ce83-24d9-453f-8dbc-bd12d714219b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'More']</value>
      <webElementGuid>18946ba1-d375-4e7c-aabe-75eb8e966dd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
