<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__text-gray-500</name>
   <tag></tag>
   <elementGuidId>afb54828-e0ed-4297-b78a-36db8e1e8436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-gray-500</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[normalize-space()='Patient Relationship to Insured']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Patient Relationship to Insured&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c171ea71-7590-4a68-b9a8-e48243e270a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-500</value>
      <webElementGuid>e9199593-6396-497c-a1e9-acf1c18f7b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient Relationship to Insured</value>
      <webElementGuid>8158b6f4-2381-4c79-a024-92051b080e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen flex flex-col bg-white w-screen&quot;]/main[@class=&quot;flex-1 flex flex-col overflow-y-auto&quot;]/section[@class=&quot;flex-1 sm:px-4 md:px-8 pb-4&quot;]/div[@class=&quot;sm:max-w-full md:max-w-4xl mx-auto w-full pl-4&quot;]/div[@class=&quot;border rounded-lg p-4 mb-4&quot;]/div[5]/div[@class=&quot;flex gap-4 mb-4 flex-col md:flex-row&quot;]/div[@class=&quot;w-full md:w-1/2 mt-2&quot;]/div[@class=&quot;dropdown w-100 mt-1 d-flex&quot;]/span[@class=&quot;gap-2 w-100    form-control border-primary&quot;]/div[@class=&quot;d-flex align-items-center justify-content-xxl-between justify-content-xl-between justify-content-lg-between justify-content-md-between justify-content-between&quot;]/span[@class=&quot;text-gray-500&quot;]</value>
      <webElementGuid>ab2dc352-e8fb-46e5-b472-732852056bc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[normalize-space()='Patient Relationship to Insured']</value>
      <webElementGuid>bedde853-217f-441f-8c07-81a2e1fcb0a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*[@id=&quot;insurance-relationship-dropdown&quot;]/label</value>
      <webElementGuid>36fe16b2-c3b1-46a9-b3a1-b2cd32ce0d3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
