<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Patient Portal Green Check On Overview</name>
   <tag></tag>
   <elementGuidId>1e695c04-2ff4-4c6b-8687-a671537fa4d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PtOverviewOptOutPP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DashBoard']/div[2]/div[4]/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PtOverviewOptOutPP</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>416c15d2-d97c-4728-8022-5f6265f0b306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mif-SignUp font18 fg-red3 marL5 v-align-bottom</value>
      <webElementGuid>81f29eb8-2800-4024-a86b-cec086430cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PtOverviewOptOutPP</value>
      <webElementGuid>94e8ca0a-a630-45af-b083-9e8b58295b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PtOverviewOptOutPP&quot;)</value>
      <webElementGuid>90dc3bf9-8fea-48b2-8b96-e0080081de52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='PtOverviewOptOutPP']</value>
      <webElementGuid>3337826d-852d-4b66-a429-0b44e4ed643c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DashBoard']/div[2]/div[4]/div/span[2]</value>
      <webElementGuid>8629c213-d683-4600-8b15-e119fda9e354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span[2]</value>
      <webElementGuid>26bb823f-7f46-4f12-aa5e-e5123c2e7f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'PtOverviewOptOutPP']</value>
      <webElementGuid>21128149-d4af-4b78-9afb-f0ba57a3fc89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
