<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Patient Portal_PtOverviewOptOutDatePP</name>
   <tag></tag>
   <elementGuidId>c308c633-8e86-4761-bb11-3a42d0de410e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='PtOverviewOptOutDatePP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PtOverviewOptOutDatePP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PtOverviewOptOutDatePP</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>141f75a1-e06e-4036-8293-540a3fd7ac85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font15 fg-red3 marL5 v-align-bottom</value>
      <webElementGuid>5ae96073-5243-46eb-aba6-8ac1ab274236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PtOverviewOptOutDatePP</value>
      <webElementGuid>6140fe0a-0867-4ac7-90fc-32cddb929ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12/15/2025</value>
      <webElementGuid>f09d4e17-81b4-43ff-bf09-4c5b33f86c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PtOverviewOptOutDatePP&quot;)</value>
      <webElementGuid>d93d40ba-5657-4a92-b845-6f1de1dc14e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='PtOverviewOptOutDatePP']</value>
      <webElementGuid>f0134a5a-429a-4f15-a9c4-8d53dc92edef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DashBoard']/div[2]/div[4]/div/span[3]</value>
      <webElementGuid>83dc1868-a8b5-43c9-bff7-61d68bc6f9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Portal'])[13]/following::span[2]</value>
      <webElementGuid>8e000455-a68f-4210-9853-10b8dfeb85eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comm. Preference'])[1]/following::span[4]</value>
      <webElementGuid>835d9428-45c2-47bd-9572-877b23cff542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HIPAA:'])[1]/preceding::span[7]</value>
      <webElementGuid>3a2bf772-cf53-4311-b798-d1386f2603bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12/15/2025']/parent::*</value>
      <webElementGuid>df8001c5-3427-4faf-a019-937539231135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[3]</value>
      <webElementGuid>b7b1fec7-5f30-4165-8cd5-fa1fb0d68387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'PtOverviewOptOutDatePP' and (text() = '12/15/2025' or . = '12/15/2025')]</value>
      <webElementGuid>3f97a6b0-5a41-49f4-8a2c-be808ea38834</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
