<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_To_mif-search font18 fg-skyblue</name>
   <tag></tag>
   <elementGuidId>82745eda-29e4-4ff2-9089-ac9c153b8323</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mif-search.font18.fg-skyblue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick=&quot;SearchPatientExternalPhysicians('ComposeInboxInput');&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#compose-mainBodySecureMessage >> internal:attr=[title=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d14f6174-30b4-47a0-b4f1-6be095c85e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mif-search font18 fg-skyblue</value>
      <webElementGuid>ca829e54-bc78-4326-8eb8-4cfadb4579cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>44a934cb-f2e0-4fa3-bbfb-3a5af7eeca87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SearchPatientExternalPhysicians('ComposeInboxInput');</value>
      <webElementGuid>3e9570ff-514a-4444-b953-a374c08530cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;compose-mainBodySecureMessage&quot;)/div[@class=&quot;grid no-margin&quot;]/div[@class=&quot;row cells12&quot;]/div[@class=&quot;cell colspan12&quot;]/div[@class=&quot;box_heading&quot;]/div[@class=&quot;box no-background no-border&quot;]/div[@class=&quot;padLR15&quot;]/div[@class=&quot;fluid grid no-margin&quot;]/div[1]/div[@class=&quot;row marT05&quot;]/div[@class=&quot;span12&quot;]/span[@class=&quot;wid&quot;]/span[@class=&quot;mif-search font18 fg-skyblue&quot;]</value>
      <webElementGuid>c4e9f7bc-c35b-4473-ba92-f2fd7400cde6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick=&quot;SearchPatientExternalPhysicians('ComposeInboxInput');&quot;]</value>
      <webElementGuid>d07bb2af-9b03-4b5c-8696-418da07fb968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='compose-mainBodySecureMessage']/div/div/div/div[2]/div/div/div/div/div/div/span[2]/span</value>
      <webElementGuid>900d93e0-4191-46a7-92df-fdf7e83b8f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div[2]/div/div/div/div/div/div/span[2]/span</value>
      <webElementGuid>22a82eac-16bb-4441-9843-7b4ec713221b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Search']</value>
      <webElementGuid>ffbea579-b275-42fd-86e7-75dbe5f3ea81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
