<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Modules</name>
   <tag></tag>
   <elementGuidId>246467c0-88b2-4864-bb10-4697f696aa16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='SavePatientGeneralNotificationOfficeAdmin();SaveMaximeyesPatientPortalData(this);'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Modules&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0dcf6213-fb84-44fe-89f2-df683e806ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>90c401d0-3c8d-4249-9ac4-9aa46d7b35e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-officeadminelementtitle</name>
      <type>Main</type>
      <value>Modules</value>
      <webElementGuid>9b757ec1-3cd7-474e-9b23-7e9e68292f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SavePatientGeneralNotificationOfficeAdmin();SaveMaximeyesPatientPortalData(this);</value>
      <webElementGuid>fc3c229b-121b-4d5c-b506-b608ee09825e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-officeadminmainurl</name>
      <type>Main</type>
      <value>Modules_menu/Home</value>
      <webElementGuid>f5257448-0c16-45f5-a4e5-8cf41de1deb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Office Admin > Modules</value>
      <webElementGuid>1fc4d256-16bc-4c07-b8b6-30ea7baa37ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modules</value>
      <webElementGuid>c2d6e05d-ba77-4100-9fb3-f764c367e8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navMenuOfficeAdmin&quot;)/ul[@class=&quot;app-bar-menu&quot;]/li[8]/a[@class=&quot;Office Admin > Modules&quot;]</value>
      <webElementGuid>5e5fef0d-065f-41e1-8c95-f3f2d55e7321</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='SavePatientGeneralNotificationOfficeAdmin();SaveMaximeyesPatientPortalData(this);'])[3]</value>
      <webElementGuid>b8d35a3c-535d-46ec-b0a9-eabfea347f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navMenuOfficeAdmin']/ul/li[8]/a</value>
      <webElementGuid>c14a5ef3-12f8-48a2-9067-c3045ebbb7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Modules')]</value>
      <webElementGuid>2d3ac1cb-d5b0-40de-ad36-00d26bb702c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office Admin'])[1]/following::a[3]</value>
      <webElementGuid>310724ee-0cb8-4240-991c-62d34ea08e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Insight Agreements'])[1]/following::a[7]</value>
      <webElementGuid>93df940f-07be-4a7f-87a6-c6e4e9b11575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Help'])[2]/preceding::a[7]</value>
      <webElementGuid>0c4c4cb0-074a-49f1-8a26-d7cba754fd70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Modules']/parent::*</value>
      <webElementGuid>053ffe20-5133-40f0-b8b4-8392f5820fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[107]</value>
      <webElementGuid>b6fdbc6d-6164-4244-a644-83bc5ff9c3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[8]/a</value>
      <webElementGuid>6a6e6b56-f9e7-4432-80a6-0d01df1b7f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Modules' or . = 'Modules')]</value>
      <webElementGuid>b4118ba1-1f7d-4ffc-a6b9-9f5f2402ca46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
