<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_gajakumarafirst-insight.com_CreateNew</name>
   <tag></tag>
   <elementGuidId>efb4a1b1-fd2c-4906-9234-3ce15d32388d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CreateNew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CreateNew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add New&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2c36e49-77e9-446b-af30-7e5cd6b06bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>35f0b281-7ca8-4709-a5fc-8216fd13d62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add New</value>
      <webElementGuid>26858bdd-0195-4628-b3ba-34b9db1e9889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CreateNew</value>
      <webElementGuid>b1948e93-9c38-41f9-b2b2-1f69be7d79d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SavePatientPopUp(this)</value>
      <webElementGuid>f5ea4578-24e9-4fff-a4e8-886b0130572c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary small-button padButtonLR</value>
      <webElementGuid>8297f0dc-772b-4655-bba0-afa4ebe56ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CreateNew&quot;)</value>
      <webElementGuid>d7494912-0718-44d8-a000-1d3b4c937570</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CreateNew']</value>
      <webElementGuid>e1ce1fa7-3174-4856-a660-8dce91ce7e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='validatePatient']/div[2]/div/div/input</value>
      <webElementGuid>027b6486-fc0b-4d05-962f-201cd743e3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>c5989e8f-d31d-4adb-b017-e65f9de2f05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'CreateNew']</value>
      <webElementGuid>84622cbc-3004-466d-8cee-806db7ad4823</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
