<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_AddNew_Patient_LastName</name>
   <tag></tag>
   <elementGuidId>4b2a784f-728f-4ac0-8950-de3e2dbc0fde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddNew_Patient_LastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddNew_Patient_LastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AddNew_Patient_LastName</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed42ca16-0ec1-401d-ba25-6b52da40f455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddNew_Patient_LastName</value>
      <webElementGuid>89884a0c-600e-472b-aed4-5861234e987d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>propname</name>
      <type>Main</type>
      <value>LastName</value>
      <webElementGuid>c3b4fcdf-05f4-460f-b969-cb945a0d13a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>aa8d0d26-677f-4a42-9fdc-daa53bacf415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>LastName</value>
      <webElementGuid>d99e4224-02b5-4e7f-a733-6c18c0f90441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~AddNewPatient.PatientInfo.PatientDetail.LastName</value>
      <webElementGuid>f4a44a4e-2d61-4f89-89c7-1e402ada037a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>STRING</value>
      <webElementGuid>08e939b0-276b-4ead-a181-27267f65d32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>PatientDetail</value>
      <webElementGuid>9c1b46bd-cf80-4b47-afcb-2d06030f169f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error-message</name>
      <type>Main</type>
      <value>Last Name is required </value>
      <webElementGuid>29d732ac-77e5-4edc-8b2e-6e2203bf8f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a5bee52d-3ac2-4fba-8409-dccf59bf467f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>Last Name length can't be more than 200.</value>
      <webElementGuid>9514057a-5756-49e1-a6dc-2853eaa33726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>66683606-f720-498d-afa4-a4c29cd22c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>You must enter a Last name.</value>
      <webElementGuid>8caf013c-985a-4931-9673-4c846d831580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>22aa36dd-4e58-43dc-b42c-d6b654b43458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addNewPatient.patientDetails.LastName</value>
      <webElementGuid>05ea689b-4c7b-467f-9891-792ecb55693f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OnDataChanged(this)</value>
      <webElementGuid>8e5b5e3b-5d02-4202-bcb6-e3d96d3ed8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bbe0e292-8010-4c42-8248-67bac87c6b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a7ac19d8-9d6d-42be-b60f-cba837b640a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-validation-error</value>
      <webElementGuid>9f458766-8a20-4b02-bce9-27061b444c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>AddNew_Patient_LastName-error</value>
      <webElementGuid>85beb9a8-21a2-4e13-a451-29094c8b5be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f36b09f2-306e-45bf-a145-488cbbd33f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddNew_Patient_LastName&quot;)</value>
      <webElementGuid>4cfa5ff6-1e30-4905-8a58-fbea27eb5a30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddNew_Patient_LastName']</value>
      <webElementGuid>a65efb1d-1fd5-43e0-bb09-e48cbca71887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewPtDetails']/div/div/div/div/div[2]/div/div/div/div[4]/input</value>
      <webElementGuid>e5cfdf28-9be4-4d3a-ba98-e4964ffbc444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[4]/input</value>
      <webElementGuid>07f0d06d-024a-4323-ad40-694f1bf27264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddNew_Patient_LastName' and @name = 'addNewPatient.patientDetails.LastName' and @type = 'text']</value>
      <webElementGuid>bbf6d6ad-bd65-4007-acdc-4f14a5dedd59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
