<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm your Date of Birth_flex h-10 _4bd2f7</name>
   <tag></tag>
   <elementGuidId>7788f5fc-4c66-4fc9-b37b-99c45960cb4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;MM/DD/YYYY&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eec85a0f-6a6e-4351-8857-87ade8b84dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc1bf884-351e-4fda-a1c0-46382f063037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>5befa92c-ab56-4968-a760-f968c7da4488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex h-10 w-full rounded-md px-3 py-2 pr-9 text-base focus-visible:ring-2 gray-placeholder form-control form-control-lg</value>
      <webElementGuid>e76af047-80c2-4ca4-9a7a-2d816c21391a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/DD/YYYY</value>
      <webElementGuid>0b68e7ea-6b06-404f-bf27-582e208d9dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid min-vh-100 min-vw-100 p-0&quot;]/main[1]/div[@class=&quot;row g-0 min-vh-100 flex-column flex-md-row&quot;]/div[@class=&quot;col-12 col-md-8 d-flex flex-column justify-content-center align-items-center text-center p-3 p-md-5 bg-white&quot;]/div[@class=&quot;w-100 d-flex justify-content-center&quot;]/form[@class=&quot;w-100&quot;]/div[@class=&quot;mb-4 mx-auto&quot;]/div[@class=&quot;relative z-999&quot;]/div[@class=&quot;relative flex items-center&quot;]/input[@class=&quot;flex h-10 w-full rounded-md px-3 py-2 pr-9 text-base focus-visible:ring-2 gray-placeholder form-control form-control-lg&quot;]</value>
      <webElementGuid>ea0906dc-e518-4266-9925-623210b48d82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>1f77b599-4373-48fd-8d9c-dc639d0cfb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/form/div[2]/div/div/input</value>
      <webElementGuid>c40d49b0-8350-4968-8773-f59a526b3f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0cf8626b-005f-49e5-9242-d5eb49d08f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'MM/DD/YYYY']</value>
      <webElementGuid>954f1e80-3c04-4d15-ab08-6bd962d38740</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
