<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Primary_zip-1</name>
   <tag></tag>
   <elementGuidId>91fb86e1-bd93-4b3e-ab4d-05825039cd75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zip-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zip-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#zip-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe7824ff-09ba-4be5-9fa1-a68f4b2b5632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b86b06f-87b7-48ed-8ea0-7b788f73df67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-1 form-control-md flex-grow-1  rounded   block w-full border rounded-md shadow-sm p-2 text-sm border-gray-300   bg-white</value>
      <webElementGuid>b20f2e0c-accd-4e2e-8110-77b59834eb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zip-1</value>
      <webElementGuid>4fe1e0ef-94dc-4d92-ab26-54abf3881d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ZIP Code</value>
      <webElementGuid>100e7faa-03a8-457b-8b6a-c4efa3e385ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zip-1&quot;)</value>
      <webElementGuid>7bfed53c-2607-414f-bf27-75f1b1ce4d5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zip-1']</value>
      <webElementGuid>1b3e383c-1b54-427d-857f-2e82d8ca9400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/form/section[3]/div[3]/div[2]/div[3]/div[4]/div/div/input</value>
      <webElementGuid>0db0c86a-a7cf-4d69-8929-197c468f7c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div[4]/div/div/input</value>
      <webElementGuid>3793b518-c433-46ba-babb-45616ef75818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'zip-1' and @placeholder = 'ZIP Code']</value>
      <webElementGuid>3fed0388-728b-4a5b-897a-16ec4876684a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
