<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Note_labelText</name>
   <tag></tag>
   <elementGuidId>0c6c9d06-917a-4fbb-b587-4a75cc68ea7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#labelText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='labelText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Subject:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>00bd505f-e7d2-4688-ba7f-51f2c30623d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>labelText</value>
      <webElementGuid>08a3dbf8-f87b-4014-a3e5-9063549baee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-capitalize fw-undefined mt-2</value>
      <webElementGuid>d37c1338-307e-4415-a379-a2172825cbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subject:</value>
      <webElementGuid>3ccf0fc7-ff17-4b61-9d43-fdef5c127c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;labelText&quot;)</value>
      <webElementGuid>2c31a5e5-9529-4add-b57a-4797fab88170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='labelText']</value>
      <webElementGuid>b915899f-e9a1-4e0d-996a-9414562796f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/div/div[2]/div/label</value>
      <webElementGuid>0808b60c-3566-4fba-b432-b654f9cc5be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/following::label[1]</value>
      <webElementGuid>f0c2667d-25c8-4931-9b38-1dc983e9ad5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compose'])[1]/following::label[1]</value>
      <webElementGuid>5b31a705-68a9-4b30-994e-07c20a875adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message For Doctor'])[1]/preceding::label[1]</value>
      <webElementGuid>55b0e9e3-7dea-4041-815c-00998a11da66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachments :'])[1]/preceding::label[2]</value>
      <webElementGuid>493dad4e-59f9-402c-9d0e-435e968e567d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subject:']/parent::*</value>
      <webElementGuid>2d6e03a6-fb96-4cf0-aa78-992d13448c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>71acf13b-0e89-4a06-a9b1-51d2ee3a2bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'labelText' and (text() = 'Subject:' or . = 'Subject:')]</value>
      <webElementGuid>2429f6a8-ad19-4e97-a6cc-f9d165f0bd1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
