<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Primary_state-0</name>
   <tag></tag>
   <elementGuidId>6227c1d6-0156-4ed5-8589-72985d1caa3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='state-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#state-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;State for address 1&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9f87a6ca-72f4-448d-9d70-9ec01cdac8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>state-0</value>
      <webElementGuid>d0fa4ff8-d4f0-40ad-8ff4-6311a571a3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full mt-4 border rounded-md shadow-sm p-2 text-sm border-gray-300</value>
      <webElementGuid>47186a0f-af1b-434a-b31b-eb3f86444b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>State for address 1</value>
      <webElementGuid>0a3e73fe-8b6d-4219-b417-efb95e94f3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select StateAAAEAKALAPARASAZCACOCTDCDEFLFMGAGUHIIAIDILINKSKYLAMAMDMEMHMIMNMOMPMSMTNCNDNENHNJNMNVNYOHOKORPAPRPWRISCSDTNTXUTVAVIVTWAWIWVWY</value>
      <webElementGuid>d14bc951-7bdb-4732-87ef-4d0acef03cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;state-0&quot;)</value>
      <webElementGuid>a95f7985-2e58-4f88-85da-f3267b9dd2de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='state-0']</value>
      <webElementGuid>8373f1a2-ebe0-43f3-a678-3a74b3cbf72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/form/section[3]/div[2]/div[2]/div[3]/div[3]/select</value>
      <webElementGuid>e65dbb99-f50d-4132-8ea3-9307492589bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary'])[4]/following::select[2]</value>
      <webElementGuid>08aa5d63-c328-4dad-aa99-2a516f1caf87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Changes'])[1]/preceding::select[1]</value>
      <webElementGuid>9b768d46-2b56-4d07-b4ac-2b860b44ccc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version: 1.0.0'])[1]/preceding::select[1]</value>
      <webElementGuid>943a2a4e-3fbc-432c-9d56-555be578e59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>d0fec452-c92c-4f87-9473-c3eb6daf58e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'state-0' and (text() = 'Select StateAAAEAKALAPARASAZCACOCTDCDEFLFMGAGUHIIAIDILINKSKYLAMAMDMEMHMIMNMOMPMSMTNCNDNENHNJNMNVNYOHOKORPAPRPWRISCSDTNTXUTVAVIVTWAWIWVWY' or . = 'Select StateAAAEAKALAPARASAZCACOCTDCDEFLFMGAGUHIIAIDILINKSKYLAMAMDMEMHMIMNMOMPMSMTNCNDNENHNJNMNVNYOHOKORPAPRPWRISCSDTNTXUTVAVIVTWAWIWVWY')]</value>
      <webElementGuid>87cc507d-ba70-4cb5-92c5-d3c385ed7762</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
