<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Name_suffix-select</name>
   <tag></tag>
   <elementGuidId>13801a4d-f32f-477e-8a12-e10030a2e85c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='suffix-select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suffix-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select suffix&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ca2111f3-649c-4b1b-9e12-403f3c35dd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suffix-select</value>
      <webElementGuid>252dec88-83a3-4e3e-a070-8e7bef05a60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border rounded px-3 py-2 mt-4 border-gray-300</value>
      <webElementGuid>5d2e5929-3309-475c-9238-0dc7cfde00db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select suffix</value>
      <webElementGuid>079ca2ac-128c-47eb-839f-3771cd7c3e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select SuffixJrSrIIIIIIV</value>
      <webElementGuid>22e695ab-40a7-46e7-bcbf-1dcba84028dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suffix-select&quot;)</value>
      <webElementGuid>b25ef7b4-e05c-4a01-81be-88ea157cfafc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='suffix-select']</value>
      <webElementGuid>2ff48f28-3ee8-4f83-a4ba-b1efa41c3bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/form/section/div/div[2]/div/select</value>
      <webElementGuid>3fe34948-830b-4ca7-bb98-7df0ea0e9c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::select[2]</value>
      <webElementGuid>9ef55fbd-1f62-44ef-8966-e8500be5dd72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Demographics'])[2]/following::select[2]</value>
      <webElementGuid>cb32c7d7-8ba6-47d7-b250-3c808a3dac4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone &amp; Email'])[1]/preceding::select[1]</value>
      <webElementGuid>4f49f16c-9238-4c10-bc55-444295e502eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/preceding::select[1]</value>
      <webElementGuid>bcdfcc24-0c99-46a5-ae1f-c6833c75dc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>3b54cd76-ce2b-4778-b424-392f4b074006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'suffix-select' and (text() = 'Select SuffixJrSrIIIIIIV' or . = 'Select SuffixJrSrIIIIIIV')]</value>
      <webElementGuid>2930d9ed-ab78-43b4-9f0a-00698f7e97b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
