<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Practice Location deleted successfully</name>
   <tag></tag>
   <elementGuidId>a72a8653-30e1-4ba0-936e-e370fb22df3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'div') and (position() = 3)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-child(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>318407ca-a19e-4c09-aeb1-afe86112eb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jquery-notific8-message</value>
      <webElementGuid>be91f03f-501e-41ef-aa63-d2b4001a3ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Practice Location deleted successfully.</value>
      <webElementGuid>e3d20a45-390c-4d34-9579-1c34d7d921d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4b8d6619e15a54f8bc4915f4f6984f71</value>
      <webElementGuid>618c42bd-d4de-41b3-a594-98ecf21ca2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'div') and (position() = 3)]</value>
      <webElementGuid>f8592487-94f0-4586-87a7-a942a34bfe46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'div') and (position() = 3)]</value>
      <webElementGuid>c6cfbcdb-b764-4132-9407-912d71600723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Practice Location deleted successfully.' or . = 'Practice Location deleted successfully.')]</value>
      <webElementGuid>f00050aa-9347-4269-881b-6626ecb019ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
