<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PL_Main_Line1_beaee0de</name>
   <tag></tag>
   <elementGuidId>c618f985-2f8b-4969-ba1c-0758f890f4d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'Addresses[0].Line1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;Addresses\[0\]\.Line1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PL_Main_Line1_beaee0de</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9dc5a38-ea2b-41c7-9b61-85df5216b7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PL_Main_Line1_beaee0de</value>
      <webElementGuid>226375de-5920-4fe5-9d91-e26660c3353f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>7bcd9062-36f8-4e93-a705-fed489ed2a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>55</value>
      <webElementGuid>6b61d255-afe7-484b-aad2-6e1bf1b8f303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c4185c2e-640a-4b3c-a363-b3b9b5f1bd23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Addresses[0].Line1</value>
      <webElementGuid>4c703e8e-db9e-4710-8905-aeda969809c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10d3a13a-4fe4-4d11-94bd-bebc082bf1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>8af8e84f-10ce-48f2-bb82-b203111209c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-69fa3105b63c628dfcd2bd7fa4370dfb</value>
      <webElementGuid>73cb7984-2165-4e56-8179-d12af1622c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'Addresses[0].Line1']</value>
      <webElementGuid>e041f046-835a-40ae-b6ec-96dfed448f44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'Addresses[0].Line1']</value>
      <webElementGuid>3908a3c8-4e8f-447d-a801-59bcbf636aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PL_Main_Line1_beaee0de' and @name = 'Addresses[0].Line1' and @type = 'text']</value>
      <webElementGuid>fe586298-b1de-4d27-8cf7-a541bca77ed7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
