<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_ui-id-474</name>
   <tag></tag>
   <elementGuidId>9f74b0bf-9d1c-43d1-b9ad-3ebcb73de22a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ui-menu-item ') and (position() = 1)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.ui-menu-item:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;90008, Los Angeles, CA, USA&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f7fe216c-14eb-492b-8a4d-c1a4c32a2643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item ui-state-focus</value>
      <webElementGuid>36342860-0379-429b-a500-c72c6579ef86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-474</value>
      <webElementGuid>d324cadf-00b1-4aeb-ac5a-0ecf6f225db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>660a91b8-f68e-4bf3-8add-66daf3c6e51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>90008, Los Angeles, CA, USA</value>
      <webElementGuid>4ecc6834-3a6a-41e3-9317-e8e15edcd872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-571b1957791c19cfdb56b4fe89856b71</value>
      <webElementGuid>a0b11d00-8e3b-4ac7-b8c2-ee6891b4680d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ui-menu-item ') and (position() = 1)]</value>
      <webElementGuid>e1e724a3-8990-423c-a81c-25cee813147b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ui-menu-item ') and (position() = 1)]</value>
      <webElementGuid>41cc1c8b-742c-48e1-80d4-ac84b38e21fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ui-id-474' and (text() = '90008, Los Angeles, CA, USA' or . = '90008, Los Angeles, CA, USA')]</value>
      <webElementGuid>6fe5767f-a036-4466-85eb-fe79d3010f97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
