<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Inbox</name>
   <tag></tag>
   <elementGuidId>86706e77-a138-4a3f-a9fc-2d25e597f404</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (position() = 1)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.rounded.shadow-sm .cursor-pointer:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Inbox&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cc9b3636-de70-4212-bcaa-411241457f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-2 hover:text-blue-500 cursor-pointer</value>
      <webElementGuid>59aa77db-bed6-4526-aeca-e12b3ad7d32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inbox</value>
      <webElementGuid>3c458bc6-b106-4b59-98b9-173e52ba3236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ea41d9959a877f3da0dd97e8ba8fe1b3</value>
      <webElementGuid>1e0ac59e-253b-4e15-a5fd-9b966c7c20ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (position() = 1)]</value>
      <webElementGuid>d50660bf-b6fb-4a5f-ba72-b34e40aadbcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (position() = 1)]</value>
      <webElementGuid>c6d8ed85-eb61-4f5b-8a55-28cbf1350d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Inbox' or . = 'Inbox')]</value>
      <webElementGuid>ca40b75b-dc6a-418a-aeae-db267e5a0349</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
