<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OptedOut.pdf</name>
   <tag></tag>
   <elementGuidId>36914533-8dc5-4fb0-ade3-b30fad0f1e6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.underline[data-donotdisable=&quot;true&quot;][data-prevent-remove-onclick=&quot;true&quot;][data-donotremoveclick=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' underline ') and (@data-donotdisable = 'true') and (@data-prevent-remove-onclick = 'true') and (@data-donotremoveclick = 'true')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;OptedOut.pdf&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a8933068-cb5c-4bfa-9dc7-aa73abb0d412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prevent-remove-onclick</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>79229548-586b-42d2-b8e7-ca51b6f7101f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-donotremoveclick</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f67c8ab6-9540-46d3-867e-5f4b46c3149a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-donotdisable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c9de16c-9844-408b-b656-8d60a14579c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline</value>
      <webElementGuid>9cd14ec6-0136-4d95-b49e-51ddadafcd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OptedOut.pdf</value>
      <webElementGuid>27f4a3bc-221d-473c-b043-602c57452c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5f53895a4bc52700c5b02705e2e41fa2</value>
      <webElementGuid>b8397e22-99d0-4363-94a1-ac73257dceb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' underline ') and (@data-donotdisable = 'true') and (@data-prevent-remove-onclick = 'true') and (@data-donotremoveclick = 'true')]</value>
      <webElementGuid>e36720ac-af8f-429b-9a38-d6f67f624c78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' underline ') and (@data-donotdisable = 'true') and (@data-prevent-remove-onclick = 'true') and (@data-donotremoveclick = 'true')]</value>
      <webElementGuid>365007b5-8b7e-4803-9f99-5a9c77f389e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'OptedOut.pdf' or . = 'OptedOut.pdf')]</value>
      <webElementGuid>65637c96-4801-44fe-83ae-5f53e3f0e11e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
