<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PR_EMAIL_undefined</name>
   <tag></tag>
   <elementGuidId>a66139cb-18c4-4caf-9a1a-6e3513919173</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-val-regex=&quot;Phone\ number\ is\ not\ valid&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-val-regex = 'Phone number is not valid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PR_EMAIL_undefined >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3fa8aa90-be4a-4e45-95fe-e83f8ec9b623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>428b00d5-53bf-4918-b281-f02aaeb4acce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-commtype</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>c01811f1-4a03-4ea1-abd4-0f39a13691fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>Value</value>
      <webElementGuid>0568cc6a-a188-4522-9e3f-1fb997680eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>EmailPhone</value>
      <webElementGuid>6c164e30-3fce-4670-8013-ea3a4c625f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PR_EMAIL_undefined</value>
      <webElementGuid>d32cf0e7-63e6-4550-87e5-e24e7c8bab3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Value</value>
      <webElementGuid>4761a9cd-6e18-42fd-8a05-1bd87a1da0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>DuplicateValidation(this)</value>
      <webElementGuid>62b968ae-2c2b-4b40-9f6b-cbdeef6fcaf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2103951e-cc4b-4e15-97de-76f56135f637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2d423f06-8a6b-41a4-9e07-474843fa0523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data_commtype</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>87c20cef-531b-42f1-a68b-c89e220829b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-dependentproperty</name>
      <type>Main</type>
      <value>PatientInfo_IsPhoneWoExtensionRequired</value>
      <webElementGuid>5d26b1c0-3a50-406e-addc-53233559002b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a3926b97-5ea3-469c-a8fc-3cee7ad468f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[0-9]{3}-[0-9]{3}-[0-9]{4}$</value>
      <webElementGuid>034adfd8-9f3c-41d6-99d0-f7b72a5cff57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Phone number is not valid</value>
      <webElementGuid>e6189f62-d4c7-4360-83c3-6f32ef997de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-eb949fdbb9d9439961ca0633fc604c1e</value>
      <webElementGuid>fe292695-c208-4dca-a850-ddf4c4e8ac40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-val-regex = 'Phone number is not valid']</value>
      <webElementGuid>9fff700a-f135-410a-ae35-6caeff89c1f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-val-regex = 'Phone number is not valid']</value>
      <webElementGuid>16e24798-ba4b-49dd-8f2b-2e6748a16113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PR_EMAIL_undefined' and @name = 'Value' and @type = 'text']</value>
      <webElementGuid>c4164102-a193-48f0-b435-72f95ae278a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
