<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Medications_undefinedundefined</name>
   <tag></tag>
   <elementGuidId>d45117c8-c992-4bfb-a275-0a713377f791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.-checkbox.form-check.mb-1.d-xxl-flex.d-xl-flex.d-lg-flex.d-md-flex.d-block.checkbox-hover > #undefinedundefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='undefinedundefined'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Medications&quot;i] >> #undefinedundefined</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b42ff7c8-5ccd-494e-b8b5-d27b85fb1fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1525457c-6376-4ef5-a1ce-033107c92c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>2c782b51-7807-47cb-9391-363a9fb1374f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>undefinedundefined</value>
      <webElementGuid>0e73b898-d6c0-4ab9-8039-c5aa683dd09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>07348150-ab66-4f99-8919-92d57623f72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50&quot;]/div[@class=&quot;bg-white rounded-lg shadow-xl w-96 max-h-[80vh] overflow-hidden&quot;]/div[@class=&quot;p-4 max-h-96 overflow-y-auto&quot;]/div[@class=&quot;space-y-3&quot;]/div[@class=&quot;flex items-center justify-between p-2 rounded-md bg-white&quot;]/div[2]/div[@class=&quot;-checkbox form-check mb-1 d-xxl-flex d-xl-flex d-lg-flex d-md-flex d-block checkbox-hover&quot;]/input[@id=&quot;undefinedundefined&quot;]</value>
      <webElementGuid>a6104faa-e845-4b65-bd08-4a0c110b7916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='undefinedundefined'])[2]</value>
      <webElementGuid>dcd08a8e-0374-4b70-be59-71f090c08b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>7d253f1f-8c4e-44ee-9de0-b2ed6a6f76df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>791494b4-06b8-4af9-9011-437b90176b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'undefinedundefined']</value>
      <webElementGuid>5bdc3a47-5815-4d9f-8ce6-c2022377ac9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
