<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vital signs_undefinedundefined</name>
   <tag></tag>
   <elementGuidId>698245ed-2670-408a-b37e-f07c0f6feeb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.-checkbox.form-check.mb-1.d-xxl-flex.d-xl-flex.d-lg-flex.d-md-flex.d-block.checkbox-hover > #undefinedundefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='undefinedundefined'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Vital signs&quot;i] >> #undefinedundefined</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b2048eb-bff9-4791-b251-df99ff0de76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5a3e9dc6-19d1-4d32-a642-079a03ea1636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>02563463-1d94-4ba1-812d-9e10cd9936a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>undefinedundefined</value>
      <webElementGuid>af033f79-d272-4856-9cdb-2a449b541e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>00b58672-9b23-445a-9eb6-2080117f4765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50&quot;]/div[@class=&quot;bg-white rounded-lg shadow-xl w-96 max-h-[80vh] overflow-hidden&quot;]/div[@class=&quot;p-4 max-h-96 overflow-y-auto&quot;]/div[@class=&quot;space-y-3&quot;]/div[@class=&quot;flex items-center justify-between p-2 rounded-md bg-white&quot;]/div[2]/div[@class=&quot;-checkbox form-check mb-1 d-xxl-flex d-xl-flex d-lg-flex d-md-flex d-block checkbox-hover&quot;]/input[@id=&quot;undefinedundefined&quot;]</value>
      <webElementGuid>f52c7cf6-b0cd-4f28-a6d6-232fec94868e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='undefinedundefined'])[9]</value>
      <webElementGuid>2fe1c37e-063b-48fc-aecf-5f7f14213fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[9]/div[2]/div/input</value>
      <webElementGuid>71c672a9-b641-4ec4-8a83-065b84d07f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/input</value>
      <webElementGuid>83d9d195-e281-4b9c-a258-96706e4e9a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'undefinedundefined']</value>
      <webElementGuid>589e6278-39f9-4989-b39a-bc16897caff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
