<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>XML File</name>
   <tag></tag>
   <elementGuidId>79f01cf4-4e84-4feb-8e57-eb2bc65a84e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div[2]/div/div/div/div/div/div[2]/div[4]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;100740_Test.xml&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de4fea38-919d-418d-ab18-73dcdbfbc3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-between gap-2 bg-gray-100 text-xs sm:text-sm px-3 py-1.5 rounded-sm border border-gray-300 hover:bg-gray-200 transition</value>
      <webElementGuid>a2a07437-62b3-4a62-8201-2fce6ba7bc53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100740_Test.xml</value>
      <webElementGuid>d20588d7-d23d-4fcc-b55d-9b55b77c5fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen w-screen flex flex-col&quot;]/main[@class=&quot;flex flex-1&quot;]/div[@class=&quot;flex-1 bg-gray-50 flex flex-col&quot;]/div[@class=&quot;flex-1 overflow-y-auto pe-3 space-y-6&quot;]/div[@class=&quot;space-y-6 message-view&quot;]/div[@class=&quot;mb-0&quot;]/div[@class=&quot;border-b border-gray-200 p-4&quot;]/div[1]/div[@class=&quot;flex space-x-3&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;flex flex-wrap gap-2&quot;]/button[@class=&quot;flex items-center justify-between gap-2 bg-gray-100 text-xs sm:text-sm px-3 py-1.5 rounded-sm border border-gray-300 hover:bg-gray-200 transition&quot;]</value>
      <webElementGuid>1c63f284-73e7-4ff3-b5b7-13561c578bcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/div/div/div/div/div[2]/div[4]/div/button</value>
      <webElementGuid>52ce53b8-bc82-4498-989e-3679d2030852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bh'])[1]/following::button[1]</value>
      <webElementGuid>d7073895-9b29-4277-9ee0-9cd6293219a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FA'])[1]/following::button[1]</value>
      <webElementGuid>cdf85046-3bb4-4534-9d1b-1cc47e1f17a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[1]/preceding::button[1]</value>
      <webElementGuid>e08bd588-52ff-4c47-af16-ac50ce4c83e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forward'])[1]/preceding::button[2]</value>
      <webElementGuid>5875b703-4d20-46aa-9ae9-3c28703eabba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>088425cd-3fa8-47bb-b074-095f82cfec13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '100740_Test.xml' or . = '100740_Test.xml')]</value>
      <webElementGuid>ca9e3181-3e9c-48f3-b1f8-54f41c99d5c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
