<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Patient Portal</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>gajakumara@first-insight.com;</mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f3dcf058-aae2-49bd-89ea-b6128c41ade8</testSuiteGuid>
   <testCaseLink>
      <guid>ab1f7bdb-9e75-4dc6-bc25-04fb89adf83f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Create_New_Account_Patient_Not_Found_in_MaximEyes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5cdca8e-cbb7-40ed-807c-e4c50b3d6ebf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9c702e1-4439-425a-acc7-eb8d9f8aa27e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c078ad74-df57-4d03-81f9-8c11c53869a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7cdc3331-0fbb-45a6-ae1e-5f0d7df5362a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCForPatient_Signup_for_Patient_Portal_From_Maximeyes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>42f85b43-6e97-4432-9a69-9a6b396d6169</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Edit_Email_on_Portal_Invitation_Popup</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f7c41d07-01e1-4ba2-9084-ad17d7dcabd3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Locking_Account_After_Three_Attempts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a14deff-4215-43e5-b900-685fa839a9d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecb0187d-6c42-4381-aab3-f3e85a5d4a20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>734b2700-7c7c-460d-91d6-1ce07dcaed40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6e56f20-9235-41ed-9b57-28695b3ae96a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9efbc8bf-960d-417e-991d-52fd0425c153</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12d052ad-8685-409a-a03e-da2fcc32e3ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_No_Insurance_Card_Checkbox_Functionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ba19869f-30bc-43cc-8b22-ba348531a898</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_PatientOpt_Out_From_Maximeyes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b948347a-ad4e-43e5-8344-f1e46c6f08cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebf618c7-b1f6-48d9-8e4b-557c0597ecd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b09dd09f-dee3-4148-afed-9c6adaf554f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4475eda4-6482-4127-a832-0ced44ed5767</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0ef440f-9233-4213-a835-18bb50b71453</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c16c8f2-7d7f-458a-a2ef-29fdd6f71136</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32803ddb-dfc0-43df-ba8a-cef8e04fb4d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45617465-cb55-49e7-831c-261fd84cbb91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e609f5f-466a-45e5-8d36-c547879de41b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>44721620-1f27-4b15-a8ab-19fa17b78576</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Print_Sign_Up_Instructions_Maximeyes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>159243c9-8b91-46a3-8720-5dd1ee7c49cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Update_Insurance_Work_Flow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>05d16126-0483-4723-87b0-624b365147be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Upload_Education_Material_to_Patient Portal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>792a6d9a-48b4-4a9a-b68d-48bd3aa1abbf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b9a7a99-8c60-4193-9abf-d0dc9e495a14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Message_Screen_Unread_Messages_and_Pagination</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8e83a1eb-a4ef-4ee1-a717-a633fa2b62b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Upload_Education_Material_for_Final_Diagnosis</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b18cb47b-a37f-4115-ba62-900f181906b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Upload_Education_Material_on_Encounter_Sign_Off</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8a6b899d-8665-45e6-89dc-9cf304fee855</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Verify_Active_User_Not_Logged_Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b499b5d2-365c-44a7-b75d-cdaaf5e76e58</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>769f49d6-2674-4b87-9dbc-8ae85eb33c72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCForExisting_Patient_Match_Full _Account_Activation_Flow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>32063c57-311a-4bed-a526-a3ba351e3a32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Den_Num_Count_MIPS</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>deb0eacc-fff0-4ce3-b053-6beed8049a89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Forgot_Password_Patient_Portal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>20986b6b-56a2-4766-b029-7de71718225a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Forgot_Username_Patient_Portal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>72291f82-f049-455f-9da1-818a750c25d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Health_Summary_Enc_Sign_Off</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3f3f818b-86a2-420f-8433-ef63de4468e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Health_Summary_Flow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1468a76a-4d5a-4290-b599-51c1a89cffdc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21c48a84-0698-477a-a244-1febf745a8e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Patient_Profile_Verification_on_Patient_Portal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62d93c19-1ffc-48cb-b8f5-388560ad1ff1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd344e15-f88f-44ad-8269-ea1f385bd9a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Messages_WorkFlow_in_Patient_Portal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb54e3c5-df68-4c4d-8a87-28a92b181634</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b54b8c7-e271-4069-a42a-70efa6df5a1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86e566f3-cda1-40cf-a52f-e255c91def4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ab9d237-c031-4a6b-af6e-23f5f783cbc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35dd9a16-b1a0-45f3-9b5a-c991ad2b63ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>17442c70-b334-47f7-8941-b57df2cdcab9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Updated_Authorized_Individual_Flow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>386d2302-6635-43e6-9b7f-60dd9961e9e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4477d05b-6930-4e94-b71f-75cf7357b1aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2acecfed-3978-4af3-b17d-c9d89986bab7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60a8cf97-0610-47ca-8f0b-c1437d539030</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Authorized_Access_for__Email_AllUserTypes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fffc611f-b8f7-4bf8-b892-7256c4145728</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e811fe7f-2a0c-4e47-8464-7fa3f03ca430</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Authorized_Access_for_Non_Signed_Up_User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc0e945b-d784-4323-9acc-f2ef6426b2a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53494a25-09bf-4f5b-9394-35f49866939d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Portal_Access_Authorized_Individual</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a53be0aa-f5a0-4ffb-92dd-9ed92745feff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62563bd0-f03c-4c1b-b6cb-6364a9f53777</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/TCFor_Opt_Out_Authorized_Individual</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e784a8ef-4c0b-428e-9a5a-181dc7a7440e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Provider Portal/TCFor_Advance_Pt_Find_On_Secure_Message</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4c0dd2c3-f2fa-475f-b9f3-d22a92c60309</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Provider Portal/TCFor_Attachment_Validation_Compose_Page</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>10a72cfb-be76-4758-a996-47c193f046f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Provider Portal/TCFor_Char_Validation_on_Compose_Page</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3d05c376-10a7-4039-bbc9-681678df4a67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Provider Portal/TCFor_eFiles_Flow_on_Compose_Screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>cf2c38fd-dbf0-4f33-9cf6-91727ca45221</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Provider Portal/TCFor_Find_Refering_Phy_On_Secure_Message</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9a254c0a-9e20-44a8-b871-0fa341e62208</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Provider Portal/TCFor_Provider_Portal_Delete_Messages_Verification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b6954936-4738-4144-b30d-36f19d6eff8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Provider Portal/TCFor_Provider_Portal_Flow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f3f800e4-66a1-4491-bd89-82c33765d4b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Provider Portal/TCFor_Provider_Portal_Forward_Message_Flow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>de514e06-70d6-406b-ada1-f4f042d292e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Provider Portal/TCFor_Provider_Portal_Inbox_Verification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c764e832-16e4-4354-9cb7-eb8d4ae51a8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Provider Portal/TCFor_Provider_Portal_Outbox_Verification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f0cf1a0c-b633-4335-b6a6-c2e209581683</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Provider Portal/TCFor_Provider_Portal_Reply_Message_Flow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7688cddd-d9a3-4b22-8feb-6912993d72f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Appointments/TCFor_Add_Appointment_Reason</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>df83ba7f-ce5b-4bee-8228-8103ee287fa6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Appointments/TCFor_Add_Appointment_Type</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d97b0a5f-d9fc-4858-bed9-441ea96d616c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Appointments/TCFor_Add_New_Appointment_Template</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>70ab917a-1675-44f1-8933-7475e4b47c1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Appointments/TCFor_Create_New_Provider_User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>739f5fef-7791-4533-8ff0-2baea2f87f42</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Appointments/TCFor_Create_New_Schedule_Resource</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>bdd446b0-b66c-4345-9dbe-024b560e8c0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Appointments/TCFor_Create_Practice_Location</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5a7cd448-b9ad-4150-8a79-6988f12fc3e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated Patient Portal/Appointments/TCFor_Schedule_Apply_Template</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
